### ISSUE TITLE
A regression bug for <see cref="T:NameSpace1.NameSpace2.ClassA">?

### ISSUE THREAD

**Issue by livisen** [EWSoftware/SHFB#1007]
After updating to "Help File Builder and Tools v2023.3.4.0", 
the cref like the format <see cref="T:NameSpace1.NameSpace2.ClassNameA"> can't be parsed.
Before updating to the latest version, this format can be supported, our old sandcastle version is very old, but after searching the existing issues, found this format is still the right format.
So wondering if this's a regression bug or not?

**Comment by EWSoftware** [comment]
So what is the issue?  Is it not generating a link or is there some sort of error/warning being generated?  Assuming the ID is correct, it should work.  Can you provide an example?

**Comment by livisen** [comment]
The issue is "not generating a link " and there are warnings.

Example:
The comment in the code.
/// <para>The object does not point to an instance of the <see cref="T:NameSpace1.NameSpace2.ClassNameA"/>.</para>

The final result on help doc:
The object does not point to an instance of the <see cref="!T:NameSpace1.NameSpace2.ClassNameA"/>.

Searching the log, there's a warning.
SHFB: Warning BE0066: ResolveReferenceLinksComponent: [N:NameSpace1.NameSpace2] Unknown reference link target &#39;!:T:NameSpace1.NameSpace2.ClassNameA&#39;.

**Comment by EWSoftware** [comment]
The "!:" prefix in the link in the XML comments file means the C++ compiler isn't able to resolve the link.  That's the place to look.  You should see compiler warnings about the invalid links.  Once you get those fixed and they are generated correctly in the XML comments file, they'll work in the generated topics.  I'm not familiar with the C++ compiler so I can't say for sure whether or not it supports the fully qualified links.  Have you tried it without the "T:" prefix?  Since the type name is fully qualified even without the prefix that may work.

If you can't fix it through the compiler, you can add the [Member ID Fix Ups Plug-in](https://ewsoftware.github.io/SHFB/html/17d977a6-e3dc-4ef4-9bbf-718ef4823854.htm) to the SHFB project.  It was created to fix issues with some known common issues with the way the C++ compiler generates member IDs.  You can add a new entry that replaced "!:T:" with "T:" which should correct the bad ones and allow them to work.  Add other expressions as needed to fix any other such instances.
