### ISSUE TITLE
Issue with Inheriting Class with a Generic Method

### ISSUE THREAD

**Issue by JPalmer-ITSM** [EWSoftware/SHFB#102]
Apologies if the is not the right venue for trying to get help on this issue.

I have a WebGridHelper class that inherits from [System.Web.Helpers.WebGrid](https://msdn.microsoft.com/en-us/library/gg548335). In my generated documentation the inherited AddSorter method appears as **AddSorter``2** instead of **AddSorter<TElement, TProperty>** as per the [MSDN Documentaion](https://msdn.microsoft.com/en-us/library/dn385614(v=vs.111).aspx).

Am I doing something wrong? Am I missing something? or is this a know issue?

Thanks

Jon

**Comment by EWSoftware** [comment]
That's not a standard framework assembly.  Are you seeing warnings in the build log about not being able to resolve the reference link to that method?  That's more likely than not the cause.  You can use the Additional Reference Links plug-in to try and generate reference data for it.  Since it's a Microsoft assembly, you should be able to set the link types in the plug-in configuration to MSDN so that it looks them up online.

**Comment by JPalmer-ITSM** [comment]
Thanks, that was exactly the issue. I followed this advice: https://shfb.codeplex.com/discussions/41971 and all went as expected. The referenced article is quite old, is there a more elegant way than adding an additional Documentation project? For our project it seems like a bit of overkill, but if that is the way it works, then that is the way it works.

**Comment by EWSoftware** [comment]
Right now, it is the only way.  This technically would count as an additional framework or common library of sorts.  I plan on making some changes in this area soon which may simplify adding such framework references with MSDN content in the future.

**Comment by JPalmer-ITSM** [comment]
Thanks for clarifying. I'll keep an eye out for any updated.
