### ISSUE TITLE
Error BE0029: Unexpected error while executing plugin

### ISSUE THREAD

**Issue by saumitramanohar** [EWSoftware/SHFB#1027]
I'm facing the below error while building a project using Sandcastle:

Error BE0029: Unexpected error while executing plug-in 'Website Table of Contents Generator': An item with the same jey has already been added.

Where do I check which is the duplicate key being added to the TOC?

**Comment by EWSoftware** [comment]
An earlier version of SHFB had a problem in the way it was setting titles on empty container nodes in the TOC.  That's fixed in the latest release.  Another potential cause is using an incorrect framework setting such as using the .NET Framework reflection data set to document a .NET 5 or later assembly or vice versa.
