### ISSUE TITLE
Easy to conflict with Microsoft.Help.F1

### ISSUE THREAD

**Issue by livisen** [EWSoftware/SHFB#1042]
In html presentation style VS2013,
For a class member, there are three filed content of Microsoft.Help.F1.
The third 'Microsoft.Help.F1' is really each to be conflicting with other 'Microsoft.Help.F1' as it only has class member name.

https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/PresentationStyles/VS2013/VisualStudio2013Transformation.cs#L1261
![image](https://github.com/EWSoftware/SHFB/assets/23472460/1bf467c5-f33a-4e8d-9d67-a6b5a2241880)

Form the code, this is by-designed and Microsoft.Help.F1 can't be customized, it's fixed.
Just wondering  does there's a chance that Microsoft.Help.F1 only generate first one filed content (namespace + class type + class member) which is unique help id.

**Comment by EWSoftware** [comment]
That is by design and is how Microsoft originally wrote the transformations way back when they were still done with XSL.  If you check any existing API topic in the MS Help Viewer, you'll see it follows the same convention.  It doesn't appear to be causing any issues even in the older Help 1 (CHM) viewer so I'm not sure there's anything that needs fixing.

**Comment by livisen** [comment]
Thanks for the explanation.

Searched Microsoft Help Viewer SDK (https://learn.microsoft.com/en-us/visualstudio/extensibility/internals/microsoft-help-viewer-sdk?view=vs-2022), it downs't say this convention. I am not familiar with this, so it looks like a convention from practice.

Just a note, for below code:

namespace NameSppace_A
{
    ref class ClassA sealed
    {
    public:
        property bool PropertyA
        {
            bool get();
            void set(bool newValue);
        }
    };
}

Currently, content Microsoft.Help.F1 in html file of VS2013 presentation style is this:
<meta name="Microsoft.Help.F1"  content="NameSppace_A.ClassA.PropertyA" />
<meta name="Microsoft.Help.F1" content="ClassA.PropertyA" />
<meta name="Microsoft.Help.F1" content="PropertyA" />

A very old Sandcastle generates this (also generate Microsoft.Help.F1 for property's get/set function).
<meta name="Microsoft.Help.F1" content="NameSppace_A.ClassA.PropertyA" />
<meta name="Microsoft.Help.F1" content="NameSppace_A.ClassA.get_PropertyA" />
<meta name="Microsoft.Help.F1" content="NameSppace_A.ClassA.set_PropertyA" />

Is there a way to also generate "Microsoft.Help.F1" for property get/set function or it is obsolete?

**Comment by EWSoftware** [comment]
How old is very old?  I don't recall it ever doing that and it may have been a bug since getters and setters aren't typically treated separately.  I'm not sure there's any good reason too since they'd end up on the same topic anyway and you're not likely to search specifically for a getter or setter but the property itself.

**Comment by livisen** [comment]
Still thinks for the explanation.

BTW, the old sandcastle is very old.
That old Sandcastle had two separate parts: sandcastle document compiler tools and sandcastle help file builder.  Old enough, ha (latest Sandcastle is a whole, doesn't have these separate parts).
