### ISSUE TITLE
Building with NuGet tools with MsBuild is broken in Visual Studio

### ISSUE THREAD

**Issue by visujomu** [EWSoftware/SHFB#1048]
We use a project build action in the csproj to call MsBuild on the shfbproj file. The SHFB tools are provided as NuGet package.
That way both build agents and developers can build the solution including the help project without further tools or Visual Studio extensions installed.

With the changes of #955 (ffc1b45) this is broken for developers building with Visual Studio as ${SHFBROOT} is no longer defined.
Determining the path to the tools from outside the NuGet package is not reliable.

If there is no better condition for the SHFBROOT property it would be best to provide an unconditional property specific to the NuGet tools (e.g. SFHBNugetToolsPath). With that we can define the SHFBROOT property in our own MsBuild scripts.

**Comment by EWSoftware** [comment]
If MSBuild works from the command line, I'm not sure why it wouldn't work if called from a build event in Visual Studio.  Can you provide an example that I can use to duplicate the issue?

**Comment by visujomu** [comment]
In some (csproj) project file with the SHFB packages included:

```xml
	<ItemGroup>
		<HelpProject Include="HelpProject.shfbproj" />
	</ItemGroup>

	<PropertyGroup>
		<SHFBProperties>
			SHFBROOT=$(SHFBROOT);
			Platform=$(Platform);
			Configuration=$(Configuration);
			ComponentPath=$(ComponentPath)
		</SHFBProperties>
	</PropertyGroup>

	<PropertyGroup>
		<BuildDependsOn>
			$(BuildDependsOn);
			BuildHelpProject
		</BuildDependsOn>
	</PropertyGroup>

	<Target Name="BuildHelpProject" Condition="'$(DocumentationFile)'!=''">
		<MSBuild
			Projects="@(HelpProject)"
			Properties="$(SHFBProperties)"
			Targets="Build" />
	</Target>
```

Nothing too fancy. Just a little wrapping with MsBuild. The properties and target definition are actually in an own imported  .targets file. But as long the language support import (Csharp.targets) is before the property definitions it should work with a single project file.

I hope this helps enough without providing a full working example.

**Comment by Zastai** [comment]
IIRC the problem here is that the MSBuild task runs within the existing MSBuild context - it is not equivalent to running `dotnet msbuild` from the command line.

As such, chances are that the restore has not been done for the shfbproj as a separate pass (and it is that restore that would pick up the nuget reference and set up its build props for inclusion (which would then define SHFBROOT).
You can try first running the MSBuild task with Restore as target, followed by the Build you already have, but I'm not sure that will be good enough. Alternatively, you can use an Exec task to issue a "dotnet restore" on the shfbproj before using the MSBuild task to build it.

Trying to drive a larger build from an MSBuild project really is a losing proposition - there's all sorts of little quirks that can break processing in obvious and less-obvious ways; you're usually better off creating a PowerShell script for that top layer.

**Comment by EWSoftware** [comment]
This is an odd use case.  I'd suggest using a post build event instead which would be equivalent to running it from the command line.  It can run MSBuild to build the SHFB project and should run all the necessary steps including package restore if needed.
