### ISSUE TITLE
Numeric constant formatting for enumeration to allow searching for constant

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#1049]
Is it possible to have enumeration constants formatted without delimiters?  E.g., "1000" instead of "1,000". 

EDIT:  The real problem was that the search wouldn't find 1000 (it's an error code).  We were assuming it was because of the formatting, but the search also doesn't find "1,000" as the enumeration value.  Is that possible?

**Comment by EWSoftware** [comment]
Currently any words containing a digit are filtered out so that would cover numbers as well.  I can update the index to include them.  Words are split on non-alpha characters to it would split the text on the comma.  I'm not sure if there's a good way of handling that.  It may be best to have an option to format the integer values without separators.

**Comment by glenncarr** [comment]
@EWSoftware an option to display integers without separators would be great.  Thanks again.
