### ISSUE TITLE
seealso tag inside of remarks tag renders incorrectly in Default 2022

### ISSUE THREAD

**Issue by FrankHileman** [EWSoftware/SHFB#1068]
I noticed that when using the "Default 2022" presentation style, some members are displayed in a buggy way, and some are not. Specifically, there is too much space on the left, and the "in this article" section is below, instead of to the right. I tracked it down to our use of the `seealso` tag inside of a `remarks` tag. Is this a valid way to use `seealso`, or have I been using it incorrectly for 20 years now? For the help viewer 2.3, it works fine.
![image](https://github.com/EWSoftware/SHFB/assets/17464368/17bfc203-941a-48c3-acc9-ed1587a9417c)

Example of a poorly formatted comment:
```c#
		/// <summary>
		/// Specifies the height of this <see cref="Element"/>. Height is specified
		/// in the Element coordinate space. The <see cref="Transformation"/>
		/// does not affect the Height property.
		/// </summary>
		/// <remarks>
		/// <seealso cref="Size"/><seealso cref="Width"/><seealso cref="Bounds"/>
		/// </remarks>
``` 
Example of a correctly formatted comment:

```c#
		/// <summary>The center of the <see cref="Bounds"/>.</summary>
		/// <remarks>
		/// Center will change if you modify <see cref="Location"/> or <see cref="Size"/>.
		/// </remarks>
``` 
The correctly formatted screenshot:
![image](https://github.com/EWSoftware/SHFB/assets/17464368/f4b79005-8454-4146-a419-9846f89b62f1)

**Comment by EWSoftware** [comment]
The `seealso` tag is a top-level tag so shouldn't be nested within any other tags.  It can be but won't render anything.  In the case above, the `seealso` tags are the only thing in the remarks section.  Since the remarks section only checks to see if there's content and not that it's all valid and actually renders something, the section is still created even though it is empty.  That's likely causing a layout issue of some sort due to the empty section.

**Comment by FrankHileman** [comment]
Thank you Eric. I have been using it incorrectly for decades then. I have a lot of comments to fix.
