### ISSUE TITLE
Whitespace ignored if two formatted words are next to each other.

### ISSUE THREAD

**Issue by digital-ember** [EWSoftware/SHFB#1069]
I'm using version 2024.2.18.0, and it is my first time using Sandcastle.

The following HTML swallows my whitespace between "Hello" and "World!". Is this intentional?

```
<para>
	<legacyBold>Hello</legacyBold> <legacyItalic>World!</legacyItalic>
</para>
```

![image](https://github.com/EWSoftware/SHFB/assets/19651078/9432bfe3-9b10-482a-aabb-02fc38e1a38e)

Juxtaposed to that, this is handling the whitespace just fine:

```
<para>
	<legacyBold>Hello</legacyBold> World!
</para>
```

![image](https://github.com/EWSoftware/SHFB/assets/19651078/77783e0c-0c13-492a-ac85-436011e54830)

**Comment by EWSoftware** [comment]
It's a [known issue](https://ewsoftware.github.io/MAMLGuide/html/b00070c7-9c5e-4b49-ad5c-f55fa866f062.htm) going back to the original Sandcastle tools.  It's been a while since I've looked at it and I think it has more to do with saving the content to the file rather than the actual transformation.  The workaround is to use a non-breaking space between the two elements.
