### ISSUE TITLE
[Call to action] Better support for partials (methods,types etc) in C# XML Doc

### ISSUE THREAD

**Issue by ThaDaVos** [EWSoftware/SHFB#1074]
I am creating this issue to call to action some discussion regarding C#'s XML doc improvements related to partial methods (and maybe more): https://github.com/dotnet/roslyn/issues/60730

**Comment by Lucasharskamp** [comment]
I concur, I was about to make a ticket for this. Auto-generated methods based on partials aren't merged, causing the builder to think XML documentation is missing. This happens with the `RegexGenerator`, the `JsonSerializerContext`, etc.

A relatively simple fix IMO is to skip any component that has a `GeneratedCodeAttribute` assigned to it for documentation, with of course options for the user to decide whether to skip them or not, or which items specifically to skip.

**Comment by EWSoftware** [comment]
@Lucasharskamp If your comments are in relation to the XML comments file itself, you should comment on the linked Roslyn work item, not this one.  It's a compiler issue and isn't something that can be handled by SHFB since it just consumes the XML comments that are generated by the compiler.  Any changes to the comments file have to occur there since SHFB doesn't see the comments in the source code and has no control over how or whether they are merged or not.

If it's in relation to members that are being included for documentation when you think they shouldn't be, that is probably something that can be handled here so create a work item and attach an example to show what you are referring to.
