### ISSUE TITLE
Custom tags and XSLT

### ISSUE THREAD

**Issue by johnnyontheweb** [EWSoftware/SHFB#1085]
Hello,
after a long search over the internet, I cannot ind any working way to add custom tags to the generated documentation, as described for instance here: 
https://learn.microsoft.com/it-it/archive/blogs/sandcastle/supporting-custom-tags-in-sandcastle
https://stackoverflow.com/a/12393192/5278185

I cannot find any relevant *.xsl, *.xslt or main_sandcastle.xsl file to edit, nor in project folder or installation folder "C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder".

I simply want to add some new tags to document my functions. Can you please give some hint?
I'm using the latest version of SandCastle.

**Comment by EWSoftware** [comment]
The XSLT transformations were removed in favor of a more [open and extendable](https://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm) code-based API in version 2022.8.14.0.  See the [Presentation Style Mods Plug-In](https://github.com/EWSoftware/PresentationStyleModsPlugIn) example project.  It shows how to do various things like adding custom element handlers using a plug-in.

In Visual Studio, create a SHFB plug-in project.  You can then add the custom element handlers and the plug-in code to indicate to the presentation style that it should use them.  For an example custom element handler, see [CustomElement.cs](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/main/PresentationStyleModsPlugIn/CustomElement.cs).  See the [Add custom element handlers](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/main/PresentationStyleModsPlugIn/PresentationStyleModsPlugIn.cs#L184) region in the plug-in for how to get it used.

I can provide more details if needed.

**Comment by johnnyontheweb** [comment]
Thanks for the hints, I definitely need more info on that.

I compiled the plugin, and now I'm looking for how to:
- add the plugin to SHFB (there's a list of available plugins, how to load a custom one?)
- modify the "Add custom element handlers" region; I need to write my own CustomElement.cs, right? Is the sample working for the new tag <customElement>? or am I reading it in the wrong way?

Well, not truly a simplification, a few lines in XSLT became an entire plugin; anyway I need it to make it work and thanks for your help.

**Comment by EWSoftware** [comment]
But the old way wasn't just a few lines of XSLT.  You still had to create the presentation style component to expose it, clone the entire presentation style and all of its supporting files, and then modify the XSLT, assuming you have at least a passing familiarity with XSLT which a lot of people do not.  It's also specific to the presentation style.  If you want your changes implemented in other presentation styles or to support other formats such as Open XML and markdown, you've got to repeat the whole process for each of the other presentation styles.  Testing was a matter of trial and error.  Run it, check the output, tweak the XSLT to try and fix issues, repeat.

With the new method, a standard SHFB plug-in replaces the presentation style component.  It just tells the selected presentation style how it should be altered or extended.  The handlers are format-aware so they can render themselves in all output formats that they support and aren't specific to any given presentation style.  It's also written in your language of choice, no XSLT required.  Since it's a standard Visual Studio project as well, you can set breakpoints in it, step through the code, inspect the source topic content and the rendered topic content, and all the other usual debugging stuff.

See the [Creating a Build Process Plug-In](https://ewsoftware.github.io/SHFB/html/a14e026e-642f-4ce6-9506-341e57cc3d1f.htm) topic for info on how a plug-in is created.  You likely won't need a configuration so you can skip that section.

For debugging your plug-in, set the SHFB project's [Component Path](https://ewsoftware.github.io/SHFB/html/e6fcfa33-e7ee-430a-abfe-6b7962e6d068.htm) property to that of the plug-in's assembly.  That allows the standalone GUI used for testing to find it so that you can add it to the project.  Once it's ready for use, it can be deployed as a NuGet package and added to your project as a package reference or it can be installed in the [Third-Party Build Process Plug-Ins](https://ewsoftware.github.io/SHFB/html/a24489fb-45d6-46f4-9eaa-9a9c4e0919b2.htm) folder so that all projects can find it on the local PC.  You can also continue using the Component Path property in the SHFB project to let the project locate it as well.

At the minimum, your plug-in will [indicate](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/3195c280078647f641d8c6f01ab85cba19f145cc/PresentationStyleModsPlugIn/PresentationStyleModsPlugIn.cs#L86C44-L86C81) that it will run before the `BuildStep.CreateBuildAssemblerConfigs` step.  And in the `Execute` method, [add your custom handlers](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/3195c280078647f641d8c6f01ab85cba19f145cc/PresentationStyleModsPlugIn/PresentationStyleModsPlugIn.cs#L193).

You can use the `CustomElement` example as a template.  Your element handler will indicate the element name in its [constructor](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/3195c280078647f641d8c6f01ab85cba19f145cc/PresentationStyleModsPlugIn/CustomElement.cs#L37).  The `Render` override is where you'll render the output.  For the most part it's a matter of creating XML elements and adding them to the current element as shown in the example handler.  The `Render` method is passed the transformation used to render the output and the current element from the MAML topic or XML comments that's being converted.  You can use the `element` parameter to access any attributes on the source element to determine how the output should be rendered such as styles or options to change how it is generated.

To test it, add the new element to a [MAML topic](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/3195c280078647f641d8c6f01ab85cba19f145cc/PresentationStyleModsDocs/Content/Welcome.aml#L59) and/or [XML comments](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/3195c280078647f641d8c6f01ab85cba19f145cc/PresentationStyleModsPlugIn/PresentationStyleModsPlugIn.cs#L49) that will be used by the SHFB project to create the help file.

**Comment by johnnyontheweb** [comment]
Hello,
thanks for the detailed guide. I'm having some troubles when trying to debug the Presentation Style Mods plugin; I did the following:
- under Paths in SHF Builder, I specified the path for the plugin (I'm using VS2022 and Debug version as well, .NET 4.7 as described in help site)
- I attached debugger to SandcastleBuilderGUI.exe (my project is opened)
- I run the compilation of the help from the GUI. I expected a stop in some breakpoints I placed in the code (e.g. in Initialize), but nothing happens. Compilation of the help goes fine but no 

I also updated SHFB to the latest version (v2024.9.12.0), but no changes. Can you please help further?

**Comment by EWSoftware** [comment]
You don't need to attach to SandcastleBuilderGUI.exe.  Just set it as the executable to run in the plug-in project's debug settings.  This should be done by default as it's part of the project template.  Just set the plug-in as the startup project and run it.

**Comment by johnnyontheweb** [comment]
I tried starting the plugin directly, SHFB opens up, but no debugging breakpoint is hit. I believe SHFB loads the plugin correclty, as when I start compiling help, breakpoints become available but debugger won't stop.

**Comment by EWSoftware** [comment]
Sorry, I don't know.  As long as the component path in the SHFB project is set to the path of the plug-in and the debug settings for the plug-in project set $(SHFBROOT)\\Tools\\SandcastleBuilderGUI.exe as the executable to run, it should work.  I tested it with the Presentation Style Mods plug-in and it's working as expected.

**Comment by johnnyontheweb** [comment]
Yes, I can confirm debug settings; DEBUG and TRACE constants are also defined. No breakpoint is hit.
How do I make sure the plugin is loaded? The debug folder is listed into log (as it has been specified in "Project-specific components path"), but I believe no plugin is loaded.
ps. SHFB is the latest version.

**Comment by EWSoftware** [comment]
If it's available in the list of plug-ins in the Plug-Ins property page and you actually added it to the SHFB project, it should load.  If it's generating the expected content in the topics, that would also indicate that it's being loaded.

**Comment by johnnyontheweb** [comment]
> and you actually added it to the SHFB project

That was the point, I believe the search path was doing the work.

**Comment by EWSoftware** [comment]
Just remove the call to add the named section handler.  I don't know what you mean about the title.  If you're not using the section, it won't come into play.  You could remove it from the content file.  As for the custom element handler, make sure the element name specified in the constructor matches the element you're putting in the MAML topic/XML comments.  It is case-sensitive.

**Comment by johnnyontheweb** [comment]
Well, this is exactly what I already tried to do starting from your template. 
1. I removed the call to `transformation.AddElement(new NamedSectionElement("customSection"));`
2. I leave only `transformation.AddElement(new myelem());`

3. Then, I have the custom element class:
```
    public class myelem: Element
    {
        /// <summary>
        /// Constructor
        /// </summary>
        public myelem() : base("myelem")
        {
        }

Having <myelem>mytext</myelem> in documentation, I expect that mytext appears somewhere, but it's not.
I believe it's not working because the Render function is never hit during help compilation. Only "RenderCustomSection" is hit. Maybe an additional handler to be added?

**Comment by johnnyontheweb** [comment]
One of the way is to add to RenderCustomSection the following code:
```
            var mye1 = transformation.CommentsNode.Element("myelem");
            if(mye1 != null)
            {
                transformation.ElementHandlerFor("myelem").Render(transformation,mye1);
            }
```
Hence Render is hit. Please tell if I can do it in a simpler way.

**Comment by EWSoftware** [comment]
Can you attach the project so that I can see what you're doing and build it myself?

**Comment by johnnyontheweb** [comment]
I'm sorry I cannot share it

**Comment by EWSoftware** [comment]
Can you get the presentation style mod's plug-in working with your custom element as an example?  Otherwise, there's not much more I can do to help you without seeing what you are doing differently.

**Comment by johnnyontheweb** [comment]
Yep, I was able to render (simply, without formatting because the CSS stile used as sample affected all subsequent parts) the new XML elements to the guides. To recap, the only things I changed are:
0. renamed "CustomElement" to "myelem"
1. commented `transformation.AddElement(new NamedSectionElement("customSection"));`
2. to make it work, I added in RenderCustomSection:
```
var mye1 = transformation.CommentsNode.Element("myelem");
            if(mye1 != null)
            {
                transformation.ElementHandlerFor("myelem").Render(transformation,mye1);
            }
```

I changed nothing else. By doing 1 only, you reported it should work, but in my case it isn't.

**Comment by EWSoftware** [comment]
You don't need the RenderCustomSection method to render your custom element.  But, like I said, without an example to see what you are doing, I can't help you any further.

**Comment by johnnyontheweb** [comment]
Hi @EWSoftware,
finally, I make the plugin work fine, and I used it successfully (until today I used SHFB 2024.2.18). 
Today, I installed latest version  and I noticed that the plugin is not working anymore. 

```
		Initializing
SHFB(0,0): error BE0028: Plug-in loading errors:
		Failed

SHFB: Error BE0028: Plug-in loading errors:
Error: Unable to locate plug-in 'Presentation Style Mods' in any of the component or project folders and it cannot be used.

   in SandcastleBuilder.MSBuild.BuildEngine.BuildProcess.LoadPlugIns()
   in SandcastleBuilder.MSBuild.BuildEngine.BuildProcess.Build()

```

Hence I updated the nuget packages linked in the plugin, but nothing - is there a migration guide?
thanks in advance

EDIT
I tried to download https://github.com/EWSoftware/PresentationStyleModsPlugIn , compile and start with it - same error. There's something uncompatible with this plugin in SHFB 2026.3.29.0 .

**Comment by EWSoftware** [comment]
I'm not aware of any issues.  The Presentation Style Mods project is working as expected for me.  I downloaded the code for it and built it that way too and it worked without any issues.  As long as the NuGet package is up to date in your project, things should work.  The [migration topic](https://ewsoftware.github.io/SHFB/html/bc933f8f-e792-45bf-afec-62aa2c46aa3b.htm) covers issues that may be encountered.  Since you were using 2024.2.18, you may need to remove the one package and make some adjustments as noted in the topic.

**Comment by johnnyontheweb** [comment]
Thanks, after days of struggle I finally solved by following the migration topic you linked - I didn't find it before.
Have a good day!
