### ISSUE TITLE
How to code help and support files?

### ISSUE THREAD

**Issue by jeffman1** [EWSoftware/SHFB#110]
I realize that help and support files for windows local help are *.mshc and *.mshi but how do I do this with sandcastle? *.mshi can only be built from what I know with HelpIndexer.exe from the Windows 8.1 ADK tools. The trouble I am having is knowing the correct structure of *.mshc and *.mshi files in order to get my help files to appear in help and support. Maybe a tutorial or a tool that makes the correct structure and build the mshc and I copy the files to help and support? I am wanting to do this for some content I am working on. My current project has me doing this. Here's the link I am referencing and the one for the main pages in help and support is right above it in the left menu on MSDN:
https://technet.microsoft.com/en-us/library/hh825704.aspx. Note: my *.mshc and *.msha files created by sandcastle work flawlessly in visual studio 2013's help viewer 2.1 so its not a question of if they are not correctly formatted (it maybe structure as stated above or registry entry to register them in help and support or something I have overlooked).

**Comment by EWSoftware** [comment]
The MS Help Viewer format in SHFB is geared towards Visual Studio's help viewer, not the OS help and support viewer.  Based on a quick look at the page you referenced, I'd guess the main problem you are encountering is that the compressed help file is not using the correct folder structure.

See the section titled *Create the Content Package*.  As I read it, the content must be placed into three specific folders (*.\images*, *.\resources*, and *.\topics*).  That's not the case for help viewer files where there isn't a folder structure requirement.  Currently, several folders are used (*.\icons* and *.\media* for images, *.\scripts* for script files, *.\styles* for style sheets, and *.\html* for the topics.

SHFB could be extended to create help and support files but it would require a new file format option and most likely a specific presentation style due to the folder structure requirement.

**Comment by jeffman1** [comment]
Would it be possible to add support for help and support since it more of a structure problem then a change file format? (*.mshi would end up being built separately anways.) I will try to do that but I am not for sure if its the only problem. Here's some possible registry entries I am looking at that might relate to the above ADK options in the topic link I gave above: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\HelpAndSupport and HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation. HelpIndexer.exe could be added to index the files for help and support or I could add it as an external build program into sandcastle in-order to build the *.mshi files.

**Comment by EWSoftware** [comment]
As noted above, yes it is possible.  To do it properly would require a new help format option as then it could either generate the index file or at least a sample script that shows how to index it and install it like the MS Help Viewer format does now.

If you want to add it to the existing release, then a presentation style would probably suffice.  You could probably clone the VS2013 presentation style and then change all the places where it references a path to send the items to the expected locations.  That would mainly be the BuildAssembler configuration files and the one resource item file (shared_content_mshc.xml).

The Help and Support format isn't something I've done anything with before so I'd need to research it to see what other issues there may be.

**Comment by jeffman1** [comment]
![logo](https://cloud.githubusercontent.com/assets/8669720/7973747/0119a154-0a27-11e5-9274-e9f258cbef69.png)
I have the above image I would like to determine the black RGB color code for windows how do I do that?

**Comment by EWSoftware** [comment]
I don't know.  Open in it Paint.net or something similar?  They should have tools that give you the color values for any given pixel in the image.

**Comment by EWSoftware** [comment]
Closing as this doesn't even seem to be an option past Windows 8.1.  The referenced documentation is obsolete and there doesn't appear to be an equivalent for anything newer.  All custom help appears to be web-based now.  If it is still possible and somebody wants it and can point me to the relevant current documentation, I can reopen it.
