### ISSUE TITLE
IntelliSense Component output deleted if Website Build is selected

### ISSUE THREAD

**Issue by StevenBonePgh** [EWSoftware/SHFB#111]
I have a project that builds a .chm file and I also use the IntelliSense component.  This works great in the current build of SHFB - the .xml files are written to the 'Help' subfolder as expected.  When I checked the box next to the Website in the build list, I stopped seeing the IntelliSense files in the output directory.

It appears that they are being created, then when then the Website build happens it deletes all of files and folders in the output folder(exempting 'working' and the lastbuild.log), including the files generated by the IntelliSense component.  

As a workaround, I changed the output path of the Intellisense component to "{@ProjectFolder}IntelliSense" instead of the default "{@OutputFolder}".  Setting it to a path under "{@OutputFolder}" will cause it to be deleted when the Website builds.  To assure they do get generated and are not hanging around from a previous build, I added a pre-build step to remove the directory: rmdir /S /Q "$(ProjectDir)IntelliSense"

Sadly, the pre-build does not expand the $(ProjectDir) token, nor does it expand the SHFB token {@ProjectFolder}, so what is executed as per the build log is [rmdir /S /Q "IntelliSense"]  Since the "Edit Pre-Build Event" button brings up the normal VS tokens, I imagine this is a bug.  I'm using VS 2013.

I'm not certain that the 'IntelliSense Component output deleted if Website Build is selected' is a bug or intentional.  If intentional, perhaps defaulting the output of that component to a different path and some surrounding documentation/FAQ would be advisable.  I'd like cleaning up the old output to be part of the component as well.

Thanks for the excellent product! 
Steve

**Comment by EWSoftware** [comment]
The pre-build and post-build event properties need to be added to the very end of the project after the target file import like this:

``` XML
<Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" />

<PropertyGroup>
  <PreBuildEvent>ECHO "$(ProjectDir)IntelliSense"</PreBuildEvent>
  <PostBuildEvent>ECHO "$(ProjectDir)IntelliSense"</PostBuildEvent>
  <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
</PropertyGroup>
```

This is necessary to allow the `PreBuildEvent` and `PostBuildEvent` targets to be evaluated correctly.  They're imported from *Microsoft.Common.Targets*.  The events weren't supported until a few versions back so if they aren't in the project already, they'll most likely get added somewhere ahead of the import statement and thus don't evaluate correctly.  I didn't have them in the project template files either so I've added them and they'll be there in the next release for any newly created projects.  I'm not aware of any way to control where new properties get added in a project.  You can edit the SHFB project in a text editor and move the properties to the end of the file manually to correct the problem.

The deletion of the website output folder is by design to clear out any prior content so that it doesn't accumulate content from prior builds that is no longer relevant.  This is noted in the Paths property page (the warning icon) as well as the help file.  I suppose it doesn't matter when the folder is cleared so I could move that part to the start of the build where it deletes the other help format files.  There shouldn't be any issues so I'll look into it for the next release.

At least for the time being, if you want other files retained, they will need to be placed elsewhere, in this case by configuring the plug-in.  I can update the plug-in documentation to note this potential issue.  Clearing the prior IntelliSense output in the plug-in would be problematic.  What should it delete?  It can't assume everything should go and it can't assume just **.xml* as there may be other files that should be kept.  Likewise, it can't do it explicitly by complete filename since it doesn't know what may have been removed.  The pre-build event is likely the best option for the time being.

**Comment by StevenBonePgh** [comment]
Thank you Eric.  What you said makes 100% sense, and your solution for the PreBuildEvent target evaluations worked like a champ.

**Comment by EWSoftware** [comment]
I was able to move the code that deletes the prior web/markdown content to the start of the build where it deletes the other help format output.  That change will be in the next release.  With that in effect, it won't delete the extra files anymore at the end of the build.

**Comment by sharwell** [comment]
Awesome :+1:
