### ISSUE TITLE
Consider using tunnelvisionlabs/MPFProj10

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/SHFB#13]
It's deployed as a NuGet package. It would make sense to move toward using that. However, when I had a quick look at the code a while ago it was missing a few bug fixes that I had in the SHFB copy (one in Utilities.cs related to recursive copies and one in FileNode.cs related to in-place renaming of a file that caused a problem with source control are the two I recall).  The code needs to be compared to see if anything else is missing and make them equivalent with regard to fixes.  Once done, the local copy of the MPFProj could go away in favor of the package.

**Comment by sharwell** [comment]
I agree that the project should migrate to it *eventually*, for the following reasons:

1. (Concrete) The implementation of Show All Files in the tunnelvisionlabs project is fast, even if the folders underneath the project include build output with thousands of files. The current Show All Files implementation for SHFB is slow enough to convince most users the IDE is hung.
1. (Theoretical) The standalone project provides a better opportunity for multiple project systems to contribute bug fixes / improvements.

I actually already created a local branch to experiment with the transition, and it was quite successful.

However, there are a few reasons why I don't think we should proceed with this *yet*.

1. There are a few remaining bugs in the tunnelvisionlabs project.
2. We should wait for the first stable release of the library, since it could be shared across multiple projects.

**Comment by sharwell** [comment]
I think I found all of the major cases. Right now I'm working on making sure the integration test framework works properly so I can create regression tests as each of these is fixed.

**Comment by sharwell** [comment]
I think this should be closed in favor of #90.

**Comment by EWSoftware** [comment]
Closed in favor of #90.
