### ISSUE TITLE
I would very much like to see a MAML designer in Visual Studio

### ISSUE THREAD

**Issue by SetTrend** [EWSoftware/SHFB#131]
Editing SHFB projects using the Visual Studio extension is great. But editing a MAML file is extremely awkward, particularly as it doesn't WISIWYG. You always have to compile a project to see the results of your edits.

I'm strongly missing a MAML designer view. A split view would be the paramount solution, so the author would be able to choose whether to edit the MAML file itself or the designer's output.

A poor man's shortcut would be to allow HTLM files to serve as MAML source in a SHFB project. Using these, the full editing capabilities of Visual Studio would already exist at hand. All there'd be required was a SHFB HTML > MAML converter run at compilation.

**Comment by EWSoftware** [comment]
You don't have to compile the project to see the MAML topic results.  There's a [Topic Previewer tool window](http://ewsoftware.github.io/SHFB/html/d3c7584d-73c0-4725-87f8-51e4ad956694.htm) to preview the topics without a build (*View | Other Windows | Topic Previewer Window*  or select it from the *Other Windows* tool bar button).  It shows the topics and information from related files (images, code snippets, tokens, etc.) including any unsaved topic edits.

Making the HTML to MAML converter part of the build is not optimal nor really feasible as there are typically many edits that need to be done to the resulting MAML topics in order to get them working as expected (see the HTML to MAML converter help file for all of the warnings, TODO items, and common issues resulting from conversion).  Unfortunately, doing a full fledged WYSIWYG/split view editor is well beyond my capabilities so it's not something that I'm going to tackle any time soon.

**Comment by SetTrend** [comment]
Thank you so much for pointing me to the Topic Previewer tool window, Eric. I didn't know it existed in the first place.

I very much comprehend that such implementation would be tedious and a long way to go.

Well opening the Topic Previewer tool window as a document window will (I'm guessing here) serve the same purpose at this time.

Problem solved.

I wonder why no-one at Microsoft is making a pull request on this. They are so fond of their GUI but don't support creating help files at all. Gee ... ;)
