### ISSUE TITLE
How can I install two versions of SHFB side by side on the same machine?

### ISSUE THREAD

**Issue by matroberts** [EWSoftware/SHFB#133]
Hi,
We've been using SHFB for a few years and are very please with it.

I have been looking at upgrading from version 1.9.7.0 to V2015.5.2.

On our build server I want to install both versions of SHFB side by side.
This way our branches can continue to build their docs against v1.9.7.0,
and I can upgrade our trunk line to run against the new version 2015.5.2

However when I install V2015.5.2, the old version of SHFB is uninstalled,
even if I choose a different location for the new install.

Any thoughts about how I can achieve my goal?

Cheers
Mat

**Comment by EWSoftware** [comment]
Install each version separately somewhere then XCOPY the files to the build server placing the two versions in separate folders.  In your build process, you'll need to define the SHFBROOT environment variable so that each build find the version it needs.  See the [XCOPY/NuGet Build Server Deployment](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm) topic for more information.

Regarding the NuGet package, there isn't a version for the current release.  I'm making changes to better support it for the next release.  For the current release, you can define the SHFBROOT variable within the project as described in the above project without the condition attribute.  Point it at the folder you copied the files to and it should work as expected.  The older 1.9.7.0 release may be more dependent on the environment variable.

**Comment by sharwell** [comment]
@EWSoftware Were there two environment variables in use for 1.9.7.0, or were they already consolidated to `SHFBROOT` at that time?

**Comment by EWSoftware** [comment]
SHFBCOMPONENTROOT was still in use but only if third-party components were in use and not in the common location.  I'm not sure it ever got much use.

**Comment by sharwell** [comment]
:+1:

**Comment by matroberts** [comment]
Thanks guys.  I blundered my way to the same solution.

Copy the installations of SHFB to new location on disk.
For 1.9.7.0 also copy the installation of Microsofts Sandcastle to a new location.

On the build server we call SHFB with msbuild.

For V2015.5.2, as you say, we just have to set SHFBROOT:
```xml
  <Target Name="BuildSdkDoc">
    <PropertyGroup>
      <ShfbRoot>C:\Sandcastle\Sandcastle Help File Builder_v2015.5.2.0</ShfbRoot>
    </PropertyGroup>
    <MSBuild Projects="Biomni.FrontOffice.Sdk.shfbproj" Properties="SHFBROOT=$(ShfbRoot);" />
  </Target>
```
For the older version 1.9.7.0, we also have to set 'SandcastlePath', 
which is the path to Microsoft Sandcastle.
My understanding is that in newer versions of SHFB 
Microsoft sandcastle has been fully incorporated into SHFB. 
```xml
  <Target Name="BuildSdkDoc">
    <PropertyGroup>
      <ShfbRoot>C:\Sandcastle\Sandcastle Help File Builder 1.9.7.0</ShfbRoot>
      <MsSandcastleRoot>C:\Sandcastle\MsSandcastle 1.9.7.0</MsSandcastleRoot>
    </PropertyGroup>
    <MSBuild Projects="Biomni.FrontOffice.Sdk.shfbproj" Properties="SHFBROOT=$(ShfbRoot); SandcastlePath=$(MsSandcastleRoot)" />
  </Target>
```
