### ISSUE TITLE
Publish XML comments guide in each supported presentation style

### ISSUE THREAD

**Issue by sharwell** [EWSoftware/SHFB#134]
The XML comments guide contains a wide array of markup functionality in a relatively small site. It would be nice if each release included a copy of this guide (available online) in each of the official presentation styles supported for that release.

**Comment by EWSoftware** [comment]
I could see perhaps publishing an Open XML document version so that its useable offline.  I'm not sure I see any real benefit to publishing it using the markdown and VS2010 styles.  Markdown takes on the style of the site you upload it to and VS2010 looks sort of like the help in VS2010.  Not much else to see really.

**Comment by EWSoftware** [comment]
Thinking about this again, I see no real benefit.  The help content is already in Help 1 format for offline access so an Open XML version would serve no other useful purpose.  As for examples of the presentation styles, it's a simple matter to create a small project and build it using the various styles to see how they look.  I can't see any benefit to adding to what has to be done to produce a release and then host a lot of redundant, duplicate content.
