### ISSUE TITLE
Namespace grouping not working flawlessly?

### ISSUE THREAD

**Issue by SetTrend** [EWSoftware/SHFB#137]
This is strange:

Although I have set namespace grouping to 4, only one namespace grouping has taken place in the following screenshot:

![5](https://cloud.githubusercontent.com/assets/9283914/8512376/ec66ae8c-233f-11e5-9c9b-186d1feab279.png)

Why haven't ` aa.bb.cc.Client ` and ` aa.bb.cc.Client.Untyped ` been merged? Is there a switch available to switch grouping on or off?

Actually, I'm very satisfied with the result: The Client project is in fact supposed to be split up, and the ServiceHost project is supposed to be grouped. But I want to understand how I can control this.

**Comment by EWSoftware** [comment]
The "Enable namespace grouping" option can be turned off to disable grouping altogether.  The rules it uses to create the groups are defined in the [property help](http://ewsoftware.github.io/SHFB/html/1b2dff59-92cc-4578-b261-f3849f30c26c.htm#NSGrouping).

Most likely, your not seeing a group because the tool determined it didn't make sense in that particular case.  It won't in some cases like putting a single group as a child of another group.  In such cases the content of the nested group gets merged up into the parent group.  As far as I know it's working as expected as I went through several iterations with the latest release to clarify the rules it uses and fix issues from prior releases.

If you've got a case that you don't think is working right and can submit an example, I'll look into it.

Eric

**Comment by EWSoftware** [comment]
In going through the change notes for the upcoming release, I do see one additional pull request that fixed a minor issue with the namespace grouping support.  It may affect the case above.  Hold off submitting any examples until after the new release.  If you still think there's an problem, re-open this issue and submit an example.
