### ISSUE TITLE
Don't include implementation information for non-public interfaces in documentation

### ISSUE THREAD

**Issue by roryap** [EWSoftware/SHFB#145]
I have a public class which implements an internal interface. I would like my documentation not to expose the interface since it's internal, but it does:

![2015-07-14_9-18-57](https://cloud.githubusercontent.com/assets/13333455/8674491/324c3052-2a0c-11e5-9cdc-8ed03e5a9050.png)

Is there a setting in sandcastle for this? I've scoured the documentation and the GUI but couldn't find it.

**Comment by sharwell** [comment]
:+1:

**Comment by EWSoftware** [comment]
The second condition and return value of the no-PIA check in ApiFilter.IsDocumentedInterface() are backwards.  I'll get it fixed for the next release.

Bear in mind that if you don't implement the interface explicitly, the methods of the interface will show up in the implementing type as normal public members.  You can exclude them with the API filter or implement the interface explicitly.  If implemented explicitly, the members won't show up even if the EII option is enabled since the interface is internal.
