### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by jsblock78** [EWSoftware/SHFB#147]
It looks like the NuGet package is using version 2014.11.22.0. Is this by design or a more stable version? Or would you recommend using a later version of the software?

**Comment by EWSoftware** [comment]
Changes to how the reflection data is handled pushed the package size over the maximum allowed so the past couple of versions haven't had a corresponding NuGet package.  I've reworked the reflection data so that it can be distributed separately effective with the next release which will be out in a couple of weeks.
