### ISSUE TITLE
TODO: Add Project Name

### ISSUE THREAD

**Issue by MihaIvan** [EWSoftware/SHFB#16]
I am just getting started in some help authoring and put together a very simple sample to get to know the system. I "borrowed" the MAML from somewhere on the internet and changed it. However when I compile it into a chm, my topic shows this after the question mark help logo:
Welcome to the [TODO: Add project name]
I don't see any documentation for this. In your help, it says to post questions on this type of thing on CodePlex, but followed you here. Don't know if the protocol is the same, so I just took the chance.

So how do I fix this. Don't see a reference to Project Name in any properties. Don't see a tag anywhere I can set. Don't even know where the "Welcome to the " portion of the heading came from. So I am at a loss here.

It seems like there are some of these TODO things are inserted by SHFB. Unfortunately, it also appears that they are put into the sample or templates, and I have no idea what is coming from samples and what is coming from SHFB trying to tell me to do something. Or do I have even that wrong? If I am right, it would be helpful to distinguish between the two.

**Comment by EWSoftware** [comment]
Since I don't know what you "borrowed" I'm going to have to guess.  If you're seeing the "TODO" in the topic, it's probably in the related topic file (Welcome.aml for example).  If you're seeing it in the table of contents, it's probably in the content layout file (ContentLayout.content for example).  You should find both files in the SHFB project.  Open the files to edit them.

If you create a new SHFB project, it will contain some default items and an introductory topic that explains the project layout.

If you're new to SHFB, I'd suggest working through the [Getting Started](http://ewsoftware.github.io/SHFB/html/b772e00e-1705-4062-adb6-774826ce6700.htm) topics as they will answer a lot of your questions and will help you get familiar with the tools.

For information on conceptual content and content layout files, see the [Conceptual Content](http://ewsoftware.github.io/SHFB/html/3d4edd2d-7883-4508-b9d2-bd7b4d848b0d.htm) topics.

To get familiar with MAML, see the [Sandcastle MAML Guide](http://ewsoftware.github.io/MAMLGuide)

**Comment by MihaIvan** [comment]
OK, I thought just expressing the message might be all I needed. I started over. Here are the steps:
1. Create a new documentation project in Visual Studio 2013 Professional using Sandcastle Help File Builder Project.
2. Checked HTML Help 1 (chm) in Build tab of the project properties.
3. In the Help File tab, changed the Help Title to DBSetup Help.
4. In the Help File tab, changed Help file name to DBSetupHelp
5. In the Plug-ins tab, added Additional Content Only and made sure it was checked.
Without changing anything else, I did a build on the project.
The resulting help file has the problem I described. 
I searched all the .aml files in the Content folder and found nothing that contained the word "Welcome" so I have no idea where that heading is coming from and why it would have the TODO in it. Here is the top two lines from the help topic that comes up when I open the DBSetupHelp.chm file.

 Welcome to the [TODO: Add project name] 

This is a sample conceptual topic. You can use this as a starting point for adding more conceptual content to your help project.

**Comment by MihaIvan** [comment]
OK. I did a search of the project on "Welcome to the" and found it in the ContentLayout.content file. I changed the TODO and did a build and it got rid of the problem. It would be VERY helpful to be able to locate where the TODO is supposed to be done. It steepens the learning curve a lot and Help is not a full time job for me, so the less effort I can put into getting it done, the better it is for my productivity.

Thanks.
