### ISSUE TITLE
Question on embedding graphs with link annotations

### ISSUE THREAD

**Issue by Stoffelche** [EWSoftware/SHFB#163]
Is it somehow possible to embed images like for example class hierarchy diagrams, where the individual nodes of the diagram directly link to the class documentation?
Thanks, Stefan

**Comment by EWSoftware** [comment]
There's no MAML equivalent but you could use the `markup` element to pass through a chunk of HTML that implements an image map HTML element.  However, that wouldn't work for Open XML output and it's doubtful it would work in MS Help Viewer output since the viewer tends to rewrite the link targets and it probably wouldn't handle the ones in the image map elements.  If all you are generating is MS Help Viewer output and it didn't work, you could figure out what the links were supposed to be and hard code them in the expected format.
