### ISSUE TITLE
Question on generating Assembly documentation

### ISSUE THREAD

**Issue by Stoffelche** [EWSoftware/SHFB#165]
I would like to try to generate an Assembly documentation similar to the namespace documentation.
The automatically generated Assembly documentation would contain a link-list of namespaces, similar to the namespasce documentation containing a list of types.
Then in a second step one could invent some merging of manual documentation with the automatic documentation similar to the NamespaceDoc mechanism.
I guess I could start by checking out the code which generates the namespace documentation.
For this I would be grateful for some pointers on where to start looking.
Thanks, Stefan

**Comment by EWSoftware** [comment]
You'd have to create a new group container in the reflection data much like the namespace group entries.  This requires a significant number of changes:

1. Namespace entries in the reflection data do not contain any assembly metadata so you'd have to create a tool to generate that information based on the types in the namespaces and add the new assembly group entries much like the *AddNamespaceGroups* tool does.
2. SHFB would be unaware of these new group containers so you'd have to update the build engine itself to handle them much like it does the group namespace containers.  That would include support for something like an `AssemblyDoc` class in the code to put assembly comments in the code as well as handling them in the Namespace Summaries project property.
3. The presentation styles would need to be updated to handle the new assembly group containers and actually generate the topics information.
4. More likely than not, you'd have to create a new document model transformation to group everything by assembly rather than namespace.  No such transformation currently exists so you'd be doing it from scratch.

That's no small amount of work and I don't see much use for it.  Bear in mind that namespaces can appear in multiple assemblies so any given namespace may appear in multiple places and now you've got to look in multiple places to find them all.

I'm much more interested in knowing what types are in a namespace as opposed to what namespaces are in any given assembly.  To know what assembly I need to reference I can look at the type's topic and find the assembly name there so grouping by assembly doesn't really add anything.

**Comment by Stoffelche** [comment]
I can follow you in the sense that a namespace can be used in more than one assembly. But it would not be necessary to remove the namespaces from the top level toc structure and replace it with the assemblies. 
One could have an additional TOC entry *Assemblies*, which contains info about the assemblies. This could be a combination of automatically generated content like a list of links to the namespaces used in the assembly, combined with user-edited content coming from an AssemblyDoc class simiilar to the NameSpaceDoc class.
My point is the following:
When one decides to create an assembly and to put code into it, one has a reason for it, in analogy to the reason for a decision to create a namespace.
Also most certainly there are usage notes and use cases and notes about dependencies and .. and .. which apply to the assembly as a whole and not to a single namespace inside this assembly.
This IMO induces the same necessity to document an assembly as there is for documenting a namespace.
Certainly one could do this in a conceptional topic, but this is true for a namespace as well. When handling assembly documentation similar to namespace documentation instead of having to do it in a conceptual topic one has the possible advantage of an automatically generated list of links to the contained namespaces.
Also, when I have a conceptional topic where I describe for example the architecture of  a software containing several assemblies, I could then use reference-links like A:AssemblyName to link to the assemblies, which would be quite helpful - better maintainable than handling GUIDs of conceptional topics.
Thanks, Stefan

**Comment by EWSoftware** [comment]
One or more conceptual topics would cover most of those points and requires much less work.  Namespaces are a natural grouping option, assemblies not so much.
