### ISSUE TITLE
Support for <para>

### ISSUE THREAD

**Issue by SoftCircuits** [EWSoftware/SHFB#171]
A `<summary>` or `<remarks>` element that contains multiple paragraphs appears to always be rendering as a single paragraph.

At first, I was hoping the software would recognize a double new line as a new paragraph. When I saw it did not, I started playing with the `<para>` tags. But those also seem to be ignored.

I'm new to Sandcastle. Is this a known issue?

**Comment by EWSoftware** [comment]
Para elements appear to be working fine.  If you view the source for the rendered page, you should see the `<p>` element wrapping the text.

**Comment by sharwell** [comment]
@SoftCircuits I haven't noticed any problems with `<para>` tags in output, but that doesn't mean there aren't any. Can you include the following to help track down the issue?

1. An example XML comment containing `<para>` tags which is rendering as a single paragraph instead of multiple.
2. The name of the presentation style you are using.

Thanks! :smile:

**Comment by SoftCircuits** [comment]
Sorry, now it appears to be working. Perhaps I hit an error or something that I didn't see and it was preventing the new source from being processed. That would probably mean the output file would be deleted so I'm not sure.

My apologies.
