### ISSUE TITLE
SHFB doesn't find documentation sources with special msbuild flag

### ISSUE THREAD

**Issue by reitzmichnicht** [EWSoftware/SHFB#18]
On TFS we are using an extra flag for msbuild to separate build output:
msbuild SMA.Runtime.Documentation.sln /p:GenerateProjectSpecificOutputFolder=true

In this case SHFB doesn't find the corresponding dll file to the referenced csproj documentation source.

SHFB: Error BE0040: Project assembly does not exist: D:\xxx\.\SMA.Runtime.Documentation\SMA.Runtime.Logging.dll
   bei SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
   bei SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by EWSoftware** [comment]
Is the SHFB project part of the same solution?  If so, it should be picking up that option too.  If you are building the SHFB project separately, you'll need to pass that option to the SHFB project as well so that it knows to look elsewhere for the output.  Also, this option wasn't supported in versions prior to v1.9.8.0 and there was a fix for it in v2014.1.26.0 so if not using the latest release, you may need to upgrade.

**Comment by reitzmichnicht** [comment]
Hi Eric 
I'm on the latest shfb version. I build the solution with msbuild v12 which contains the shfb project and the documentation source projects

**Comment by EWSoftware** [comment]
I don't have TFS but was able to do something similar by passing that option along with OutDir on the command line using the test case project.  It doesn't appear to be picking up the OutDir value for some reason and is using the SHFB project folder instead.  I'll have to look into it and see what's going on.

**Comment by guillaume-fr** [comment]
Hi Eric,
Do you plan a release including this fix in the near future ?

**Comment by EWSoftware** [comment]
I hadn't planned on a release yet but I can probably publish one this weekend.

**Comment by guillaume-fr** [comment]
That'd be great !
