### ISSUE TITLE
How do I link to the root namespace container in HTML docs?

### ISSUE THREAD

**Issue by andreashuber-lawo** [EWSoftware/SHFB#186]
I'm using SHFB to generate HTML docs (I don't currently need any other output format). In the project properties, I have **Include root namespace container** checked and use the **Insert after this topic** option in the content layout to have the API content inserted at a specific point in the tree.

My question is: How do I link to the root namespace container with a <link> tag?

I noticed that there's the **Use as MS Help Viewer root container** option, but that does not seem to work with HTML output.

**Comment by EWSoftware** [comment]
To link to the root namespace container page, you need to know either its ID or its internal filename.  It's ID is generated at build time and will be `R:Project_NameOfHelpProject` where `NameOfHelpProject` is the SHFB project name with any spaces replaced by underscores.  The internal filename is an MD5 hash of that.  The easiest way to find both is to view the source for the page in the help file.  Look for the `Microsoft.Help.ID` and `file` metadata elements in the `head` section.

Once you've got those, you can do one of the following:

From XML comments, you can use a `see` element with the ID:

```XML
/// <remarks>See the <see cref="R:Project_TestCaseProject">root namespace container page</see></remarks>
```
You will need to supply the inner text as none of the presentation styles currently know how to resolve the root namespace ID to get a proper title.  I'll see if I can fix that.

From a conceptual topic, you can use an `external` link element with the internal filename:

```XML
<para>See <externalLink>
    <linkText>Root Namespace Container Page</linkText>
    <linkAlternateText>root namespace container</linkAlternateText>
    <linkUri>html/2d888795-6dea-c731-62ed-ed08d66bd539.htm</linkUri>
    <linkTarget>_self</linkTarget>
  </externalLink>
</para>
```
Just replace the GUID in the `linkUri` element with the filename for your page.  The `codeEntityReference` element would also work using the ID but, again, it doesn't know how to resolve the ID to get a proper title.

**Comment by andreashuber-lawo** [comment]
Thank you, the <externalLink> works. However, it seems the "html/" part in the <linkUri> tag must not be there?

BTW, I don't think it is necessary to resolve the root namespace ID into its title. It would be nice for sure, but such links are so rare that I don't think it's worth the effort.

**Comment by EWSoftware** [comment]
The "html/" part may not be needed for website output.  It is for Help 1 though at least in my test.  I don't think resolving it would be too hard since its just extending the existing templates and would guarantee a format that works across all help types so I'll probably take a look at it when I get some time.

**Comment by phikret** [comment]
Hello, I picked Presentation style vs2013 and now I have one problem. Since we added SiteMap to the project where we have additional help pages (html), we are not able to see this node in the left menu upon opening help. It is visible only after clicking arrow of the root node (Name of the project). Even when I manage to show this option in meny, there is another problem. Since Javascript method trims /html (5 chars) from URL, I am getting all anchors under SiteMap pointing to non-existing pages. For example, instead of <a href="documentation.html">, I am getting <a href="entation.html">). This of course does not work. I edited javascript file but it is not acceptable solution. Once I get right links, it happens whern I click on the link that particular help page (.html file) is opened over the whole document in browser, not only in right part of window. Can you pleae check this issue. If needed I can send screenshots.

**Comment by EWSoftware** [comment]
@phikret: There is no support for HTML content in the VS2013 presentation style.  You'll need to convert it to conceptual content and a content layout file.  Your only other alternative is the older VS2010 style.
