### ISSUE TITLE
Add Existing Topic File takes 197 seconds to complete

### ISSUE THREAD

**Issue by dougclutter** [EWSoftware/SHFB#198]
This has been an issue in the following SHFB releases:
* 2014-05-31
* 2015-07-25
* 2015-10-10

I have experienced this problem in both:
* Visual Studio 2013 Ultimate
* Visual Studio 2015 Enterprise

When editing a .content file, right-click on an existing topic and choose the Add Sibling/Child Topic -> Add Existing Topic File option.  Pick the .aml file to add.  At this point, Visual Studio changes the mouse icon to the wait icon and Visual Studio appears to lock up.  Clicking on the Visual Studio window causes it to go completely grey because the application is non-responsive.  After 197 seconds, the operation completes successfully.

Thanks for creating SHFB.  It is an awesome tool!

**Comment by EWSoftware** [comment]
Even in my largest project with 300 topics or so, it adds new or existing files in a second or two with or without source control.  Is your project under source control?  Is it going to a remote server?  If under source control, what happens if you go offline or try it in a project not under source control?

**Comment by dougclutter** [comment]
I only have 42 topics in this project so that's not the problem.

We use TFS for version control.  We just upgraded from 2013 to 2015 and I can confirm it was an issue under both versions.  The TFS server is on our network; it is not at my site but it's not in Bangladesh either.

Tried the following:
* Created a new project and adding a topic is nearly instant.  Good.
* Created an empty solution and copied only my help project to that solution, and I get the same crazy behavior.  No connection to TFS.

Also, I'm getting this behavior with a completely different help project.

**Comment by EWSoftware** [comment]
Sorry, I don't know what else to tell you and it's not something I can reproduce.  You can try copying items across a few at a time from your problem project and adding them to the new project to see at what point things stop working as expected.  That may help determine if it's one or more files in particular that cause the problem.

**Comment by dougclutter** [comment]
I think I figured it out.

When I generate the web version of the help, I drop it in the Help folder at the same level as the shfbproj file.  I think this is the default.

My Help folder contains 4,106 file in 8 folders with a total size of about 60.3MB.  When that Help folder exists in the project, I get the bad behavior.  If I move that folder somewhere else, it works fine.

Can you reproduce the problem now?

**Comment by EWSoftware** [comment]
That would make sense.  Web projects include every file as part of the project when they exist as I recall.  When you add a new help topic, it does scan the project to see if it already exists including all of the help output which would slow it down with so many files.  Since the help output probably isn't going to be part of the website, it's best to place it outside of the website project folder.

**Comment by dougclutter** [comment]
I can think of no rational reason why adding an existing topic to a content file would require scanning the entire folder contents.  That just doesn't make any sense.

It also doesn't make sense to "place it outside of the ... project folder."  When I compile a program, the resulting files are saved to the bin folder *within* the project folder; *almost everything in Visual Studio works this way*.  Why should SHFB work any differently?

I really think we need to call this a bug.

**Comment by EWSoftware** [comment]
I misunderstood what you were saying.  If you're saying you're including the .\Help output folder in the SHFB project as part of the stuff you see in Solution Explorer that actually is part of the .shfbproj file, that is the problem and is not necessary.

Adding a file to the content layout file isn't the issue.  It's adding the resulting topic file to the project itself that is the issue.  It's not scanning the folder but the project content.  The project needs to be checked to ensure that the file is not already part of the project.  If it is, then it won't overwrite what is there and it doesn't need to add it to the project again.  You can't avoid that.  With thousands of unnecessary help output files in the project, it slows that process down.

**Comment by dougclutter** [comment]
I can reproduce the problem every time with this procedure:
* Create an empty Sandcastle project
* Add a topic by right-clicking on the project, choosing New Item..., choosing Conceptual Topic.
* Open the ContentLayout.content file, right-click on the root topic, choose Add Child Topic, choose Add Existing File.  Select the file created in previous step.  
* This works fine and the file is added almost instantly.
* The Sandcastle project folder contains an empty Help folder.  Drop a previously generated Help Web site with a lot of files into this folder.  My folder has 4,108 files in 8 folders using 60.3MB.
* Repeat the process of adding a topic file to the ContentLayout.content file exactly as described above.
* This will lock up Visual Studio for multiple minutes.

Are you able to reproduce this problem?

**Comment by EWSoftware** [comment]
I am able to reproduce it now.  I didn't have the web content built when I tested adding an existing file so that was the part I was missing.  The underlying problem is that once the file is added, it needs to refresh the Solution Explorer to show the new file.  Currently, this is done by toggling the Show All Files option on and off which is the simplest way since it handles the various issues related to whether the file is in the project, isn't in the project, or is shown as a place holder when Show All Files is enabled.  The way Show All Files is implemented is not optimal when there are thousands of files to handle such as when web output exists which causes the slow down.

There are two workarounds:

1. Rather than adding the file to the solution and then the content layout file, just add the file to the content layout file.  If it's not already in the project, it will add it automatically.  In such cases, the project add is handled differently and it doesn't need do a refresh on the Solution Explorer window and it's a fast operation every time.
2. Clean the build output.  That will resolve the issue since it won't have to process it when it doesn't exist.

Given that there are easy workarounds, making the Show All Files code perform better is a low priority.  It would involve a number of changes to the underlying project system (MPF) which I'm not planning on enhancing any further as there is a new project system in VS2013 and later which I plan on using once I get around to looking into it.

**Comment by dougclutter** [comment]
That makes sense.  I agree that this isn't a big deal...especially since I can easily work around it.  Hopefully our conversation will help others work around it too.

Once again, thanks for all you've done with SHFB.
