### ISSUE TITLE
Broken links for additional html documentation

### ISSUE THREAD

**Issue by mplogix** [EWSoftware/SHFB#20]
If an html page is added to the project and included in the TOC, the link to the page in TOC has a truncated page name, instead of the original name, and the page does not make it to the html directory.  The result is that the TOC link to the page fails.

For example for an html page named MyPageExample.html, the TOC link may looks like something like this: ../html/xample.html. But neither MyPageExample.html, nor xample.html can be found in the html directory.
Thanks.

**Comment by EWSoftware** [comment]
What help format?

**Comment by mplogix** [comment]
VS2013

**Comment by EWSoftware** [comment]
The VS 2013 presentation style uses the lightweight TOC which inserts TOC elements into each topic.  HTML files aren't supported since they more likely than not will not have the structure required to receive the added elements.

The HTML additional content model has been deprecated for quite some time.  You can use the VS2010 or VS2005 presentation styles which use the older frame-based web layout or you can switch to using a content layout file and MAML topics which will get transformed based on the presentation style and will contain the proper structure needed to receive the added TOC elements in the VS 2013 presentation style.
