### ISSUE TITLE
Additional Content from .htm files

### ISSUE THREAD

**Issue by KarloX2** [EWSoftware/SHFB#206]
Hi!

I recently updates by SHFB installation from some V1.9.x version to the latest V2015.10.10.0. Works file like before, but I have trouble with an existing .shfbproj file that lists a number of .htm files as a source for additional content. The older version took all these files and included it nicely in the compiled .chm file, each as a separate topic and each represented in the table of content below the regular content. The new version just seems to ignore the .htm files. I can't find any output.

I read a little about MAML which is new to me. I hope I won't need to change all the existing .htm files into new MAML style content ???

Thanks!

**Comment by EWSoftware** [comment]
Please review all of the release notes from the last version you used to the latest. A great many changes have been made including removal of a large number of deprecated features.  This step was necessary to move forward with support for new and future features.  Raw HTML support was removed mainly because it isn't supported in the newer presentation styles and MS Help Viewer.  You will need to use MAML for additional content going forward as it is the only means supported by all components of the build process.

The HTML to MAML conversion tool is still included to help with the migration from HTML to MAML.
