### ISSUE TITLE
How do I add a reference to an parameter to a method when I am writing the method's summary?

### ISSUE THREAD

**Issue by dlipkie** [EWSoftware/SHFB#207]
Do I use `<cref="xxx" />`?

If so what is the correct value for xxx, e.g.

public void MyMethod(string MyParam)

**Comment by EWSoftware** [comment]
There isn't a way to link to parameter help from an external source or from within the topic.  You can use the `paramref` element to indicate that a word is a parameter reference.

See the [XML Comments Guide](http://ewsoftware.github.io/XMLCommentsGuide) as it covers all of the available elements and their usage.

Also, please use code markdown (backticks) to surround the angle bracketed text in your messages.  They don't get rendered otherwise and I have to edit the message to see what you wrote.  For multiline code, use [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).  Thanks.

**Comment by dlipkie** [comment]
Thanks.
