### ISSUE TITLE
Error in German Version

### ISSUE THREAD

**Issue by UlliBien** [EWSoftware/SHFB#21]
Hi,

there is no problem to build an english version of a help-file. But when I switch to german, I get this error:
"CopyFromIndexComponent: The indexed document 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\de\System.Data.Services.Client.xml' is not a valid XML document. The error message is: Ungültiges Zeichen in der angegebenen Codierung. Zeile 11, Position 10. [C:\Users\Ulli\Documents\Visual Studio 2012\Projects\USB Hid\SimpleGenericHid\Help\Working\BuildReferenceTopics.proj]"

The translation of the german part of the error message "Ungültiges Zeichen in der angegebenen Codierung. Zeile 11, Position 10." is "Invalid character in the given encoding. Line 11, Position 10"

At the specified position is an german umlaut u "ü".
Second: I wonder why version \v.4.0\ is used. The projekt whas build with .NET framework 4.5

Im using a fresh installed version aof Sandcastle 2015.1.12.0

**Comment by EWSoftware** [comment]
It's a known issue with the German language framework XML comments files.  You need to manually open them and change the offending characters to numeric entities such as &#252; since the .NET XML parser doesn't handle them.  If you're using the assemblies rather than the project as the documentation sources, check the SHFB Framework Version property and set it to .NET 4.5.
