### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by hugener** [EWSoftware/SHFB#215]
I have a fairly simple project set up to build documentation for a single assembly. However, starting the build always results in the following error message:
SHFB: Error BE0065: BUILD FAILED: Cannot cast the underlying exported value of type 'Microsoft.Ddue.Tools.BuildComponent.AdditionalHeaderResourcesComponent+Factory (ContractName="Sandcastle.Core.BuildAssembler.BuildComponent.BuildComponentFactory")' to type 'Sandcastle.Core.BuildAssembler.BuildComponent.BuildComponentFactory'.
   at System.ComponentModel.Composition.ExportServices.CastExportedValue[T](ICompositionElement element, Object exportedValue)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

Is this a bug?
I'm using version: 2015.7.25.0 and have been able to reproduce it on multiple computers.

**Comment by EWSoftware** [comment]
Perhaps its finding an older version or you've got the project's Component Path property set to a location containing an older version.  Also check the SHFBROOT system environment variable to make sure it's pointing to the right location and check the project with a  text editor to make sure SHFBROOT isn't defined within the project as a property which may point to an incorrect version.

**Comment by hugener** [comment]
Hi Eric,

 

Thanks a lot, that was it the Nuget package for SHFB was updated to 2015.10.10 with the installation being 2015.7.25.

 

How come is it available as a nugget package and are there plans to make the UI independent from the nuget package, so simply updating the package will suffice for future updates?

 

-Kim

**Comment by EWSoftware** [comment]
The main purpose of the NuGet packages is to deploy the Sandcastle Help File Builder tools inside of a project to build help files without installing the tools manually and without defining the SHFBROOT environment variable (build servers for example).

For development work, you do need the version you're trying to build against since the UI and Visual Studio package directly reference the build engine and supporting assemblies.  There's no way around that.  That's why if you add the SHFBROOT property to the project, it should be made conditional.  If the component path is set such that it's finding the other tools under Visual Studio, it could be made conditional as well which should resolve the problem.
