### ISSUE TITLE
Can I build CHM without index file?

### ISSUE THREAD

**Issue by stefanov-stefan** [EWSoftware/SHFB#217]
Is it possible to build Chm with Sandcastle without the index tab. 

To do that with the HHC compiler, one has to edit the .hhp file prior running the build as follows:
- set the index file to nothing "Index file="
- set auto index to no - "Auto Index=No"
- in the MsdnHelp command, delete the .hhk file setting, leaving empty string

Also, is there is a way to limit the number of indexes added to the index file (hhk). Looking at the source code, there is not such way, but I might be missing something.

**Comment by EWSoftware** [comment]
SHFB doesn't provide a way to exclude the Help 1 index but you could create a plug-in that modified the project file used to build the CHM file in order to remove it.  Likewise, the plug-in could limit the index entries if there's a way to do it.

**Comment by stefanov-stefan** [comment]
I've started with the plug-in (I am using version 1.9.5) and in the help it says to copy the plugin to ""%ProgramData%\EWSoftware\Sandcastle Help File
Builder\Components and Plug-Ins\$(TargetName).plugins", however, such folders do not exist on my machine (Windows10). Should I create them or I have corrupted instalation?

**Comment by EWSoftware** [comment]
That's going back quite a way and things have changed a lot since then.  The best I can suggest is look at the topic in the help file on creating plug-ins.  It should give you the info you need.  If it's an option, I suggest updating to the latest release of SHFB.  All components are now implemented using MEF and the Component Path property makes them easier to discover and keep them project-specific which helps [during development](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm).  The Visual Studio package also contains a project template for creating plug-ins.

**Comment by stefanov-stefan** [comment]
Thanks. I did follow the help file sticky and triple checked, but it doesn't see my plugin. Can you tell me where I can get 1.9.5 source code, so I can see how it looks them up? I couldn't find it either



Sent from my Samsung device


-------- Original message --------

**Comment by EWSoftware** [comment]
Download the source from this link: https://github.com/EWSoftware/SHFB/tree/3e569c84583cac63ea42b3359f47b576b4a2a1a6
