### ISSUE TITLE
Documented entities only

### ISSUE THREAD

**Issue by Sonizci** [EWSoftware/SHFB#223]
Hi;

Maybe you know already but Doxygen has an option under Wizard->Mode->"Documented entities only". I think this is very helpfull with big projects. It generates help files/sites; only the usefull information.

We are dealing with a very huge project (50+ class library). Because of this option we are using Doxygen. If we build our documentation with SHFB; it generates 100+ mb help file. Most of them has no comment. When other developers see uncommented a lot of pages/index, they intent to not to look again.

I like SHFB a lot and want to push it to my colleagues. Just a suggestion.

**Comment by EWSoftware** [comment]
I'll look into it.  In the meantime, you can use the [API filter](http://ewsoftware.github.io/SHFB/html/7df16a60-f718-4b8f-bfa2-88c42906070c.htm) to exclude namespaces, types, and members that you do not want to include.

**Comment by Sonizci** [comment]
Thanks

**Comment by jbparker** [comment]
Would love to see this implemented as well - we are running into the same problem, and unfortunately, most of our code isn't documented.  We're using API Filters to work around this, but it would be preferable to just add XML comments to the source project and they are automatically built on the add instead of having to add an API Filter to allow the class / namespace to show.

**Comment by EWSoftware** [comment]
@Sonizci  and @jbparker:  Attached is a prototype Documented Entites Only plug-in.  Please try it out if you have some time and provide feedback about how well it works for you.  Once any issues are ironed out, I can add it to the next release.

Extract it to a folder and use the Component Path property on the Paths property page in the project to point to the folder you extracted it to.  You can then select it and add it to the project on the Plug-Ins property page.  It has no configurable information.

This plug-in is used to automatically generate an API filter based on the XML comments member IDs to limit the help file content to only the documented entities.

This plug-in is unique in that it runs both before and after the `GenerateReflectionInfo` step.  This is necessary as we must remove any project-based API filter and generate a full set of API information in order to compare it to the XML comments member IDs.  Once we have done that, we can generate an API filter and apply it by building the reflection information again.

Note that we are still constrained by the rules of the API filter.  Specifically, if you exclude one member of an overloaded method set, all of them will be excluded.  There is no getting around that rule.

In addition, since inherited documentation is generated after reflection data is generated, undocumented members of explicitly implemented interfaces will not be included.  If you want them included, you must explicitly add an `inheritdoc` tag on those members.

To explicitly exclude a documented member, add the `exclude` XML comment tag to its comments.  If placed on a type, it will exclude the entire type regardless of whether or not it has documented members.  If placed on a `NamespaceDoc` class, it will exclude all types within the namespace regardless of whether or not they are documented.  Note that namespace exclusions defined in the project namespace summaries will have no effect.  You must either add a `NamespaceDoc` class for the excluded namespace or exclude all of its types.

[DocumentedEntitiesOnlyPlugIn.zip](https://github.com/EWSoftware/SHFB/files/355728/DocumentedEntitiesOnlyPlugIn.zip)

**Comment by jbparker** [comment]
Awesome, thanks @EWSoftware!  I will try to give this a try next week.  Thanks so much for this!

**Comment by EWSoftware** [comment]
@jbparker:  Where you able to try the component out?

**Comment by jbparker** [comment]
@EWSoftware 

So sorry for the long time looking at this - I tried it out and it seems that the plugin included / removed the filter under some scenarios, but a few don't seem to be behaving correctly.

Looks like it could be related to classes that implement interfaces / inherit, see the below example:

<img width="903" alt="results" src="https://cloud.githubusercontent.com/assets/5770169/17872061/5c52a5b0-688c-11e6-9966-52f963c9e6ab.png">

Related code:

```
Public MustInherit Class BaseHandler
    Implements IHttpHandler

    Protected Context As HttpContext

    Protected Overridable ReadOnly Property Application As HttpApplicationState
        Get
            Return Context.Application
        End Get
    End Property

    Protected Overridable ReadOnly Property Request As HttpRequest
        Get
            Return Context.Request
        End Get
    End Property

    Protected Overridable ReadOnly Property Response As HttpResponse
        Get
            Return Context.Response
        End Get
    End Property

    Protected Overridable ReadOnly Property Server As HttpServerUtility
        Get
            Return Context.Server
        End Get
    End Property

    Protected Overridable ReadOnly Property Authentication As Components.Shared.IAuthentication = Nothing
    Protected Overridable ReadOnly Property IsReusable As Boolean = False Implements IHttpHandler.IsReusable

    Protected MustOverride Sub ProcessRequest()

    Private Sub ProcessRequest(context As HttpContext) Implements IHttpHandler.ProcessRequest
        Me.Context = context

        Try
            ProcessRequest()
        Catch ex As Exception
            Components.Shared.ErrorLog.Create(ex, Authentication?.ID)
        End Try
    End Sub
End Class
```
Let me know if you have any thoughts, and thank you very much for this!

**Comment by EWSoftware** [comment]
As I recall that's normal.  Implicit implementations don't auto-inherit documentation, only explicit implementations do.  Although, as noted above, with this plug-in, explicit ones won't either due to the order of generation (reflection data first, then inherited documentation).  So, without an explicit `inheritdoc` tag, the members will be excluded as they have no documentation.

**Comment by jbparker** [comment]
Hey @EWSoftware 

In this case, I don't have any comments in the file `BaseHandler`, but it **_is_** showing up in documentation (not expected or desired).

I would expect that this class wouldn't show up in the export because it is not commented.

**Comment by EWSoftware** [comment]
The auto-doc constructors/dispose method settings in the Missing Tags category are causing the type to be included.  I just need to update the filter generation so that if the only methods documented are the auto-doc constructors/dispose methods, it excludes the type.

**Comment by EWSoftware** [comment]
Try this update.  It should work as expected now.

[DocumentedEntitiesOnlyPlugIn2.zip](https://github.com/EWSoftware/SHFB/files/443109/DocumentedEntitiesOnlyPlugIn2.zip)

**Comment by jbparker** [comment]
Hey @EWSoftware 

Looks perfect as far as I can tell. Thanks for this!

**Comment by EWSoftware** [comment]
Thanks for the update.  I'll get it into the next release due out in a few weeks.

**Comment by jbparker** [comment]
Great!

**Comment by EWSoftware** [comment]
Added and checked in with commit 86d19756a5edc25305947e152b1b6cea69a48a8a
