### ISSUE TITLE
ShowMissingComponent warning on lists and nullable arguments in c++ CLI

### ISSUE THREAD

**Issue by jazpearson** [EWSoftware/SHFB#225]
I am getting a  <b> warning : BuildAssembler : warning : ShowMissingComponent: </b> whenever I have a Nullable type, or when there is some sort of list in the method. I am running the latest version 
2015.10.10.0 with Visual Studio 2015. This worked absolutely fine in Visual Studio 2012. The code is written in managed C++.

Example 1:

      <summary>
      Sets the Area.
      </summary>
      <param name="area">The value of the area to set.</param>
      <returns>A Result with details on the success or failure of the operation.</returns>
      Result^ SetArea(Nullable<double> area);

The XML file generates the following (notice the `1): 

      <member name="M:Task.SetArea(System.Nullable`1{System.Double})">
        <summary>
           Sets the Area.
        </summary>
        <param name="area">The value of the area to set.</param>
        <returns>A Result with details on the success or failure of the operation.</returns>
      </member>

Example 2:

        <summary>
        Updates the list of items 
        </summary>
        <param name="items">The list of items to update.</param>
        static void UpdateItems(System::Collections::Generic::List<Item^>^ items);

The XML file generates the following (notice the `1 after Generic.List:

    <member name="M:Task.UpdateItems(System.Collections.Generic.List`1{Item})">
      <summary>
     Updates the list of items 
     </summary>
     <param name="items">The list of items to update.</param>
    </member>

Any help on the matter is much appreciated.

**Comment by EWSoftware** [comment]
The C++ compiler has known issues with generating XML comments files.  You can try using the [Member ID Fixups plug-in](http://ewsoftware.github.io/SHFB/html/17d977a6-e3dc-4ef4-9bbf-718ef4823854.htm).  There's an option in it to fix the common issues.  You may be able to use the other settings to fix up the new issues.  In this case, it looks like part of the problem is that its writing out actual types rather than the general T placeholder so you probably needed a replacement expression that looks for anything in braces and replaces it with "{T}".

**Comment by jazpearson** [comment]
Magic. Worked a treat. Thanks.
