### ISSUE TITLE
inheritdoc components

### ISSUE THREAD

**Issue by rowanmiller** [EWSoftware/SHFB#23]
Hey,

Is there any feasible way to use the logic that processes `<inheritdoc />` to post-process an IntelliSense file that is produced by a build process? I was digging thru the code base but couldn't see where this logic lives.

Basically I want to be able to use `<inheritdoc />` when commenting the API but then have build produce an xml file that VS can consume for IntelliSense... was hoping to re-use what you've already implemented.

~Rowan

**Comment by EWSoftware** [comment]
Add the [IntelliSense Build Component](http://ewsoftware.github.io/SHFB/html/5d546511-6aec-455a-ba09-9daffb124c6d.htm) to your project in the Components category property page.  It will generate an IntellSense XML comments file during the build containing only the elements necessary for IntelliSense and will include any inherited documentation.

**Comment by rowanmiller** [comment]
I saw that one... sorry I should have mentioned that we aren't using a csproj/MSBuild based system... so I was hoping there may be some factored out processing we could use :smile:

**Comment by EWSoftware** [comment]
The GenerateInheritedDocs tool is the one that creates the inherited documentation file for the help file build.  If your doing something unrelated to building a help file, you could probably pull the code out of that and create something similar that merges the comments back into the source XML comments file.  However, it still depends on the MRefBuilder reflection data output so that it can determine base types and members for inheritance so you'd still have to run that first.

If there's the possibility that you could use a SHFB project, there's the [IntelliSense Only plug-in](http://ewsoftware.github.io/SHFB/html/1fcdf9d3-06fb-4a7b-a584-f55b6ea5baae.htm) found on the Plug-Ins category property page (separate from the component noted above) that basically does the above and skips all the help file steps.  That would get the job done without having to manually try to reproduce the same steps.  Documentation sources can be assemblies and XML comments files rather than projects if necessary.

**Comment by rowanmiller** [comment]
Thanks, that gives me the info I need. I'll see what I can do with it.
