### ISSUE TITLE
VS2015: cannot install snipets

### ISSUE THREAD

**Issue by win32nipuh** [EWSoftware/SHFB#235]
There is VS2010, VS2013, VS2015 on the same machine Windows 10.
When I install SFHB I can mark to install snippets for VS2013 but cannot mark for VS2015, it is disabled: it writes cannot find folder for cache etc.

**Comment by EWSoftware** [comment]
Snippets are stored in the My Documents folder under the *Visual Studio 2015\Code Snippets\XML\My Xml Snippets* folder.  You may need to run Visual Studio so that it creates the default snippets folder if you haven't ran it already.  Creating the folder manually should work too if it still can't find it after that.

**Comment by win32nipuh** [comment]
Thanks, you are right
