### ISSUE TITLE
Failure to Target Assembly Output Directory Using MSBuild

### ISSUE THREAD

**Issue by daviddunson** [EWSoftware/SHFB#238]
I have a C# assembly and am redirecting the output to the solution bin directory as follows:

{solution}\Source\MyProject\MyProject.csproj
`<OutputPath>$(SolutionDir)bin\$(Configuration)\</OutputPath>`

I'm adding a documentation source to Sandcastle as follows:

{solution}\Documentation\MyProject.Documentation\MyProject.Documentation.shfbproj
`<DocumentationSource sourceFile="..\..\Source\MyProject\MyProject.csproj" xmlns="" />`

When building inside Visual Studio, SHFB picks up the assembly in the {solution}\bin\{configuration} folder successfully; however, when running on the build server (VSTS Git), I get the following error:

`##[error]SHFB(0,0): Error BE0040: Project assembly does not exist: C:\a\1\s\MyProject\Source\MyProject\bin\Release\MyProject.dll
SHFB : error BE0040: Project assembly does not exist: C:\a\1\s\MyProject\Source\MyProject\bin\Release\MyProject.dll [C:\a\1\s\MyProject\Documentation\MyProject.Documentation\MyProject.Documentation.shfbproj]`

I have another solution configured the exact same way and is building successfully on an internal TFS 2013 server using TFVC. After comparing the files and finding no significant difference, I decided to open a Visual Studio Command prompt and run MSBuild.

When using MSBuild, I get the same error on both solutions. It appears that when using MSBuild, the output directory is being ignored and the path to the DLL is constructed manually resulting in a file not found.

Both solutions have a local copy of SHFB v2015.10.10.0. The solution on TFS 2013 has the binaries checked into source control, the solution on VSTS is using the NuGet package restore.

Just to reconfirm, when building inside Visual Studio, they both build successfully.

Update: I am also getting this warning on the VSTS build server. I'm not sure if it's related.

`SHFB(0,0): Warning BHT0001: Unable to get executing project: Unable to obtain matching project from the global collection. The specified project will be loaded but command line property overrides will be ignored.`

I've restored my assemblies to build in the default folders and I get a successful build; however, the BHT0001 warning still exists.

**Comment by EWSoftware** [comment]
Can you create a small example and attach it here or e-mail it to me?

**Comment by daviddunson** [comment]
A sample project has been sent to your e-mail.

**Comment by EWSoftware** [comment]
This appears to be related to a difference in the way Visual Studio and MSBuild load the projects.  Within Visual Studio, when the documentation project is built, because the project is part of the same solution loaded within Visual Studio, the SHFB build engine is able to find a copy of the project in the global projects collection.  Since that copy has a value in SolutionDir that resolves to the right location, it's able to find the output.

When building under MSBuild, it doesn't load things the same way and the project is not found in the global projects collection so the SHFB build engine has to load it for itself.  Since that copy doesn't have a solution, the SolutionDir property is undefined and it defaults to looking in the usual location for the output.

What you need to do is use the solution as the documentation source rather than the project.  In that case, the SHFB build engine knows that the project it loads is part of the given solution that it searched for projects and will manually set the solution related properties accordingly and it will find the output in the expected location.

Regarding the BH0001 error, it's probably trying to use MSBuild 14.0  There's a problem in the current release related to that which has been fixed for the next release.

**Comment by daviddunson** [comment]
That workaround seems to work. It does add some complexities to my environment since I have other projects that are consuming the output of the SHFB project; however, I can workaround that too. Just FYI, you might want to take a look at the source for the WiX Toolset, they are about to determine the correct location of m project output using [var.ProjectName.TargetPath](http://wixtoolset.org/documentation/manual/v3/votive/votive_project_references.html). I realize your environment is different, but it might be worth a look.

Thank you for your reply.
