### ISSUE TITLE
Customising API output with Lightweight VS2013 style

### ISSUE THREAD

**Issue by deejaygraham** [EWSoftware/SHFB#26]
What is the best way to customise the layout and style of the VS2013 API output? I have a project which is a combination of additional conceptual content (in old fashioned html), customised to include extra css, js and markup. I would like the styling of this content to be extended to the API documentation. Currently the API documentation has the default black bar at the top for the title and search bar. Obviously I could post-process the generated html to force the content but I'm looking for something that's a bit cleaner and more maintainable.
Thanks.

**Comment by EWSoftware** [comment]
You can clone the presentation style and modify it to suit your needs.  By creating a separate presentation style cloned from the original you don't have to keep it in synch or remember what you changed with each new release of SHFB.  There's a Visual Studio project template that can be used to create a presentation style and you can copy the existing content to it and modify it as needed.

Bear in mind that HTML pages will not work with the presentation style unless you modify them to contain the necessary elements to support the added lightweight TOC elements.  The old HTML model has been deprecated for a long time because it doesn't work with the newer presentation styles as well and will not work in MS Help Viewer Output.  You're better off converting the older additional content HTML files to MAML since they will then inherit the presentation style when transformed regardless of the output format and require no changes if you later change presentation styles.

**Comment by deejaygraham** [comment]
Thanks Eric. I think cloning the style might be the best thing. It's my goal to convert to MAML but I have > 800 topics to convert and I need to get the markup into a better format so the conversion tool won't choke on it.
