### ISSUE TITLE
Printing a topic fails with scripting errors

### ISSUE THREAD

**Issue by MikeTheFid** [EWSoftware/SHFB#266]
Hi,

I have used SHFB to successfully create a Compiled HTML Help file for my product.

When I try to print a topic and all its subtopics, I get the following script error window:

------------------------------
An error has occurred in the script on this page.

Line: 3929   (for example)
Char: 144    (for example)

Error: The value of the property 'AddLanguageSpecificTextSet' is null or undefined, not a function object

Code: 0
URL:  file:///c:/Users/myUserID/AppData/Local/Temp/~hh7139.htm

Do you want to continue running scripts on this page?

                  Yes     No     <== buttons
------------------------------

This error occurs for page after page after page...

The problem boils down to the fact that branding.js, which defines the function 'AddLanguageSpecificTextSet' is not available at the time the html page is being processed while printing.

What can I do to ensure branding.js is available at print time?

Thanks,
Mike

**Comment by EWSoftware** [comment]
It's a known issue with Help 1.  It's caused by script in the content.  As I understand it, the Help 1 Viewer concatenates all topics into one huge topic and tries to print it all in one go.  Since there's script in each page that adjusts the language specific text, it doesn't work and you get the warnings.  I'm not aware of anyway to work around the issue.

**Comment by MikeTheFid** [comment]
Acknowledged. Thank you.
