### ISSUE TITLE
Ability to change text for 'Namespaces' node of the TOC

### ISSUE THREAD

**Issue by dkemlage** [EWSoftware/SHFB#27]
Eric,

I have had some people suggest that I change the 'Namespaces' text in the TOC pages that are generated by the Visual Studio SandCastle project.

![image](https://cloud.githubusercontent.com/assets/5495810/6363410/929973f2-bc4d-11e4-956a-0573a64d8f76.png)

I did not see any option in the SandCastle project properties to modify the 'Namespace' TOC text.

I have been able to identify the HTML files that have the 'Namespace' text in the TOC. Specifically: the
the 'default topic page', pages that begin with 'N_xxxxxx.htm, and the 'R_Project_xxxxxx.htm' page. I could write some custom routines to find the 'Namespace' text and replace it with their suggestions but this seems like a lot of work for something that could just be a setting.

Is there some modification in a file of the "C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder" directory structure that could be used to change the 'Namespace' TOC text?

Thanks,
-don

**Comment by EWSoftware** [comment]
In your SHFB project, open the project properties and go to the Help File category.  There is a **Title** textbox field immediately following the **Include root namespace container** checkbox that enables this option.  Enter your alternate title there and it will be used instead of the default "Namespaces" title.

See the subtopics of the [Project Properties Window](http://ewsoftware.github.io/SHFB/html/e32086c6-de17-4e54-a746-1ac80bf0c45a.htm) help topic for a description of each of the available project properties.

**Comment by dkemlage** [comment]
Thanks Eric for the quick response. Your solution worked perfectly.
-don
