### ISSUE TITLE
Split large .mshc file

### ISSUE THREAD

**Issue by icom85** [EWSoftware/SHFB#279]
Hello, 

We are building Help 3 API Reference to be viewed in the Visual Studio Help Viewer. The generated .mshc file is very large, approximately 280 Mb and the count of the Html files is more than 100k. 

It appears that the help viewer is having a limitation considering the file count in a single .mshc file. Only if we split the large .mshc file to a number of smaller ones we are able to view the content. Currently, the split process is being done outside of Sandcastle.  Is there a way to specify in the Sandcastle project to generate a number of .mshc files or split an existing large one?

Thank you in advance.
Hristo

**Comment by EWSoftware** [comment]
There are no provisions for splitting an MSHC file.  The only way to do that as far as I know would be to document each assembly separately if you are documenting multiple assemblies with the same help project.  If that's the case, you can split each into its own help project and use the Additional Reference Links plug-in to include the other projects' info to generate links to the topics in the other files.

If you've already got a process that can split it external to the build, you could probably wrap that functionality in a plug-in so that it can be done when the project is built.

**Comment by icom85** [comment]
Thanks for the suggestions. We will be doing with with a batch file as part of the build definition.
