### ISSUE TITLE
Visual Studio 2013 Presentation Style Tweaks

### ISSUE THREAD

**Issue by jbparker** [EWSoftware/SHFB#281]
Hi @EWSoftware

First, thanks very much for this awesome tool.

I wanted to check with you about a few styling tweaks I think could benefit the default VS 2013 look & feel to more closely match the current iteration of the MSDN styles (font size & spacing).

There is more that could be done here (color of sidebar links, arrow images, etc), but that seemed like it would be a bit more involved and likely would require scripting / content changes.

Here is a [link to the diff](https://www.diffchecker.com/c68nnft9), and below is an image of the output:

<img width="1002" alt="results" src="https://cloud.githubusercontent.com/assets/5770169/14404558/a7d0a136-fe47-11e5-8954-34278e4624bf.png">

Please let me know your thoughts on this - I will make the changes (as-is, or with your thoughts) and submit the PR if you agree.

**Comment by EWSoftware** [comment]
Thanks but I think the style is fine as it is.  I definitely don't want to make the font smaller and I think the spacing is fine as it is.  Regarding the current MSDN style, that's really more of a VS2015 presentation style so that would probably be better done as a new style if someone wants to tackle it.

**Comment by jbparker** [comment]
Ok, thanks
