### ISSUE TITLE
Sporadic compile failure: "BuildAssembler : error : The current position of the navigator is missing a valid parent."

### ISSUE THREAD

**Issue by Octoate** [EWSoftware/SHFB#288]
Hi,
we are using the latest version of the SHFB (v2016.4.9.0) and are facing sporadic build failures with the new version (on our build servers and local machines). I have already increased the verbosity level, but the only failure that can be found in the LastBuild.log is this:

`BuildAssembler : error : The current position of the navigator is missing a valid parent. [D:\[...]\bin\BuildDoc\Working\BuildTopics.proj]`

I have attached the BuildTopics.proj file to this issue (NOTE: I have replaced the path to our project by an [...], so don't bother about it :-)):

[SHFB-Issue-BuildTopics.proj.txt](https://github.com/EWSoftware/SHFB/files/225768/SHFB-Issue-BuildTopics.proj.txt)

Do you have any ideas on how to trace or get around this problem?

**Comment by EWSoftware** [comment]
It's possible the new writer caches used in the Save Component and IntelliSense components are causing an issue.

You can try setting the "Maximum Save Component writer cache capacity" in the Build Category to 1 to make it write topics synchronously.  Likewise, if you are using the IntelliSense Component, edit its configuration and set the cache capacity to 1.

If it works using a value of 1, you can play around with the cache numbers to isolate which one is causing the problem if that is the case.  Since it's complaining about an invalid parent, my guess would be the IntelliSense component.  Disabling it in project should allow you to confirm that as well.  I'll take a look and see if there's anything obvious.  If you can create an example that fails, that would help.

**Comment by Octoate** [comment]
Hi,
thanks for your fast answer. I have changed the "Maximum Save Component writer cache capacity" option to "1", but the problem still occurs sporadically (1 of 5 builds are approx. affected).

At the moment there are no components activated in the documentation project, but I have to enable the "API Token Resolution", "Code Block Component" and "Intellisense Component" for the next builds.

I will also try to generate an example and hope that I can reproduce the problem somehow. Unfortunately I am not allowed to provide our solution for testing purposes.

**Comment by EWSoftware** [comment]
Were you able to create an example to duplicate this issue?

**Comment by Octoate** [comment]
Unfortunately not. I tried to extract and produce a similar documentation project, but the result had not the sporadic failures.
I also played a bit with the cache settings again and set it to "0" to allow the maximum usage of the cache. It seems that this setting has reduced the sporadic failures, but they still occur.
Any other ideas how to trace the problem?

**Comment by EWSoftware** [comment]
None that I can think of.  I can't reproduce it and nobody else has reported it.  I did take a look at the framework source to find out where that error is thrown.  It occurs in a couple of different places, neither of which really relate to the cache.  Tracing back up through the call hierarchy, the methods involved are called by common code such as removing and inserting elements so it could be occurring anywhere.

**Comment by Alex43256** [comment]
Our build process fails sometimes too. The error text is the same.

**Comment by EWSoftware** [comment]
Without an example to duplicate it, there isn't anything I can do to find the problem and fix it.

**Comment by ysubba** [comment]
Experienced same problem with the latest build. Setting Maximum Save Component writer task cache to 0 resolved the problem (for now!).

**Comment by Octoate** [comment]
After we weren't able to reproduce the failure in a different solution and with breaking our build too often (nearly every second build with "Maximum Save Component writer task cache" set to 0), we changed back to the previous Sandcastle version. This works fine for us.
We will try the next version of Sandcastle in the future (maybe not on productive systems), but we are currently on a tight schedule, so I can't investigate this issue any further :(.

**Comment by brennon** [comment]
Can this issue be reopened? We have the same problem...

**Comment by Octoate** [comment]
Ok, reopened the issue.

Btw, a colleague of mine thinks that it might be an issue if the API documentation is directly located under the root element of the documentation. E.g.:

* API documentation
** Getting Started
** Other documentation topic
** API Reference

In his project, he changed the location to a subcontent and this seem to work. E.g.:

* API documentation
** Getting Started
** Other documentation topic
** Additional API Reference text
*** API Reference

**Comment by DataWolfSoftware** [comment]
I'm a new user working on my first help file project, and I'm getting the same error. I've managed to work through all my other errors so far, and even had a successful build, but started getting this error after adding some content both to my C# files and to Summaries.

I've replaced my root path in the attached files with [root path].
[LastBuild.txt](https://github.com/EWSoftware/SHFB/files/379033/LastBuild.txt)
[AdditionalFiles.zip](https://github.com/EWSoftware/SHFB/files/379044/AdditionalFiles.zip)

**Comment by 4alexbo** [comment]
Hello,

we are using today's latest version (2016.5.28.0) with VS2015. We just upgraded to it, because our API documentation generation was disabled some months ago. I did not have time to fix it yet.
We experience the same error message. For every build. As Octoate had a suspect regarding the content structure I did some research:
- Original .content file -> this error message
- Simple .content file with one entry -> build succeeds!
- I took the original .content file and removed parts of it, step by step, until I found a few entries, which let the build succeed / fail respectively.
- I tried to identify the evil line or lines but then the build failed again everytime, no matter what I did!
- I tried the simple .content file again and the build fails here as well

Hmm, strange I thought... then I enabled the "Additional Content Only" Plug-In and then the build succeeds! I tried it several times, disabling the API documentation lets the build succeed. Otherwise it fails.

```
BuildTopics:
  BuildAssembler (v2016.5.28.0)
  Copyright c 2006-2016, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2016, Eric Woodruff, All Rights Reserved.
  Loading configuration...
  Processing topics...
BuildAssembler : error : The current position of the navigator is missing a valid parent. [c:\[...]\Help\Working\BuildTopics.proj]
  CopyFromIndexComponent: &quot;metadata&quot; in-memory cache entries used: 1 of 15.
  ResolveArtLinksComponent: Copying media files...
  ResolveArtLinksComponent: Copying media files...
  CopyFromIndexComponent: &quot;reflection&quot; in-memory cache entries used: 10 of 15.
  CopyFromIndexComponent: &quot;comments&quot; in-memory cache entries used: 5 of 30.
Done Building Project &quot;c:\[...]\Help\Working\BuildTopics.proj&quot; (default targets) -- FAILED.

Build FAILED.
```

Setting "Maximum Save Component..." to 1 or 0 does not help.

**Comment by DataWolfSoftware** [comment]
I don't know if 4alexbo had any warnings displaying, but I was going through the build output from SHFB (I've been using that instead of VS for compiling help files). And I saw that I was getting a lot of warnings about missing documentation, mostly for the code automatically created by VS when creating a web API project. So I compiled in VS and saw that there were over 200 such messages generating from the C# compiler.

After adding comments to the few items in my code that didn't have them and suppressing them in the VS-generated code, I got the C# compiler warnings down to 0. I recompiled the help files in SHFB, but I continued to see the warnings. I changed the options in the Missing Tags settings for the project so that it didn't display missing documentation.

**However, the SHFB compiler ignored the settings and continued to generate the messages.** I then set the BuildAssembler Verbosity to Errors Only. After making that change, the help files compiled normally.

I'm wondering if it's possible that there's a memory leak or some sort of list management issue involving the messages collected during the compilation process that is causing the error.

I hope this helps find the source of the problem and I hope it helps anyone else having the same problem as me.

**Comment by DataWolfSoftware** [comment]
Additional information that may help debug the source of this problem. I was combing through the SHFB code and tracing through my build logs. The errors seem to be generated by XPathNavigator methods. Considering the source of the issue would then be the XML files themselves, I examined the logs and found that XPathNavigator was likely tripping up on the generic method I have on one class.

VS replaces <T> with ``. Doing a search of the source code, I discovered that different parts of the code are doing searches differently. In some cases, the code searches for ``. In other cases, it searches only for `. In still other cases, it searches for T:`` or T:`.

I don't know if there's a difference between `` and `, but if the characters are being stripped or replaced and go "out of balance", then I'd imagine this would generate an error in XPathNavigator.

**Comment by EWSoftware** [comment]
@4alexbo, @DataWolfSoftware: As I've said before above, the most helpful thing I can get is an example that I can use to reliably duplicate this issue.  Not build logs or files from the working folder, an actual project that I can build.  To date, I haven't been able to duplicate it based on the descriptions alone.

**Comment by DataWolfSoftware** [comment]
Mr. Woodruff,

 

I’ll send you a zip of my projects (VS and SHFB) if you’ll provide me a direct email address. Please bear in mind there’s confidential information in the files.

 

Sincerely,

 

David Lee Conley

A+, Net+, MCP, MCSA

C#, ASP.NET, HTML, CSS, JavaScript, PHP, SQL

**Comment by EWSoftware** [comment]
@DataWolfSoftware : Eric@EWoodruff.us 
Thanks.

**Comment by EWSoftware** [comment]
@DataWolfSoftware :  Unfortunately, the projects you sent build without issue for me, debug and release builds.  The BuildAssembler verbosity setting has no effect either.  The replies above seem to indicate an issue with the API content placement within conceptual content.  You example contains no conceptual content.  Was anything left out that may affect reproducing the issue?

**Comment by EWSoftware** [comment]
@Octoate , @Alex43256, @ysubba , @Brennon, @4alexbo, @DataWolfSoftware: Attached below is a patched version of *SandcastleBuilder.Components.dll*.  This should resolve this issue.  Please download it, extract it, and replace the copy found in the *%ProgramFiles(x86)\EWSoftware\Sandcastle Help File Builder* folder and give it a try.

If you're interested, the details follow:

David (DataWolfSoftware) resent his example with some modifications and I was finally able to get it to fail somewhat consistently.  The failure was occurring in the Shared Content Component which replaces items in the topics with text from the shared content files (section titles, common text, icon file paths, etc.).

What made this so hard to track down is that it was completely random occurring on some builds but not others, in some help files but not others, in different topics, and with different shared content items each time.  The point of failure made no sense either.  The node it complained about not having a valid parent was perfectly valid a few lines above the point of failure with no intervening code that would corrupt it.  At one common point of failure, it had just cloned the node and the clone was made to move to the parent and it was still valid.

The only consistency was that it failed when generating the topic for website output.  In this particular test case though, it only occurred when built in combination with MS Help Viewer output.  Website output by itself or Website content with HTML Help  1 content worked fine.

I finally traced the root cause back to the Multi-format Output Component.  This component creates a clone of the document before building each output format.  It appears that `XmlNode.Clone()` is not always cloning the document in a way that keeps it valid.  I changed the component to create a brand new copy of the document from the XML rather than cloning it and this appears to have fixed the issue as it no longer suffers from the build failure after letting it continuously rebuild the same project repeatedly for several minutes.

[SandcastleBuilderComponents.zip](https://github.com/EWSoftware/SHFB/files/389509/SandcastleBuilderComponents.zip)

**Comment by ysubba** [comment]
Eric

First of all, appreciate your effort.

I tried your DLL (7/29/2016 140KB) vs the older (4-29-2016 139KB) but go this hard error...

Attached the log file. 

Regards
Subba


	MergeCustomConfigs
SHFB(0,0): error BE0021: The project contains a reference to a custom build component 'Code Block Component' that could not be found.
	Failed
	Build details can be found in C:\Help\LastBuild.log
Done building project "PrismaSDKHelp.shfbproj" -- FAILED.

========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

[LastBuild.zip](https://github.com/EWSoftware/SHFB/files/390322/LastBuild.zip)

**Comment by ysubba** [comment]
Eric

I forgot to add - when I go to the Components tab, select Code Block Component in the Build Components in this project listbox and click Configure, it says: The selected build component could not be found in any of the component or project folders and cannot be used. 

Regards
Subba

**Comment by 4alexbo** [comment]
For me your provided dll works! 
Yes, I also build MS Help and Website output. Maybe it is really just that combination!

Now I will try to make it work on our build server...

Thank you!

**Comment by 4alexbo** [comment]
Buildserver is happy as well! :)

**Comment by DataWolfSoftware** [comment]
Sad to say not only was I able to get the same "invalid parent" error, but I'm also getting an endless build once it gets to the "Processing topics" stage.

**Comment by EWSoftware** [comment]
@ysubba:  You need version 2016.5.28.0.

I posted that on Friday but it appears to have been lost so I'm posting again in case you missed it.

**Comment by EWSoftware** [comment]
@DataWolfSoftware:  Don't know what to tell you.  As long as it got replaced correctly, it should resolve the issue.  Not sure what you mean by "endless build".  If you enable verbose logging do you see any messages coming through?

**Comment by ysubba** [comment]
@EWSoftware: Got 2016.5.28.0. Added patch file 16.5.28.0, unblocked it and restarted VS2015. Was able to successfully build twice without any errors. 
Thanks much.

**Comment by Octoate** [comment]
I will test it as soon as possible, too. We are currently in a release phase, so it will take about a week until I can test it.

**Comment by Octoate** [comment]
Ok, so I have run the documentation builds on our build servers for some days and the problem seems to be fixed :-)! Thanks a lot for your effort, I guess we finally nailed it.
I will close this issue now.
