### ISSUE TITLE
PresentationStyle folder for Nuget Package usage

### ISSUE THREAD

**Issue by twenzel** [EWSoftware/SHFB#289]
I'm using the NuGet package to build our documentation on the build server.
We also using a custom PresentationStyle. Where should the presententation style files be copied to in order SHFB will find it?

Or should I deploy the presentation style via NuGet as well? How should I package the files then?

**Comment by EWSoftware** [comment]
You should have the SHFBROOT property defined in your project file so that it can find the tools.  Point the Component Path property at your presentation style folder if it's in a fixed location.  You can also put the presentation style folder somewhere under the project folder and SHFB will find it there too automatically.  See the [XCOPY/NuGet Build Server Deployment](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm) topic for more information.

**Comment by twenzel** [comment]
Thanks. 
I've found my issue, the presentation style assembly was build against an old version of Sandcastle.Core.

Btw. Is there a documentation how to change my presentation style from 2014.12 version (using sandcastle/conceptual/....config) to the current one (using BuildAssembler.config)?

**Comment by EWSoftware** [comment]
See the presentation styles in the current release.  They use a combined configuration file.  The Switch Component is used to combine both.
