### ISSUE TITLE
Request for a "Portable Executable" scaffold / process

### ISSUE THREAD

**Issue by pnstickne** [EWSoftware/SHFB#29]
I would like to run SHFB (and SandCastle) to build HTML files are part of an automated process.

This process is done on "clean room" build machines - it would be very nice to be able to run some _no-install_ executables.

While the UI-based SandCastle installer (and SHFB therein) are nice _for end-users_ it really hampers on getting an automated process pushed.

**Comment by pnstickne** [comment]
See under "XCOPY" in the documentation - would still like a clean distrib. of such.

**Comment by EWSoftware** [comment]
A NuGet package is available using a prior release.  That lets you install the minimal set of tools within the project and build it without installing or XCOPYing the tools manually.  Enabling NuGet's package restore in the solution allows machines without it to download it on first build.

I had to remove it for the current release due to size restrictions in the NuGet gallery.  I'll be working on breaking up the reflection data to reduce the size and make it available for a future release.

**Comment by pnstickne** [comment]
A proper NuGet package would definitely help!

(I don't know about others, but HTML is the only target I .. target.)
