### ISSUE TITLE
SHFB: Error BE0020: Unknown substitution tag ID: 'MSHelp2SdkLinkType'

### ISSUE THREAD

**Issue by markusschaber** [EWSoftware/SHFB#296]
A while ago, i upgraded to version 2016.4.9.0.

Today, I tried a project which always worked well in the past, but now, I get the aforementioned error when trying to build. Is that a known problem? (a google search returned 0 matches...)

I attached project and log file, if you need any more information, please tell me.
[LastBuild.log.txt](https://github.com/EWSoftware/SHFB/files/272209/LastBuild.log.txt)
[ScriptEngine.shfbproj.txt](https://github.com/EWSoftware/SHFB/files/272218/ScriptEngine.shfbproj.txt)
[systeminformation.nfo.txt](https://github.com/EWSoftware/SHFB/files/272219/systeminformation.nfo.txt)

One important data point might be that some of the assemblies or their dependencies target .NET Framework 2.0.

(Btw, I had to rename the file extensions to .txt to allow upload - the filter here is a bit picky... :-()

Thanks,
Markus Schaber

**Comment by EWSoftware** [comment]
See the SHFB release notes from the last version you used through the current release or the one last used by that project.  There have been a significant number of changes.  Most notably, all of the deprecated features have been removed which is related to the error you are seeing (that happened in v2015.7.25.0).

Most likely, you need to remove, re-add, and configure any custom build components and plug-ins in the project such as the E-Sent cache components so that they are using the most recent configuration elements and remove any obsolete ones.

**Comment by markusschaber** [comment]
I can confirm now: that solved the problem, thanks!
