### ISSUE TITLE
Build hangs after "GenerateInheritedDocumentation" line

### ISSUE THREAD

**Issue by ZbynekZ** [EWSoftware/SHFB#299]
I have a SHFB project which consistently hangs during build. The last line emitted to the console is "GenerateInheritedDocumentation" - and it stays there for hours. It looks like it is consuming one thread (of MSBuild.exe) to the max. Can be interrupted by Ctrl+C. What can I do? 

As an interesting sidenote, I have a second project that is based on the very same assemblies/XML docs, and just has a *wider* API filter in the project. This project builds just fine. The project that hangs during the build is supposed to be a concise version of the doc, hence the narrower API filter. I find it quite weird - I would rather expect the bigger project to exhibit an issue.

This is with the current SHFB as of today.

**Comment by EWSoftware** [comment]
It may be getting further than the reported step and may be in the Build Help Topics step which can take a long time if you have an extremely large set of assemblies to document.  In Visual Studio, you can verify this by going into _Tools | Options | Sandcastle Help File Builder_ and enabling the _Build output verbose logging enabled_ option.  If using MSBuild, specify the `/p:Verbose=True` option.  If it's getting past that step, you should see a lot more output.

**Comment by ZbynekZ** [comment]
Thank you. I think it is truly hung, but of course I cannot prove it because I would have to wait indefinitely first. I have following reasons to think so:
- I have waited over 12 hours, and that's on a fast machine.
- It used to work well with this project (and much faster) before last round of code changes (but there very too many of them, so it's not realistic to pinpoint where it went wrong).
- The other SHFB project based on the same assemblies, but with broader API filter, finishes in reasonable time.

After applying the MSBuild command-line option, the output stops in such a way that it shows "  Merging inherited documentation...", and then an empty line.

I cannot rule out that I have some kind of circular reference in the inheritdoc-s; however, when this has happened before, it used to properly detected and reported by SHFB, and the build had stopped.

**Comment by EWSoftware** [comment]
Can you supply the project in question so that I can test it and duplicate the issue?

**Comment by ZbynekZ** [comment]
Thank you for this offer. I have minimized the project; it comes to 15 MB after zipping. I will place it on Web for download and send you a link by email, would that be OK ?

**Comment by EWSoftware** [comment]
That would be fine.  Thanks.

**Comment by ZbynekZ** [comment]
I just wonder whether you have received the project? I have sent the link by email on May 30, 2016. Thank you.

**Comment by EWSoftware** [comment]
Sorry for the delay, I didn't get around to posting what I found.  I've fixed the underlying issue that causes the *GenerateInheritedDocs* tool to hang.  It was caused by an `inheritdoc` tag nested within an inherited `param` element which caused it to get stuck in a loop.  However, the fix won't get you the documentation you are trying to get.  In this particular case, you actually need to remove the `param` elements containing the nested `inheritdoc` tag and add an `inheritdoc` tag at the root of the member comments in their place.

When nested, the documentation is not inherited recursively up the parent member chain.  It only pulls in the nearest parent's comments for that element.  When you remove the elements, the `inheritdoc` tag at the root level will inherit all comment elements from the parents excluding those defined on the member.  So, in this case for example, you have a `summary` element which would override the one in the inherited parent element and it would add the `param` elements from the parent.  If the parent also has an `inheritdoc` tag and no `param` elements, it would pull them from its parent and so on up the line.

Most of yours seem to be `param` elements for the `info` and `context` parameters on `GetObjectData()` methods.  So, as noted, remove those and add a single `inheritdoc` tag in their place.  That will generate the correct inherited documentation and will allow the build to continue.

**Comment by ZbynekZ** [comment]
Thank you very much. I have fixe the problematic elements, and it works well now. BTW, I would not write them myself this way, <inheritdoc> tags were used properly elsewhere. I have probably copied it over from somewhere, but at the moment I cannot determine the true origins of it.

**Comment by LunarWhisper** [comment]
Hi, @EWSoftware! Any chance this issue will be fixed? I expect that in this case a warning will be printed, or at least an understandable error, indicating the problem. The fact that the build hangs now seems completely wrong. :(

**Comment by EWSoftware** [comment]
This thread is 6 years old and, as noted in the comments above, the issue was fixed.  If you're using an older version, update to a later release that contains the fix.  If you are seeing this issue in the latest release, please provide an example project that demonstrates the issue.
