### ISSUE TITLE
How to create in-page Table of Contents

### ISSUE THREAD

**Issue by michfuchs** [EWSoftware/SHFB#303]
I would like to include a TOC that contains the section header links on the page. See for example this page (screenshot below): https://msdn.microsoft.com/en-us/library/9h8dy30z.aspx (right hand side: "In this article")

How can I achieve that, is there some standard functionality to do it, can I use xslt (how to get hold of all sections)?

![2016-06-07_12-06-29](https://cloud.githubusercontent.com/assets/9607008/15888902/222b645c-2d69-11e6-8385-87fd735550e6.png)

**Comment by EWSoftware** [comment]
You'd have to modify the presentation style, specifically the XSL transformations.  If you want it to function just like the current MSDN page you referenced, there would also be script changes in order to get it to move the highlight based on the topmost visible section header.

How you'd do it I can't really say.  More likely than not, you'd have a template called at some point when generating the body that varies based on the topic type (namespace list, type members list, or general topic, plus changes to the MAML conceptual templates for similar behavior there).  You'd probably have to see what conditions are used to include each section and use those to output a link to them if those conditions are met.  The one for MAML topics should be pretty straightforward as all you'd need to do is search for section elements with a title and perhaps an address attribute to limit it to those the user wants in the list.

**Comment by michfuchs** [comment]
Turns out that for conceptual pages, it's as easy as 
`<?xml version="1.0" encoding="utf-8"?>
<topic ...>
  <developerConceptualDocument ...>
    
    <introduction>
      <autoOutline/>
    </introduction>`

For API reference documentation however, the same seems a major headache. I finally decided to store the t_body output in a variable, send it to a template that will parse the output for divs with the class collapsibleAreaRegion, extract the title and the id from them, and write those to a TOC. Let me know if you see an easier way.

New stylesheet custom_sandcastleTOC.xsl:

    <?xml version="1.0" encoding="utf-8"?>
    

    <xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
        xmlns:msxsl="urn:schemas-microsoft-com:xslt" exclude-result-prefixes="msxsl"
    >
      <xsl:output method="xml" indent="yes"/>

      
      <xsl:template name="t_custom_toc">
        <xsl:param name="p_content" />
        <xsl:variable name="p_sections" select="$p_content//div[@class='collapsibleAreaRegion']"/>
        <xsl:if test="p_sections">
          <p>
            This topic contains the following sections:
          </p>
          <ul>
            <xsl:for-each select="$p_sections">
              <xsl:variable name="v_id" select="concat('#',@id)"/>
              <xsl:call-template name="t_custom_toc_item">
                <xsl:with-param name="title" select=".//span[@class='collapsibleRegionTitle']/include"/>
                <xsl:with-param name="id" select="$v_id"/>
              </xsl:call-template>
            </xsl:for-each>
          </ul>
        </xsl:if>
      </xsl:template>

      
      <xsl:template name="t_custom_toc_item">
        <xsl:param name="title"/>
        <xsl:param name="id"/>
        <li class="outlineSectionEntry">
          <a>
            <xsl:attribute name="href">
              <xsl:value-of select="$id"/>
            </xsl:attribute>
            <xsl:copy-of select="$title" />
          </a>
        </li>
      </xsl:template>

    </xsl:stylesheet>


Adjustments to main_sandcastle.xsl: 

    <xsl:import href="custom_sandcastleToc.xsl"/>

    <xsl:template name="t_body">
      <xsl:variable name="bodyStandard">
           
      </xsl:variable>
      <xsl:call-template name="t_custom_toc" > 
        <xsl:with-param name="p_content" select="msxsl:node-set($bodyStandard)"/>
      </xsl:call-template>
      <xsl:copy-of select="$bodyStandard"/> 
    </xsl:template>

Add id attribute to each section title div in t_putSection and t_putSectionInclude (globalTemplates.xsl):
    <div class="collapsibleAreaRegion" id="{concat($togglePrefix,'Title')}">

**Comment by EWSoftware** [comment]
If you don't need the exact behavior of the MSDN version, `autoOutline` and your additions should be fine.  I can't think of a better way.

**Comment by michfuchs** [comment]
Ok thanks, I appreciate your quick replies!
