### ISSUE TITLE
Help file project appears to lock DLL

### ISSUE THREAD

**Issue by kevinrjones** [EWSoftware/SHFB#308]
I have a SHFB project in my solution. When I build the solution, if I exclude the project then the solution builds fine. If I include the SHFB project then the solution builds OK the first time but on subsequent builds it tells me that the DLL the SHFB project depends on is locked. I have to restart Visual Studio and start it again to get rid of the lock.

If I leave the SHFB project out of the solution all is fine

**Comment by EWSoftware** [comment]
If your SHFB project is at the same or higher level in the folder structure containing the documented assemblies, it would find them and load them to search for plug-ins and components.  That would lock them as it would if you've got the Component Path property pointing at the folder containing the documented assemblies.

The solution would be to put the SHFB project in a sub-folder within the folder containing the documented assemblies project.  If it's because the Component Path is pointed at the folder containing the documented assemblies, the solution would be to move any custom components to a different location or a sub-folder that gets them out of the way.

**Comment by kevinrjones** [comment]
Thanks Eric

On 17 June 2016 at 18:12, Eric Woodruff <notifications@github.com> wrote:

> If your SHFB project is at the same or higher level in the folder
> structure containing the documented assemblies, it would find them and load
> them to search for plug-ins and components. That would lock them as it
> would if you've got the Component Path property pointing at the folder
> containing the documented assemblies.
>
> The solution would be to put the SHFB project in a sub-folder within the
> folder containing the documented assemblies project. If it's because the
> Component Path is pointed at the folder containing the documented
> assemblies, the solution would be to move any custom components to a
> different location or a sub-folder that gets them out of the way.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EWSoftware/SHFB/issues/308#issuecomment-226827001>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAI8GGd-16tQ-3nLlIRH_4y3WKBR-va0ks5qMtV7gaJpZM4I4XhF>
> .
>



-- 
Kevin
