### ISSUE TITLE
VSPacakge fails if Visual Studio runs it from the Shadow Copy location

### ISSUE THREAD

**Issue by 1Siger1** [EWSoftware/SHFB#31]
I have installed latest package. Added new project to VS 2013 Update 4. Set source dll's and refereces and tried to build project. I got:
Warrning
Help file builder content for the 'en-US, English (United States)' language could not be found.  Using 'en-US, English (US)' defaults.
Error
Unable to transform template 'en-US.xml': Could not find a part of the path 'C:\Users\******\AppData\Local\assembly\dl3\B8YMJO3A.LZE\PZPZXZV2.ZMG\f23369c6\0006711a_4106d001\VS2013\SHFBContent\en-US.xml'.
I have tried to generate documentation using SandcastleBuilderGUI.exe and everything is working fine.
Tried also running it from Visual Studio on different computer, but the error stays almost the same.
How to solve this problem. My operating system is Windows 8.1 with latest updates.

**Comment by EWSoftware** [comment]
It looks like the SHFBROOT system environment variable isn't set.  You may need to reboot for it to take effect.

**Comment by 1Siger1** [comment]
Rebooted. Tried old version (2014.11...), but the error is the same. When i write in command line - echo %SHFBROOT% output is
C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
It looks that the path variable is set correctly.

**Comment by EWSoftware** [comment]
This is a new one.  I don't know why it's doing it but based on the assembly path (*AppData\Local\assembly\dl3*) it looks like the Shadow Copy feature for the app domain Visual Studio is using for the package assemblies has been enabled.  From what I found related to that path, for some reason the app domain is copying all assemblies to that location before running them.  Since the package doesn't recognize that as a package location to run from it's assuming that's where to find the supporting files rather than using SHFBROOT as it needs to do.

The suggestion I saw to stop it from running from there was to delete the folder (in this case C:\Users******\AppData\Local\assembly\dl3\B8YMJO3A.LZE or whatever it may have changed to).  Give that a go and see if it works.

I'll add code to check for the *AppData\Local\assembly* location for the next release.

**Comment by 1Siger1** [comment]
I tried to remove this directory B8YMJO3A.LZE (dl3 also) but VS recreate it every time I try to build Documentation project, and gives me the same error every time. So your solution does not solve the problem for me :(.

**Comment by EWSoftware** [comment]
## Patch Notes
A patched version of the VSIX file (*SHFBVisualStudioPackage_Issue_31_Fix.vsix*) is available on the related [v2015.1.12.0 release page](https://github.com/EWSoftware/SHFB/releases/tag/v2015.1.12.0).  To install it:

* Run the guided installer to install the latest release of the SHFB tools if you have not done so already.  Do not install the VSPackage included with the guided installer.
* If you have installed the VSPackage from the guided installer, use the Tools | Extensions and Updates option in Visual Studio to remove the installed SHFB package.
* Restart Visual Studio to make sure the package has been removed.
* Download the patched VSIX file from the release page.
* Double-click on it in Windows Explorer to run it and install it in the Visual Studio versions of your choice.

**Comment by 1Siger1** [comment]
Removed SHFB from my computer and VS. Installed v2015.1.12.0 without Visual Studio Package. Verified in Visual Studio (no extension). Installed SHFBVisualStudioPackage_Issue_31_Fix.vsix. Create new project in VS. Try to build documentation project, but get same error.
Removed extension from VS and shut down VS. Remove directory dl3 from AppData. Installed extension. Start VS and try to build project. The result was the same. File not found.
Copied whole content of c:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2013 to C:\Users******\AppData\Local\assembly\dl3\B8YMJO3A.LZE\PZPZXZV2.ZMG\f23369c6\0006711a_4106d001 (with directory VS2013 this is my target) and this let me to build documentation from VS2013.
I think that the problem was not fixed.

**Comment by EWSoftware** [comment]
I can't see how it's setting up the app domain to use shadow copy in the first place.  What kind of project are you documenting?  Perhaps it's related to that.

**Comment by EWSoftware** [comment]
I'd still like to know what project type you are getting this problem with but I think I've figured out the continuing issue.  The components such as the presentation styles also use the assembly location as the path in which to find their supporting files.  I've made changes so that it uses the code base location rather than the executing assembly location which should resolve the problem for good.  This change won't be published just yet as it touches quite a few things.  However, since you appear to have a workaround you should be able to carry on for the time being.
