### ISSUE TITLE
'Code Block Component' reports errors even if inactive

### ISSUE THREAD

**Issue by FugDev** [EWSoftware/SHFB#317]
I migrated to Version: v2016.5.28.0

SHFC Project Configuration: One .dll + .xml. xml cointains references to `<example><code source=".."/></example>`
Since I only use this project for the 'Version Builder' plugin of a 'main project', I do not need+want the sample code here. 

SHFC "Build Output" reports:
    The configuration for 'Code Block Component' is disabled and will not be used.
...
BuildAssembler : error : CodeBlockComponent: [..] Unable to load source file '..RuntimeExamples.cs'.  Error: <path not found>

My impression: if the code block component is inactive, it means only the configuration page is not used. It still is part of the build process even if it is removed from the 'Build Components in This Project" list.

This feature worked fine in my previous SHFC version: v2014.5.31.0

It would be great if SHFC ignored the `<code source=".."/>` entries, if CodeBlockComponent is disabled.

**Comment by EWSoftware** [comment]
[Disabled in this case](http://ewsoftware.github.io/SHFB/html/da405a33-3eeb-4451-9aa8-a55be5026434.htm#DisableCodeBlock) means it just won't syntax highlight the code.  It is still included to support all of the other options such as importing code blocks from external sources and normalizing the leading whitespace.  This has been the behavior for many years.  If it was working before, you've probably made a change to the XML comments that are causing the error either in one of the older projects documentation sources or the main project's documentation sources.

Since BuildAssembler doesn't run for the projects in the Version Builder Plug-In configuration, the error is coming from the main project that contains the plug-in.  Bear in mind that XML comments from all versions are still being merged from all of the other projects since it needs them for methods that are documented from prior versions whether or not they are in the latest release.  If you've got an invalid code reference in one of them, you'll either need to fix it or add the Code Block Component to the main project on the Components property page and configure it to ignore missing code files.  It'll build but the topic containing the example will just contain a placeholder containing a "missing code" message.
