### ISSUE TITLE
Clarify support for 'Linked Items'

### ISSUE THREAD

**Issue by lab2k1** [EWSoftware/SHFB#319]
The documentation page for [Folder and File Items](https://ewsoftware.github.io/SHFB/html/0a9d6da4-cff6-4664-8b64-b7df04c8a37d.htm) notes at the end that:

> The project supports linked items as well (adding them is not supported from the standalone GUI). Linked items will have a Remove option rather than a Delete option. This removes them from the project but leaves them on disk in their original location since they may belong to another project.

However, it's not obvious how such linked items can be added *outside* the GUI.

**Comment by EWSoftware** [comment]
The standalone GUI supports them for use but can't add them.  They can be added in Visual Studio in the usual manner.  Select the option to add an existing item and in the file selection dialog box, rather than clicking the *Add* button, click the drop down arrow on it and select the *Add as Link* option.

If you don't have Visual Studio, the only way to create linked items is by manually editing the project in a text editor.  Add a build item to an item group.  This is done by adding an element named after the build action (i.e. `None` for a MAML topic).  The `Include` attribute points to the relative path of the file which is typically outside of the current project's folder.  Add a `Link` element nested within the build item and set its property value to the relative path of the item within the SHFB project.  For example:

``` XML
<None Include="..\SomeOtherProject\Content\SharedMamlTopic.aml">
  <Link>Content\SharedMamlTopic.aml</Link>
</None>
```

The above creates a linked MAML topic.  Its physical location is one level up from the SHFB project folder in another project folder (..\SomeOtherProject\Content).  Its virtual location within the SHFB project will be in a folder called .\Content.

**Comment by lab2k1** [comment]
Thank you for the quick and complete answer. I believe it (or at least the `example` part at the end) would make a great addition to the final `note` in [Folder and File Items](https://ewsoftware.github.io/SHFB/html/0a9d6da4-cff6-4664-8b64-b7df04c8a37d.htm).

**Comment by EWSoftware** [comment]
I'll add a section that explains the linked items.
