### ISSUE TITLE
NuGet release missing [Content_Types].xml

### ISSUE THREAD

**Issue by recycleddan** [EWSoftware/SHFB#331]
In the NuGet package version of SHFB, the [Content_Types].xml is missing from PresentationStyles\OpenXml\DocumentParts. This causes an OpenXML build to fail with a FileNotFoundException for the SandcastleBuilder.Utils.MSBuild.BuildOpenXmlFile task.

I checked the 2016.5.28, 2016.4.9, and 2015.10.10 releases and none contained this file.

**Comment by EWSoftware** [comment]
It looks like the file is there but when packaged, NuGet is encoding the brackets so the filename changes to *%5BContent_Types%5D.xml*.  I'll have to see if there's a way to stop NuGet from doing that.  In the meantime, you can probably rename the file manually within the extracted package folder as a workaround.

**Comment by recycleddan** [comment]
I manually added the [Content_Types].xml to the package directory after restoring. That uncovered that the package was also missing the PresentationStyles\OpenXml\DocumentParts\_rels directory and the .rels file in that directory. I manually added those as well and the build finally worked.

**Comment by EWSoftware** [comment]
The folder and the file are in the package.  NuGet seems to have a problem restoring them.

**Comment by EWSoftware** [comment]
If the package is installed from a local feed, the files are there.  If installed from the nuget.org feed, they are removed.  It appears I'll have to find a way to package them as embedded content in the presentation style assembly so that they don't get lost.  Those names are part of the Open Packing Conventions so they are probably in conflict somehow with the package installation.
