### ISSUE TITLE
Installing SHFB installs Plug-ins instead of installing Sandcastle Helf File Builder template in Visual Studio 2015

### ISSUE THREAD

**Issue by DeboleenaP** [EWSoftware/SHFB#338]
I simply downloaded SHFBInstaller_v2016.5.28.0 and installed it, but plug-ins were installed instead of SHFB templates. Although, if I work directly on SHFB application, it creates projects properly.
Is this a bug or I am missing any other installations I should be doing?

**Comment by EWSoftware** [comment]
I don't know what you mean by "plug-ins were installed instead of SHFB templates".  If you ran the guided installer, there's an option to install the SHFB Visual Studio package.  It's a separate step after the main SHFB tools are installed.

If you did that, you should find it when you go to Tools | Extensions and Updates and select the Installed category.

If you're having trouble finding the SHFB project templates to create new projects, start with the [Visual Studio Integration Package](http://ewsoftware.github.io/SHFB/html/b128ad2a-787e-48c7-b946-f6953080c386.htm) help topic and its subtopics.  It describes how to use it and how to find everything.
