### ISSUE TITLE
Latest Sandcastle release misinterprets enum and struct types as classes

### ISSUE THREAD

**Issue by shawnhar** [EWSoftware/SHFB#343]
I recently upgraded to SHFB.2016.9.17, which appears to have a regression with generating documentation for enum and struct types.  These all now show up in the "classes" section of the API Reference index.  Enum types are described as eg.

    public sealed class CanvasCapStyle : Enum

and the enum field named "value__" (which is emitted by the C# compiler) is included in the documentation.

**Comment by EWSoftware** [comment]
What framework?  Can you attach an example?

**Comment by shawnhar** [comment]
I narrowed this down to an oddity in my doc build process - one of my assemblies is built against .NET Framework 4.5, but my Sandcastle project that consumes it specifies .NET for Universal Windows.  I obviously shouldn't be mixing up frameworks like this.

Note though that prior to the most recent version, Sandcastle was able to generate valid docs even with this framework version mismatch.

**Comment by EWSoftware** [comment]
The Universal Framework redirects all system types like `Enum` to the System.Runtime assembly.  They're in mscorlib for the standard .NET framework.  When mixing assemblies built against different frameworks like that, the system types won't match up since they're in different assemblies so you will see the issue above.  That's partly why SHFB won't let you mix projects with differing framework targets as documentation sources.  It can't detect that when you specify the assemblies as documentation source directly.

There were changes in MRefBuilder in the most recent release needed to support the most recent .NETCore framework so that's probably why it stopped working.  It was unsupported in prior releases and was not intended behavior so if it worked, it was more by luck than anything else.

You should be able to use the Version Builder plug-in to work around it since it would build the reflection data for each documentation project separately and then merge it into a common set for producing the help file.
