### ISSUE TITLE
Too many topics associated to the "Dispose method" keyword.

### ISSUE THREAD

**Issue by peterhession** [EWSoftware/SHFB#350]
I've hit a limit with our help file where there are too many references to Dispose methods across all our classes for the help builder to handle. Can anyone suggest a way to avoid this?

**Comment by EWSoftware** [comment]
What help format?  As I recall, this was only an issue with Help 2 (HxS) files.

**Comment by peterhession** [comment]
No, we're using HTML Help (.chm).

**Comment by EWSoftware** [comment]
Assuming the issue is the same as it was for Help 2, the solution was to create a build component that stripped out the excess keywords from the topics.  You could probably do something similar.  Here's the link to the old component.  It would need updating for use with the latest release of SHFB but you shpuld be able to cut and paste the main processing into a new build component project.  The processing may differ since it's Help 1 as opposed to Help 2 but perhaps not since I think at that point, the HTML is the same for both.

http://sandextensions.codeplex.com/SourceControl/latest#SandcastleExtensions/SandcastleExtensions.Components/Components/KeywordsFilterComponent.cs
