### ISSUE TITLE
Remove search functionality from website format

### ISSUE THREAD

**Issue by drieseng** [EWSoftware/SHFB#353]
Is it possible to remove the search functionality when building help in the website (HTLM/ASP.NET) format?

This should also not generate any files related to search functionality.

**Comment by EWSoftware** [comment]
You could probably include a modified version of the *branding-Website.css* file in your project and change the visibility of the `form#SearchForm` style to hidden.  Place the file in a `styles\` folder within the help project so that it gets copied to the right location and overrides the standard file.

You can't prevent the keyword index files from building by default.  If you want to do that, you'd need to create a plug-in that suppresses the `GenerateFullTextIndex` build step.
