### ISSUE TITLE
Markdown Links Broken

### ISSUE THREAD

**Issue by tisaacs** [EWSoftware/SHFB#360]
When using the markdown output setting, links in tables are inline html, for example:

```
## Classes
&nbsp;
<table>
    <tr>
        <th></th>
        <th>Class</th>
        <th>Description</th>
     </tr>
     <tr>
         <td>![Public class](media/pubclass.gif "Public class")</td>
         <td><a href="T_NameSpace_MyClass">MyClass</a></td>
         <td>Class description</td>
      </tr>
</table>

```

It doesn't however include the `.md` extension, meaning the the links are actually broken.
This happens with all `Topic file naming method` settings.

**Comment by EWSoftware** [comment]
The output is geared towards GitHub which does not include the extensions on links.  See the [spell checker wiki](https://github.com/EWSoftware/VSSpellChecker/wiki/843b1166-b105-8d83-2699-b089b0cdbb20) for an example.  If the extension is included, it goes to the raw page rather than the rendered content.

If you're generating it for a site other than GitHub, I could include an option to include the extension if its required.

**Comment by tisaacs** [comment]
Thanks for the prompt reply & the brilliant project!

That makes more sense.
I've found a work around which uses a runs a small script after build. The script uses a regex replace to add the extension which has solved my issue, so I'm happy for you to close the issue if you don't think it's worth implementing the option (I'm probably an edge case).

On 26 Oct 2016, at 16:25, Eric Woodruff <notifications@github.com<mailto:notifications@github.com>> wrote:


The output is geared towards GitHub which does not include the extensions on links. See the spell checker wiki<https://github.com/EWSoftware/VSSpellChecker/wiki/843b1166-b105-8d83-2699-b089b0cdbb20> for an example. If the extension is included, it goes to the raw page rather than the rendered content.

If you're generating it for a site other than GitHub, I could include an option to include the extension if its required.

-
