### ISSUE TITLE
Documented Namespaces (assembly) disappear in web help

### ISSUE THREAD

**Issue by hounddog22030** [EWSoftware/SHFB#363]
When we navigate to the index page of our help @ http://deploy2the.cloud/help/html/Welcome.htm or http://deploy2the.cloud/help  the documented assemblie(s) show up on the left tab.

You can see in the below image as "Bisque.Aws Namespace" & "Bisque.AutoScaling" & etc.

![image](https://cloud.githubusercontent.com/assets/2836974/19877763/69f4e7c4-9fb8-11e6-8e43-3d07ca01bbc7.png)

But, when you click on a link like "Welcome AWS Marketplace Bisque User" the "Bisque.Aws Namespace" disappears as shown below.

![image](https://cloud.githubusercontent.com/assets/2836974/19877782/8b7feae2-9fb8-11e6-90a6-edf997cb57b2.png)

Any thoughts on why this is happening?

Thanks!

**Comment by EWSoftware** [comment]
It's modeled after MSDN where you only see the root entries, the parent and its siblings, along with the siblings of the selected topic.  Since your namespaces are not part of the root, they don't show up when you have a nested topic selected.  Don't make the namespaces a parent of the root topic, insert them after the selected topic rather than being a child of it.

**Comment by Sajuz** [comment]
Same issue exist for our Documented project also .In previous version this issue is not exist .But after converting project to 4.6.2 this above issue exist . Could you please tell me how to solve this issue .

**Comment by EWSoftware** [comment]
Using .NET 4.6.2 has nothing to do with it.  See the post above, it's by design and the solution is listed there.  If you want don't like the lightweight style and want the full TOC to show always, use the VS2010 style.
