### ISSUE TITLE
UWP issue BE0065

### ISSUE THREAD

**Issue by mumford** [EWSoftware/SHFB#376]
I'm trying to build documentation for a UWP project, but I'm getting the following error:

SHFB: Error BE0065: BUILD FAILED: A numeric comparison was attempted on "$(TargetPlatformMinVersion)" that evaluates to "10.0.10240.0" instead of a number, in condition "'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'".  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets

I created a sample project that targets Windows 10 Anniversary Edition (10.0; Build 14393) with a minimum version of Windows 10 (10.0; Build 10240). Here's the sample project [doc-test.zip](https://github.com/EWSoftware/SHFB/files/642875/doc-test.zip). And here's the Sandcastle build output 
[Build Output.txt](https://github.com/EWSoftware/SHFB/files/642876/Build.Output.txt).

Any ideas? Thanks!

**Comment by EWSoftware** [comment]
It builds without issue in VS2015.  I tried it from the command line and was able to duplicate the error when using MSBuild 12.0.  Switching to MSBuild 14.0 resolved the issue and it built without error.  I assume MSBuild 12.0 is using an outdated version of the SDK so it doesn't know about the newer stuff for the Windows 10 Anniversary update.

**Comment by mumford** [comment]
Yeah, I've not had any issues building in Visual Studio, and the csproj for the project sets the ToolsVersion to 14.0. However, I'm running into the build errors with the SandCastle GUI. Should I be using the build events to get this done?

https://ewsoftware.github.io/SHFB/html/8ffc0d37-0215-4609-b6f8-dba53a6c5063.htm

**Comment by EWSoftware** [comment]
The standalone GUI may need updating to build against newer versions of the MSBuild assemblies or it may needs to pick a more appropriate tools version when building SHFB projects.  I'll take a look at it to see if it can be fixed.  For now, as noted, there are workarounds for the issue by using Visual Studio or MSBuild 14 from the command line.

Build events won't do anything here.  Just use MSBuild 14 (%ProgramFiles(x86)\MSBuild\14.0\bin\MSBuild.exe) rather than older versions or the ones in the framework folders.  Use it whether you're building the SHFB project by itself or a solution file containing the documented assembly and the documentation project.
