### ISSUE TITLE
VS2013 presentation style only shows active category

### ISSUE THREAD

**Issue by MulleDK19** [EWSoftware/SHFB#384]
The VS2013 style is far better looking than VS2010, but the contents table on the left only shows the active element, which makes it extremely cumbersome to navigate, since you have to start all the way at the root before you can then navigate back down the tree to another element.

**Comment by EWSoftware** [comment]
It was modelled on the MSDN content which acts in a similar fashion and uses a lightweight TOC style.  You'll only see the selected topic and any others at the same level.  You do need to expand the parent nodes to see the other topics.

Note that nesting your API content as the child of a conceptual topic can make it awkward to use.  The solution in that case is to move the API content so that its at the root level, not a child of another topic.
