### ISSUE TITLE
Xml Intellisense - Can't Scroll

### ISSUE THREAD

**Issue by CharlesCross** [EWSoftware/SHFB#391]
Any of the versions labeled 2016 have the following problem:

1. Create a new solution with a class library project.
2. Insert a blank line before "public class class1"
3. Type '///' to insert the summary.
4. Type '<' which bring up an intellisense scroll box.

 Attempting to scroll with the keyboard up and down keys does not work.

I am using Visual Studio Community 2015.

Charles.

**Comment by EWSoftware** [comment]
@sharwell: Since you wrote the code, can you perhaps take a look at it?  I took a look but I can't figure out why it's preventing scrolling when using the keyboard.  I fixed a couple of other issues in item #361 but it doesn't appear to be related to that or those changes.  If you click in the popup with the mouse it does occasionally allow movement with the arrow keys but usually stops once you get to the end of a set with the same starting letter.

@CharlesCross: For the time being you can use Tools | Options, go to the Sandcastle Help File Builder category, and uncheck the "Enable extended XML comments completion options" checkbox. That'll turn off the additional completion options related to that feature. Just close and reopen any files and it'll take effect.  It'll allow the list to scroll but you'll loose the extra SHFB specific completion options.

**Comment by sharwell** [comment]
@EWSoftware Are you able to reproduce the issue? I have a modified build of 2014.11.22.0 installed and can't reproduce it there.

**Comment by EWSoftware** [comment]
@sharwell: Yes, it is reproducible with the latest release v2016.9.17.0.  I think it has something to do with the changes to the keyboard handler to fix issue #91.

**Comment by sharwell** [comment]
Thanks I was able to reproduce it :smile:
