### ISSUE TITLE
.net 4.6 problem

### ISSUE THREAD

**Issue by CapitanPlanet** [EWSoftware/SHFB#395]
Hi. I have problem with building solution projects in .net 4,6 and Sandcastle giving me error
> Error BE0073: A project with a different or higher framework version was found but that version (.NETFramework 4.6) or a suitable redirected version was not found on this system.  The build cannot continue.

I tried to download .NETFramework_4.6.reflection file from repository and put into Data/NETFramework folder, installing SC in NutGet. Still getting error...

**Comment by EWSoftware** [comment]
If you're using the installed version of SHFB, download and install the latest release which contains all of the necessary framework files.

If you're using NuGet to install the packages, make sure you followed the instructions in the package's [Read Me file](https://github.com/EWSoftware/SHFB/blob/master/NuGet/ReadMe.txt) for setting up the SHFB project so that it can find the necessary files.
