### ISSUE TITLE
"AxImp.exe" was not found

### ISSUE THREAD

**Issue by DiskCrasher** [EWSoftware/SHFB#397]
I'm running Windows 7/Visual Studio 2015 and have Windows SDKs installed for 7, 8.1, and 10. During the SHFB build I'm getting the following error:

`[C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe - GenerateRefInfo.proj]
Build started 2/14/2017 10:08:22 AM.
Project "C:\Users\lowerym\Documents\gitRepository\HeatExecutive\Help\Working\GenerateRefInfo.proj" on node 1 (default targets).
Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
PrepareForBuild:
  Creating directory "obj\Debug\".
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(2015,5): error MSB3091: Task failed because "AxImp.exe" was not found, or the correct Microsoft Windows SDK is not installed. The task is looking for "AxImp.exe" in the "bin" subdirectory beneath the location specified in the InstallationFolder value of the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx40Tools-x86. You may be able to solve the problem by doing one of the following:  1) Install the Microsoft Windows SDK.  2) Install Visual Studio 2010.  3) Manually set the above registry key to the correct location.  4) Pass the correct location into the "ToolPath" parameter of the task. [C:\Users\lowerym\Documents\gitRepository\HeatExecutive\Help\Working\GenerateRefInfo.proj]
Done Building Project "C:\Users\lowerym\Documents\gitRepository\HeatExecutive\Help\Working\GenerateRefInfo.proj" (default targets) -- FAILED.`

The registry key noted in the error does not exist on my system. Attempting to create it and point to the location of "AxImp.exe" also did not help.

**Comment by EWSoftware** [comment]
You're using a very old version of MSBuild.  Try using MSBuild 12.0 or 14.0 instead.  You should find them in *%ProgramFiles(x86)\MSBuild*.

**Comment by DiskCrasher** [comment]
How do I tell SHFB which version to use?

**Comment by EWSoftware** [comment]
The stuff you posted above looks like you're building from the command line.  In that case, just specify the appropriate path to MSBuild.exe.  Visual Studio should use the version it's associated with.  The standalone GUI picks the version based on the tools version the SHFB project.  If it's not set to at least "12.0", you can change it by hand in a text editor:

```XML
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

**Comment by DiskCrasher** [comment]
Actually I was building from the GUI. I changed the ToolsVersion from "4.0" to "14.0" and now everything works. (Not sure how it got set to 4.0). Thanks.

**Comment by DiskCrasher** [comment]
Just upgraded to the latest released version of SHFB (2017.5.15.0) and am experiencing this issue again except this time it doesn't seem to be related to the ToolsVersion setting (which is set to "14.0" in my project):

`[C:\Program Files (x86)\MSBuild\14.0\bin\amd64\MSBuild.exe - GenerateRefInfo.proj]
Build started 7/17/2017 10:26:29 AM.
Project "C:\Users\lowerym\Documents\gitRepository\HeatExecutive\Help\Working\GenerateRefInfo.proj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj\Debug\".
C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(2398,5): error MSB3091: Task failed because "AxImp.exe" was not found, or the correct Microsoft Windows SDK is not installed. The task is looking for "AxImp.exe" in the "bin" subdirectory beneath the location specified in the InstallationFolder value of the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6\WinSDK-NetFx40Tools-x86. You may be able to solve the problem by doing one of the following:  1) Install the Microsoft Windows SDK.  2) Install Visual Studio 2010.  3) Manually set the above registry key to the correct location.  4) Pass the correct location into the "ToolPath" parameter of the task. [C:\Users\lowerym\Documents\gitRepository\HeatExecutive\Help\Working\GenerateRefInfo.proj]
Done Building Project "C:\Users\lowerym\Documents\gitRepository\HeatExecutive\Help\Working\GenerateRefInfo.proj" (default targets) -- FAILED.

Build FAILED.
`

Perusing through the Windows registry, I don't see a key at the location specified in the error. Is there a specific version of the Windows SDK that has to be installed, or any other prerequisites?

**Comment by EWSoftware** [comment]
I haven't seen it do that before.  Can you create a small example that duplicates the issue?

**Comment by DiskCrasher** [comment]
Haven't been successful in duplicating it. When I create a new SHFB project for a different solution, it generates the help file successfully. It's only crashing on this particular solution (but wasn't in the previous version of SHFB).

**Comment by EWSoftware** [comment]
Since it seems to be failing when trying to run the intermediate project generated by the build, can you send me the content of the working folder?  I can probably use that to see if I can duplicate the issue.

**Comment by DiskCrasher** [comment]
Unfortunately the software is proprietary and I'm unable to release details about the source code. If there's something I can analyze myself let me know.

**Comment by EWSoftware** [comment]
I don't need the source code or your assemblies, just the content of the working folder.  The most it'll contain from your project is the XML comments files.  Everything else in it is generated by the build.  I just need enough to get it to the MRefBuilder step where it's trying to generate the reflection info and see why it's failing when the intermediate project that runs the process is loaded.

**Comment by DiskCrasher** [comment]
I think I found out what was causing this error (but not sure why). One of my projects had unnecessary references to IWshRuntimeLibrary and also stdole. After removing those references SHFB no longer complained about AxImp.exe. However, I'm now seeing this error:

**SHFB: Error BE0065: BUILD FAILED: The 'p' start tag on line 1241 position 2 does not match the end tag of 'th'. Line 1241, position 92.**

How do I know which file it's referring to?

**Comment by EWSoftware** [comment]
See the last section of the log file prior to the error.  That should give some context as to what was happening when the build failed.  Based on the error it is probably some ill-formed content perhaps in an HTML file that's being included in the project.

**Comment by DiskCrasher** [comment]
No HTML files in this project. Below is the full error, which seems to imply a problem with namespace summaries. Only one summary contains markup and I removed it as a test with no success.

`Generating namespace summary information...
    Last step completed in 00:00:00.7176
-------------------------------

SHFB: Error BE0065: BUILD FAILED: The 'p' start tag on line 1241 position 2 does not match the end tag of 'th'. Line 1241, position 92.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFile.get_Comments()
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFile.get_Members()
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFileCollection.get_ContainsInheritedDocumentation()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
`

**Comment by EWSoftware** [comment]
It's scanning the XML comments files for inherited documentation tags.  If it's not the project or namespace summaries, take a look at the list of XML comments files listed at the start of the build log.  One of them probably has a mismatched end tag or is missing a `</p>`.  Search the XML comments files for `</th>` to see if you can identify the member in question.

**Comment by DiskCrasher** [comment]
Using a process of elimination I was able to determine which project was causing the error. I then looked at XML files under the Working directory and found that System.ValueTuple.xml was the culprit. (System.ValueTuple is referenced by my project.) Is there a way to exclude this reference from SHFB?

**Comment by EWSoftware** [comment]
XML comments from reference assemblies are included automatically so that comments info can be included for anything that derives from types within them.  SHFB can't tell whether or not they'll be used so everything is included.  Since they're XML, the expectation is that they are all well-formed so there are no provisions for excluding them on a case-by-case basis.

Your only option is to fix the original file or delete it so that it isn't found.  I'm assuming it's probably in a NuGet package folder since the ValueTuple comments are in mscorlib.xml for .NET 4.7 and they're okay.  You'll need to file a bug report with the package owner to get them to fix it.  In this case, I guess that would be Microsoft.

**Comment by DiskCrasher** [comment]
Sounds like an opportunity for a new SHFB feature (exclude dependencies) since both of the issues I experienced in this thread were caused by external assemblies that I have no control over.

**Comment by juderb** [comment]
This issue has been closed for some time, but I am running into the same problem after updating from VS2015 to VS2017 and updating to the latest SHFB build. I'll update this thread as I work towards resolving this in case anyone else comes across the same issue.

Generating reflection information...
[C:\Program Files (x86)\MSBuild\14.0\bin\amd64\MSBuild.exe - GenerateRefInfo.proj]
Build started 5/8/2018 12:12:10AM
Project "...\Working\GenerateRefInfo.proj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj\Debug\".
C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(2398,5): error **MSB3091: Task failed because "AxImp.exe" was not found**, or the correct Microsoft Windows SDK is not installed. The task is looking for "AxImp.exe" in the "bin" subdirectory beneath the location specified in the InstallationFolder value of the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6\WinSDK-NetFx40Tools-x86. You may be able to solve the problem by doing one of the following:  1) Install the Microsoft Windows SDK.  2) Install Visual Studio 2010.  3) Manually set the above registry key to the correct location.  4) Pass the correct location into the "ToolPath" parameter of the task. [...\Help\Working\GenerateRefInfo.proj]
Done Building Project "...\Help\Working\GenerateRefInfo.proj" (default targets) -- FAILED.

**Comment by juderb** [comment]
Update:
I removed the repository and pulled down a clean version that I am certain worked on a previous workstation. I was able to successfully build this version. Now, I am concerned that the error occurred because I had updated several NuGet packages. I will update these individually to see if I can replicate the issue.
