### ISSUE TITLE
Handling TODO comments

### ISSUE THREAD

**Issue by feldrim** [EWSoftware/SHFB#398]
I've checked out the documentation but couldn't find out if SHFB handles `// TODO: Refactor foo` comments. So that I can see the things former programmers kept in TODO comments of my legacy code on documentation. It would be nice to handle and present todos in the class. Afterwards in the namespace, addressing the todos and classes wirth line number in a table, then in the project, a collective information table, sorted by namespaces and classes etc.

I'll fork the repo in order to work on this but I'm not sure if I can spend enough time on this, because this legacy code I'm working on takes a lot time of mine.

**Comment by EWSoftware** [comment]
TODO comments by themselves don't get any special handling.  For one, they'd need to be put in a custom XML comments element and the presentation styles would need updating to handle it.  Also, double slash comments aren't included, only triple slash XML comments.  TODOs embedded within the body of a method would never be seen since XML comments are only applied to namespaces, types and members, never within a method body.

Line number info for types and members is included in the reflection data to a certain extent and is used for the View Source link in the topics.  There are [limitations though](http://ewsoftware.github.io/SHFB/html/e6fcfa33-e7ee-430a-abfe-6b7962e6d068.htm#SourceCodeBasePath).
