### ISSUE TITLE
Minimizing Output Using Presentation Styles

### ISSUE THREAD

**Issue by zcollins0** [EWSoftware/SHFB#403]
I am using SHFB for a very large codebase. The HTML documentation exceeds 16GB and 130,000 files. I have been looking through the documentation about presentation styles, and I'm not sure how much control I really have in regards to what it output. 

One thought I had to reduce size of the output was to combine the documentation of methods, properties, etc. with the class page. At a quick glance, do you know if this would be possible?

**Comment by EWSoftware** [comment]
If it's just a matter of too many types and members being documented that you don't want included, the API Filter can help in removing the unwanted stuff.  If you're willing to invest the time in creating a presentation style, you've got full control over how it renders the content.

From the start, the output has been geared towards one topic per member so the transformation that generates the manifest used by BuildAssembler (ReflectionToManifest.xsl) isn't part of the presentation style definition.  However, a presentation style-specific plug-in could be created to override that build step to generate the manifest such that it's limited to namespaces and types.  Your presentation style would then include all the information on the class page rather than rendering one topic per member.

The BuildAssembler.config file used by such a presentation style would likely be significantly different as it would probably have to pull in a lot more information than it currently does for type topics.  I'm not sure what that might look like without investing more time in it.

**Comment by zcollins0** [comment]
Unfortunately, all of it needs to be documented. Thank you for your help!
