### ISSUE TITLE
Support MSBuild Properties in Namespace summaries

### ISSUE THREAD

**Issue by chm-tm** [EWSoftware/SHFB#408]
Consider the use case where there are different flavors of a collection of libraries. All libraries are documented in one help file. Based on the flavor, I want to document some namespaces, but leave out others.

I tried to accomplish this goal by putting MSBuild properties as the value of the `isDocumented` attribute of the `NamespaceSummaryItem` element:
```XML
<NamespaceSummaryItem name="MyNamespace" isDocumented="$(FlavorBool)">
```
This works for the command line, but fails when building inside Visual Studio 2015, since it failed to parse the value as a boolean value.

I have forked SHFB and [committed](https://github.com/chm-tm/SHFB/commit/af4476a6769f39176112367fadf85bf29b23f56b) a change which supports my use case. I didn't want to immediately create a pull request from it since I feel I don't sufficiently understand the use of the `EvaluatedValue` versus `UnevaluatedValue` Properties in the code.

**Comment by EWSoftware** [comment]
Unfortunately, I think this would still break the property page if you went to edit the namespace summaries.  Since ultimately, the property gets converted to an API filter, you may be better off creating a [target override file](http://ewsoftware.github.io/SHFB/html/8ffc0d37-0215-4609-b6f8-dba53a6c5063.htm#TargetOverrides) that contains API filters based on the flavor.  Note that this still wouldn't be supported within Visual Studio since it doesn't really handle conditional properties like this besides those tied to the configuration setting (Debug or Release).  However, SHFB doesn't look at the configuration when it comes to its project properties.
