### ISSUE TITLE
Can't open Open XML (docx) document

### ISSUE THREAD

**Issue by parfant** [EWSoftware/SHFB#412]
Hello,

I have created an Open XML (docx) document with the presentation style Open XML Document.
When I open the document with Microsoft Word 2010, an error message is shown:

> The file xxx.docx cannot be opened because there are problems with the Contents.
> Details:
> Unspecified error
> Location: Part: /word/document.xml, Line: 3, Column: 0

The help file formats HTML Help 1 (chm) and MS Help Viewer (mshc) can be opened without problems.

Any idea what is going wrong?

Manuel

**Comment by EWSoftware** [comment]
See the [Open XML Format topic](http://ewsoftware.github.io/SHFB/html/c5e7e920-2cb4-4f78-b167-634361d85263.htm) for common problems and how to fix them.  The Open XML format is very unforgiving of ill-formed content.  The topic contains some tips on finding the cause of the corruption so that you can fix it.
