### ISSUE TITLE
TOC link disappear when clicked

### ISSUE THREAD

**Issue by MaxThom** [EWSoftware/SHFB#414]
I just started playing with SHFB and I have this issue (only on VS2013 website).
When I click a link in the TOC all the other disappear.

![image](https://cloud.githubusercontent.com/assets/26239574/23779790/8c21f400-0510-11e7-9ba2-95b376ff4223.png)

![image](https://cloud.githubusercontent.com/assets/26239574/23779796/9533148e-0510-11e7-8c76-8df7709d3d71.png)

Any idea on how to fix this ?

**Comment by EWSoftware** [comment]
I believe that's an old issue that has been fixed as I seem to recall it and cannot duplicate now with the latest release.  If you aren't using the latest release, please upgrade to it.  If you are, can you supply me with an example that duplicates the issue?

**Comment by MaxThom** [comment]
I'm using the SHFBInstaller_v20171.28.0 version. 
I have a project in my git with the issue (Arithmetic Tree). 
[https://github.com/MaxThom/ArithmeticTree](url)

**Comment by EWSoftware** [comment]
I tested your example and it works fine when running using the local web server.  If ran using the file system option, it does exhibit the behavior you are seeing and I do see that's what you are doing in the screen shots.

If you use the local web server or upload it to a remote one and view the content, you'll get the expected behavior.  The local file system blocks some of the scripts from running hence it doesn't handle the node expansion as it should.

Note that in the current release, if you've only got IIS Express installed it may not let you use the local web server option.  That's fixed for the next release.
