### ISSUE TITLE
<autoOutline/> was "fixed" to be inconsistent with MSDN

### ISSUE THREAD

**Issue by Millerni456** [EWSoftware/SHFB#42]
It seems like the issue was posted before, except the issue was to change the output of the <autoOutline/> to be inconsistent with MSDN pages:
https://sandcastle.codeplex.com/workitem/2950

Take a look at this MSDN page for example:
https://msdn.microsoft.com/en-us/library/ms743643(v=vs.110).aspx

In the outline, it includes "Related Topics", not "See Also".

It would be nice if "Related Topics" was displayed..

**Comment by EWSoftware** [comment]
It's a matter of opinion as to which is inconsistent.  The thread referenced in the old work item is long since gone but general consensus was that the link text should match the section title just like all the other links thus it was changed to be "See Also".

Since it's been that way for 6+ years, I'm not inclined to change it back since then I'd probably get someone saying to put it back the other way.  Personally, I don't like seeing the See Also/Related Topics link in the outline so I add the `excludeRelatedTopics="true"` attribute to hide it.  If you'd prefer the old text, you can add a [Resource Items file](http://ewsoftware.github.io/SHFB/html/fcf8e4ac-5b32-4d5f-9bce-2e85c3468fdc.htm) to the project, locate the *RelatedTopicsLinkText* or *title_relatedTopics* item depending on the presentation style and change it there.

**Comment by Millerni456** [comment]
Ah, didn't realize it was decided to be that way.  Yes I noticed it was
consistent with the section title.

Thanks for the reply and help! :)

On Friday, March 20, 2015, Eric Woodruff <notifications@github.com> wrote:

> It's a matter of opinion as to which is inconsistent. The thread
> referenced in the old work item is long since gone but general consensus
> was that the link text should match the section title just like all the
> other links thus it was changed to be "See Also".
>
> Since it's been that way for 6+ years, I'm not inclined to change it back
> since then I'd probably get someone saying to put it back the other way.
> Personally, I don't like seeing the See Also/Related Topics link in the
> outline so I add the excludeRelatedTopics="true" attribute to hide it. If
> you'd prefer the old text, you can add a Resource Items file
> <http://ewsoftware.github.io/SHFB/html/fcf8e4ac-5b32-4d5f-9bce-2e85c3468fdc.htm>
> to the project, locate the *RelatedTopicsLinkText* or
> *title_relatedTopics* item depending on the presentation style and change
> it there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EWSoftware/SHFB/issues/42#issuecomment-84110600>.
>


-- 
Nicholas Miller
(248) 880-4777
Mill1453@Kettering.edu
