### ISSUE TITLE
File handling in SHFB on change of name in Project Explorer or content outside

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#424]
I observed two problems with functionality normally expected for an file based text editing GUI:

a)
If I rename a file in the SHFB "_[Project Explorer](http://ewsoftware.github.io/SHFB/html/e12c2b9f-18c7-4718-850b-ac3c2e293672.htm)_" then file name in the topics/content layout will not be changed? This leads into two steps, renaming in "_[Project Explorer](http://ewsoftware.github.io/SHFB/html/e12c2b9f-18c7-4718-850b-ac3c2e293672.htm)_" and then reload the file at the "_Topic Filename_" setting in "_[Content Layout File Editor](http://ewsoftware.github.io/SHFB/html/54e3dc97-5125-441e-8e84-7f9303e95f26.htm)_".

b)
If I edit the content of file outside of SHFB GUI (f.i. in VS) while file is still open in SHFB - it has still the old content after I saved file in extern editor. Other editors detect outside changes and query an reload after detection, like the editors in VS or Notepad++.

**Comment by EWSoftware** [comment]
The topics in the content layout file are associated by ID rather than by filename.  This is intentional as it allows changing the name of the file or its containing folder or moving them around without the fear of breaking the content layout file.

If the content layout file is open in the editor when you rename or move a file it will be unaware of the change.  However, clicking the Refresh button to the far right of the topic filename in the content layout editor will force it to refresh and go find the related file again as will closing and re-opening the content layout editor window.  It's really not much of an issue unless you try to open the file from the editor.  If you did a build, it would work since, again, it's associating by ID and not the filename.  Where you would run into an issue is if you changed the unique ID of the topic.  Then you would have to re-associate the topic file with the topic entry in the content layout file.

The standalone GUI goes have a file system watcher.  If you edit an open file outside the GUI and then switch back it should prompt you to see if you want it reloaded it as long as those files are within the current project's folder.

The standalone GUI predates the Visual Studio package and is now provided simply as a convenience for those that don't have access to a supported version of Visual Studio.  It'll get the job done but I don't intend to spend lots of time making it something that can compete with Visual Studio feature-wise in all aspects.

I don't know if it's an option for you but there are [Community Editions](https://www.visualstudio.com/vs/community/) of Visual Studio available now which are full-featured versions of Visual Studio that do allow installation of third-party packages like SHFB unlike their older Express Edition counterparts.

**Comment by VBWebprofi** [comment]
I can understand that the GUID of the file is more reliable for all processes around build tec. But for humans - I don't want search every time for the right GUID of a file and then open it or do somethings else. For this a clear meanful file name best. But I can live with the manual "Refresh"ing after renaming the file.

I know the editions, currently using VS2010 Professional and can use also VS2015, but found no SHFB package.

Don't much us the file content file editor in case of missing functionality I have with the VS XML editor. There I missing the right tag support in case of incorrect XML schema files, see issue #418. But may I can solved this also.
