### ISSUE TITLE
Create and improve of German translation

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#447]
Hello Eric,

I want continue with German translations and scanned the project source for that. Going along the Russian translations brought me following list for German:

```
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\AspNet.xml
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\CSharp.xml
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\FSharp.xml
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\JScript.xml
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\JSharp.xml
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\JavaScript.xml
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\ManagedCPlusPlus.xml
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\VisualBasic.xml
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\VisualBasicUsage.xml
BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\XAML.xml
PresentationStyles\Markdown\Content\de-DE\ConceptualContent.xml
PresentationStyles\Markdown\Content\de-DE\ReferenceContent.xml
PresentationStyles\Markdown\Content\de-DE\SharedContent.xml
PresentationStyles\Markdown\SHFBContent\de-DE.xml
PresentationStyles\OpenXml\Content\de-DE\ConceptualContent.xml
PresentationStyles\OpenXml\Content\de-DE\ReferenceContent.xml
PresentationStyles\OpenXml\Content\de-DE\SharedContent.xml
PresentationStyles\OpenXml\SHFBContent\de-DE.xml
PresentationStyles\Shared\StopWordList\de-DE.txt
PresentationStyles\VS2010\Content\de-DE\conceptual_content.xml
PresentationStyles\VS2010\Content\de-DE\reference_content.xml
PresentationStyles\VS2010\Content\de-DE\shared_content.xml
PresentationStyles\VS2010\Content\de-DE\shared_content_mshc.xml
PresentationStyles\VS2010\SHFBContent\de-DE.xml
PresentationStyles\VS2013\Content\de-DE\conceptual_content.xml
PresentationStyles\VS2013\Content\de-DE\reference_content.xml
PresentationStyles\VS2013\Content\de-DE\shared_content.xml
PresentationStyles\VS2013\Content\de-DE\shared_content_mshc.xml
PresentationStyles\VS2013\SHFBContent\de-DE.xml
```

Is there something missing or something I should know else?

**Comment by EWSoftware** [comment]
There's a general topic on [localizing the resource files](http://ewsoftware.github.io/SHFB/html/e2ed6222-c3ee-4c6e-b0f9-fa3c86bc3e2c.htm).  In short, there's a .\Content folder in each presentation style and the .\SyntaxContent folder for the syntax components.  The root contains the English resource files.  To translate them, create a folder named after the language, copy the English resource files into it, and translate each of the elements within them.

There's also a .\SHFBContent folder in each presentation style.  The files in this folder are named after the language and represent a set of SHFB-specific item overrides.  To create a new language there, you copy the en-US.xml file to a new file with the language ID and translate the elements as usual.  The stop word lists in .\PresentationStyles\Shared\StopWordList are handled in a similar fashion.

**Comment by VBWebprofi** [comment]
Where can I find a documentation with used translations of the section "_XAML section headings_" of "BuildAssembler\SyntaxComponents\SyntaxContent\de-DE\XAML.xml"? or can you provide a picture of such?

**Comment by EWSoftware** [comment]
You'd need an assembly containing some XAML controls and/or forms.  You can probably use the SHFB assembly SandcastleBuilder.WPF.dll as a test though I'm not sure how much you'd actually get since it may not cover all the cases.  You'd need to add a [XAML syntax configuration file](http://ewsoftware.github.io/SHFB/html/c38461a6-6edd-42cf-9d91-73c4b11cdd70.htm#XamlConfiguration) to the project as well to define the namespaces in it so that they are included and get the XAML syntax stuff.

Item IDs are unique within each set of files but are common across all translations.  So, for example, you'll see an entry for `UnsupportedOperator_CSharp` in each C#-related language resource file.

**Comment by VBWebprofi** [comment]
Are they (all/nearly) equal across all PresentationStyles?

**Comment by EWSoftware** [comment]
For the syntax content, yes since they are shared amongst all presentation styles.  For presentation styles, as far as the IDs go, I think so.  As far as content, the text will most likely be identical.  The only variation may be in formatting.  For example, the Open XML and Markdown presentation styles won't contain HTML markup.  They'll contain the equivalent Open XMl and markdown markup with a few exceptions that get handled in post-processing like `span` elements that apply keyword formatting.
