### ISSUE TITLE
Occasional Extra Spacing In Generated Document For Generic Types...

### ISSUE THREAD

**Issue by jrichmeier** [EWSoftware/SHFB#451]
Suppose I have a type that has two generic type parameters, say something like MyClass<TKey, TValue>.

If I document using:

    <summary><see cref="MyClass{TKey, TValue} /></summary>

The summary is generated correctly as "MyClass<TKey, TValue>"

If I document using:

    <summary>XXX <see cref="MyClass{TKey, TValue} /></summary>

The summary is generated correctly as "XXX MyClass<Tkey, TValue>"

If I document using:

    <summary><see cref="MyClass{TKey, TValue} /> XXX</summary>

The summary is generated incorrectly as "MyClass< TKey, TValue>  XXX" (notice the extra space after < and the two spaces before XXX).

This appears to be an issue when text follows the <see> tag.  Specifically, this appears to be an issue when a space is added after the <see> tag.  If I add something like a period right after the <see> tag with no leading space the output is generated correctly.  Also, this does not seem to occur if the generated output is OpenXML but does if the generated output is CHM or HTML.

**Comment by EWSoftware** [comment]
There's script to work around an issue in certain browser versions for Help 1 and MS Help Viewer that adds an extra space to prevent the language-specific text elements from running together with any subsequent text.  As currently written, it does it for the leading and trailing language-specific text.  I can adjust it so that it only inserts the space on the trailing language-specific text if it's a closing angle bracket or parentheses.
