### ISSUE TITLE
Error when attempting to create new project from GUI

### ISSUE THREAD

**Issue by whiggs** [EWSoftware/SHFB#453]
When attempting to create a new project from the GUI based application (not visual studio), when I try to save the project to "Documents" only (it works everywhere else for some reason), I get the following errors.  I have the latest build of Windows 10 x64 Pro, the Creators Update.  Also, despite what the error message says, yes I am attempting to save the project to "Documents".  Not sure how "My Music" got in there.
![snipaste20170410_165458](https://cloud.githubusercontent.com/assets/11139575/24882359/c83f89d6-1e0e-11e7-93ba-b1ab830838e9.png)
![snipaste20170410_165506](https://cloud.githubusercontent.com/assets/11139575/24882358/c83f732e-1e0e-11e7-8f68-097e154531ae.png)
![snipaste20170410_165446](https://cloud.githubusercontent.com/assets/11139575/24882357/c83e820c-1e0e-11e7-9c3d-52384dfe4c47.png)

**Comment by EWSoftware** [comment]
When a SHFB project is opened, a search is made of the project folder and its sub-folders for components such as plug-ins, presentation styles, etc.  Move the SHFB project to a subfolder under My Documents rather than placing it directly in My Documents.  That way, it only searches the project folder rather than everything under My Documents.

**Comment by whiggs** [comment]
Well I knew that it worked in other folders (as I stated as such in original post), but fail to see how "documents" is any different from "Desktop" or the root of a drive in terms of the folder sit needs to search.  The purpose of reporting the issue was to potentially resolve, not workaround.

**Comment by EWSoftware** [comment]
It's not a workaround, it's by design.  The SHFB project folder and it's subfolders are searched for components that can be used during the build.  If you put the project in the root My Documents folder, it's going to search all the subfolders under it.

A SHFB project is just like any other Visual Studio project and can have content files added to it.  I wouldn't create a C# project in My Documents without placing it in a subfolder by itself since I don't want all the C# source files in the root My Documents folder.  A SHFB project is no different.
