### ISSUE TITLE
Possibility to merge helpfile indexes? and reference in other helpfile?

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#454]
Is there any possibility to merge helpfile indexes into one of all? Second question is there any possibility to reference an API documentation in an other helpfile?

**Comment by EWSoftware** [comment]
For MS Help Viewer (MSHC) files, such support is automatic since the help files are merged into a common catalog.  You can use the Additional Reference Links plug-in to generate the link information for other assemblies that appear in help files that are going to be in the same help viewer catalog.

For Help 1 (CHM) files, I think there are tools that may be able to merge help files but there's no support in SHFB for merging them nor creating links to topics in other Help 1 files.

For websites, there are no provisions for merging content or linking between sites.  I have some plans to support this in the future but nothing definite on when that might occur.
