### ISSUE TITLE
The <inheritdoc> tag does not seem to work for overloads.

### ISSUE THREAD

**Issue by alekdavis** [EWSoftware/SHFB#457]
I'm trying to follow the instructions at http://tunnelvisionlabs.github.io/SHFB/docs-master/SandcastleBuilder/html/79897974-ffc9-4b84-91a5-e50c66a0221d.htm to inherit overloads for a method, but it does not seem to be working. The overloads tag does work for the original method, but when I reference it using the following format, the overloads summary does not appear in the help file. 

Here is the code that works (with duplicate overloads):

ILogger class:

```
#pragma warning disable 1573
/// <inheritdoc cref="Write(LogLevel,object,Exception,string,string,int)" select="param|remarks"/> 
/// <summary>
/// Converts the specified <paramref name="message"/> to a string
/// and writes it along with an exception to the log as a debug message.
/// </summary>
/// <overloads>
/// Writes a debug record to the log.
/// </overloads>
#pragma warning restore 1573
void Debug
(
	object		message, 
	Exception	ex,
	[CallerMemberName]
	string		callerMemberName	= "", 
	[CallerFilePath]
	string		callerFilePath		= "", 
	[CallerLineNumber]
	int		callerLineNumber	= 0
);

#pragma warning disable 1573 
/// <inheritdoc cref="Write(LogLevel,string,Exception,string,string,int)" select="param|remarks"/> 
/// <summary>
/// Converts the specified <paramref name="message"/> to a string
/// and writes it along with an exception to the log.
/// </summary>
void Write
(
	LogLevel	logLevel, 
	object		message, 
	Exception	ex, 
	[CallerMemberName]	
	string		callerMemberName	= "", 
	[CallerFilePath]	
	string		callerFilePath		= "", 
	[CallerLineNumber]	
	int		callerLineNumber	= 0
);
#pragma warning restore 1573
```
In LogWrapper class:
```
#pragma warning disable 1573
/// <inheritdoc cref="BasicLogging.ILogger.Debug(object,Exception,string,string,int)" select="summary|param|remarks"/> 
/// <overloads>
/// Writes a debug record to the log.
/// </overloads>
#pragma warning restore 1573
public void Debug
(
	object		message, 
	Exception	ex, 
	[CallerMemberName]
	string		callerMemberName	= "", 
	[CallerFilePath]
	string		callerFilePath		= "", 
	[CallerLineNumber]
	int		callerLineNumber	= 0
)
{
	//...
}
```
If I change the LogWrapper's XML comment to the following, it does not work (I do not see the overloads description for the LogWrapper's Debug class:
```
#pragma warning disable 1573
/// <inheritdoc cref="BasicLogging.ILogger.Debug(object,Exception,string,string,int)" select="summary|param|remarks|overloads/*"/> 
#pragma warning restore 1573
public void Debug
(
	object		message, 
	Exception	ex, 
	[CallerMemberName]
	string		callerMemberName	= "", 
	[CallerFilePath]
	string		callerFilePath		= "", 
	[CallerLineNumber]
	int		callerLineNumber	= 0
)
```
Maybe I'm not doing it correctly, but I think I follow the example provided in the documentation (although, I could not find what `overloads/*` actually means).

**Comment by EWSoftware** [comment]
An [overloads element](http://ewsoftware.github.io/XMLCommentsGuide/html/5b11b235-2b6c-4dfc-86b0-2e7dd98f2716.htm) can contain other things besides a simple description.  It may contain other elements such as summary, remarks, examples, etc.  As such, it is never inherited when it appears at the root level to prevent doubling of the comments on the overloads page.

The example in the help topic is showing how to inherit the content of the element (`overloads/*`), not the element itself.  Take a look at the target method inherited from in the example and you'll see that it contains a summary and a remarks element within the overloads element.  In your case, all you're inheriting is some plain text.  Since there are no elements in it, it doesn't render anything since it's just superfluous text outside of all the other elements.

What you need to do is nest an `inheritdoc` element within an `overloads` element on the method so that it inherits the text properly.  When nested, it inherits from the parent element, in this case, the `overloads` element.  Since the text will then appear within an `overloads` element, it will get rendered.  For example:

``` C#
/// <inheritdoc /> 
/// 
/// <overloads>
/// The inheritdoc element outside this "overloads" element inherits the standard summary,
/// parameters, remarks, etc. for the member itself.
/// 
/// The inheritdoc element below will inherit the overload text from the implemented member
/// and it will appear on the overloads page:
/// 
/// <inheritdoc /> 
/// 
/// </overloads>
```

Since the member ID matches the base, there's no need to specify the `cref` attribute.

**Comment by alekdavis** [comment]
Oh, awesome!!! Thanks a lot, Eric. It makes more sense now.

If anyone has a similar issue, the only change for my example I had to do was this: 

```
#pragma warning disable 1573
/// <inheritdoc cref="BasicLogging.ILogger.Debug(object,Exception,string,string,int)" select="summary|param|remarks"/> 
/// <overloads>
/// <inheritdoc/>
/// </overloads>
#pragma warning restore 1573
public void Debug
(
	object		message, 
	Exception	ex, 
	[CallerMemberName]
	string		callerMemberName	= "", 
	[CallerFilePath]
	string		callerFilePath		= "", 
	[CallerLineNumber]
	int		callerLineNumber	= 0
)
```
It also works with `cref` (if the method needed to be inherited from some other member and not via direct inheritance:

```
/// <inheritdoc cref="BasicLogging.ILogger.Debug(object,Exception,string,string,int)" select="summary|param|remarks"/> 
/// <overloads>
/// <inheritdoc cref="BasicLogging.ILogger.Debug(object,Exception,string,string,int)" />
/// </overloads>
```
