### ISSUE TITLE
Building help documentation from MSBuild and VSTS

### ISSUE THREAD

**Issue by vonlar** [EWSoftware/SHFB#461]
I've added a documentation project to my solution.  In the proj file I've added the following code, but how do I tell the proj to build the documentation who's files are in a different folder?  Also what are these other SHFB project properties?
```  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <SHFBROOT Condition=" '$(SHFBROOT)' == '' ">$(SolutionDir)\packages\EWSoftware.SHFB.2017.1.28.0\Tools\</SHFBROOT>
    ... other SHFB project properties ...
  </PropertyGroup>
```

**Comment by EWSoftware** [comment]
You add documentation sources to the SHFB project to tell it what to document.  I'd suggest working through the [Getting Started topics](http://ewsoftware.github.io/SHFB/html/b772e00e-1705-4062-adb6-774826ce6700.htm) to get familiar with how to use SHFB.

See the [Visual Studio Integration Package topic](http://ewsoftware.github.io/SHFB/html/b128ad2a-787e-48c7-b946-f6953080c386.htm) for information on working with SHFB projects in Visual Studio.

Refer to the [Project Property Window topics](http://ewsoftware.github.io/SHFB/html/e32086c6-de17-4e54-a746-1ac80bf0c45a.htm) for information on the various project property categories and their properties.

**Comment by vonlar** [comment]
Thank you for the response.  However I may not have made my question and issue very clear.

I've added an SHFB project via the VSIX tool to my solution called "Linker API".  However the documentation being created is for a project within the solution called "Linker".  The code I mentioned above, I put in the Linker project file.  I need the build server to build the documentation, every time it builds the Linker project.

The documentation isn't very clear on how to structure the SHFB files so it works with the nuget packages for a hosted build server.  (I'm using a VSTS hosted build server with no installation rights)

Thanks for all the work you've done on this project and for your help!  By chance are you a Microsoft MVP?  If not, I'd be happy to nominate you, as I am one myself.

**Comment by EWSoftware** [comment]
The SHFBROOT property should go in the SHFB project file itself.  That will let it find the tools when it is built.  Any other project in the solution that's being used as a documentation source by the SHFB project doesn't require any changes.  SHFB project don't do any incremental builds or "up-to-date" checks so they should build every time the solution is built unless specifically excluded through the configuration settings.

Typically, within Visual Studio, you can right click on the root solution node and use the Project Dependencies option to set the dependencies so that things build in the right order.  However, I've been told that MSBuild and build servers don't always honor those settings in the solution file.

To ensure that the Linker project is built before the SHFB project, you can add it as a project reference to the SHFB project.  It will already appear as a documentation source but add it to the **References** node of the SHFB project as well.

Once added, select the project reference and set the `ReferenceOutputAssembly` property to False.  This makes SHFB ignore it when determining reference assemblies to include but MSBuild will use it to determine build order dependencies.  Since the SHFB project uses the Linker project as a reference, it will be built after the Linker project has been built.  Hopefully that all makes sense.

I'm not an MVP so thanks for the offer.

**Comment by sunefred** [comment]
I would assume you need a VSTS extension for Sandcastle to run on hosted build agent (this does not exist). Or you can run your build on a custom build agent with SHFB installed.

Please prove me wrong, I would love to be able generate documentation as part of my CI build on VSTS.

**Comment by vonlar** [comment]
@EWSoftware How does one add the NuGet package to the SHFB project?  Or it just needs to get added to any project, so that the SHFB project has access to the package?  On the MVP front, can you contact me via email?  The domain for my email is harvestdatacorp.com and then you can reach me at randy.walker.  I need to know how many hours you spend on open source projects including this one.

@sunefred I'm workin on it! ;)

**Comment by EWSoftware** [comment]
@sunefred: To use SHFB on a build server, use the [NuGet packages](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm).

@vonlar: At some point in the past, I think it was possible to install the NuGet package in the SHFB project but that no longer appears to be the case at least not since VS 2015.  As long as you add the main package and the related reflection data package to one of the documentation source projects within the same solution, the SHFBROOT property you add to the SHFB project will let it find the tools.

I don't have access to a build server so I can only do simple testing locally with the NuGet packages.  I know other people have done it but I haven't had any feedback on improving the instructions for getting it to work. If you want to give me some more info on how you get it working, I can use it to update the help topic.

**Comment by vonlar** [comment]
@EWSoftware Ok getting the following error at the build server ...

Unable to parse value ' ..\packages ' for property 'ComponentPath' ---> SandcastleBuilder.Utils.BuilderException: Unable to parse value ' ..\packages ' for property 'ComponentPath' ---> System.ArgumentException: Illegal characters in path. at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) at System.IO.Path.IsPathRooted(String path) at SandcastleBuilder.Utils.SandcastleProject.SetLocalProperty(ProjectProperty msBuildProperty, String value)

Btw, you can get a free build server at both VSTS (https://www.visualstudio.com/team-services/) and at AppVeyor because it's an OSS (https://ci.appveyor.com/signup/free).  AppVeyor is the preferred service by most OSS projects.  However if you want help with VSTS I have plenty of experience there.

**Comment by EWSoftware** [comment]
If the value is literally as given, it looks like there are spaces or some other characters on either end of the value.  Perhaps it's having issues with them?

**Comment by vonlar** [comment]
![image](https://cloud.githubusercontent.com/assets/19557417/26411922/c8f74b4a-406c-11e7-8553-1c6dd4b0d72d.png)
Woop woop!  Now to get it to deploy the contents!

**Comment by vonlar** [comment]
@EWSoftware Sorry, one more question, I have everything building and deploying (CI/CD).  Is there a way to specify what goes into the web.config file that gets generated?  I need a couple of extra lines added to it.

**Comment by EWSoftware** [comment]
Add a copy to the root of the SHFB project and make the required changes.  Make sure its Build Action is set to Content.  When built, it'll get copied to the output folder and will override the standard one for the presentation style.

**Comment by EWSoftware** [comment]
I looks like you got everything working so I'm closing this for now.  If you have any suggestions on improvements to the documentation with regard to getting this working, feel free to submit them.
