### ISSUE TITLE
Resolving " Unknown reference link" problems

### ISSUE THREAD

**Issue by green4don** [EWSoftware/SHFB#483]
There are going to be " Unknown reference link" problems with most Sandcastle builds that need to be found and resolved. They fall into (at least) two categories. The first are references to external assemblies and the "Additional Reference Links" plug-in can deal with that. The second are references to internal components that are malformed or problematic.

It seems to me that, in the past, I was able to double click on these errors (somewhere, somehow) and be taken to the offending code. I can't find a way to do this anymore so either my memory is faulty or things have changed. This issue is thus more of education than a bug.

I have previously been working with VS2013 and an older version of Sandcastle. I am now working with VS2017 (V15.2) and the newest Sandcastle (V2017.5.15.0).

Not to muddy the waters, but a similar challenge occurs with missing XML comments in the code which generates warnings on the build. I have to find these errors manually when I used to be able (I'm pretty sure) to just click on them and fix the issue.

Help please!

Thanks.

**Comment by EWSoftware** [comment]
The SHFB project doesn't have a direct connection to any of its documentation sources so warnings about unresolved reference links and missing comments won't do anything if clicked within the Visual Studio Build output or Error List tool windows.  That's always been the case.  If the link in question is in a MAML topic, you can copy the MAML topic ID to the clipboard and paste it into the Find text box in the content layout editor to find the matching topic.  There isn't an equivalent for such warnings in API members.

If the compiler is generating warnings about missing XML comments (i.e. CS1591 from the C# compiler), those can be double-clicked in either the Build output tool window or Error List tool window to go to the member with the missing comments.  There are also keyboard shortcuts for the View.NextError and View.PreviousError commands that can navigate between errors and warnings in the build output.  What they're bound to will vary based on your environment settings.

Note that the compiler warnings may not be the same as the missing comments warnings in SHFB.  If you add an empty comment to a member (i.e. `/// <summary></summary>`) that will satisfy the compiler and you won't see a "missing XML comments" warning but you will still see a "missing comments" warning from SHFB because it's empty.

**Comment by green4don** [comment]
I do not get (or no longer get) any compiler warnings on missing XML comments when building my project. Is there some option that needs to be enabled to show this level of warning?

**Comment by EWSoftware** [comment]
Have you checked to ensure that the XML Comments File output option is enabled in the project?  Also make sure it's enabled in all configurations (i.e. Debug and Release).

**Comment by green4don** [comment]
Yes, all on, the help file builds there's just no warnings about missing XML. I'm pretty sure there used to be, so no real idea, but I thought I enabled this somewhere in some configuration. Anyways, thanks for your help.
