### ISSUE TITLE
Adding Conceptual Content

### ISSUE THREAD

**Issue by qnw2** [EWSoftware/SHFB#485]
I'm trying to add conceptual content to my help page, but I keep getting an error in the build engine. When I use the template for conceptual content (and don't change it in any way) and add that file to my content layout file, I get the following error in my build output:
![capture](https://user-images.githubusercontent.com/29742431/27615576-099f3016-5b5e-11e7-9066-c0a76ff418f4.PNG)
My content layout and conceptual files are as follows:
![capture](https://user-images.githubusercontent.com/29742431/27615598-4714607e-5b5e-11e7-9c04-899bccb02451.PNG)
[Conceptual.txt](https://github.com/EWSoftware/SHFB/files/1107223/Conceptual.txt)
(I changed the file from Conceptual.aml to Conceptual.aml for uploading purposes)

**Comment by EWSoftware** [comment]
It's not the new topic that's causing the issue.  It's either a setting in the content layout file such as a title or keyword, some text in another topic, or more likely in this case a project property value such as Help File Version.  The text in question is matching the format for keyword replacement.  In this case `{@Major}`.  Since that doesn't exist in the project as a property or as a known keyword, it's failing.

Since it looks like it's trying to resolve a version number, I'd check the SHFB project's Help File Version property first.  You've most likely copied it from an example or some other project and because the substituted values don't exist in this project, it's not finding them.  To fix it, either remove the invalid substitution tag references or use the User Defined SHFB project category to define the related properties.

**Comment by qnw2** [comment]
Thank you! You were correct that it was the Help File Version property.
