### ISSUE TITLE
Showing Method Dependencies 

### ISSUE THREAD

**Issue by kellyjmartens** [EWSoftware/SHFB#489]
I was told by a person more knowledgeable then me about Sandcastle that when trying to show dependencies within the remarks tags that I am not doing it correctly and there was an easier way. Basically I got the url by going to a previous build of the help file,got the url for the method and pasted it in the XML line. Of course said person hasn't responded to my question so I thought I would ask you all. Thanks for your time and any suggestions you might give are appreciated.

`''' <remarks>
    ''' <para><b>Dependencies</b></para> 
   ''' <para><a href="ms-its:C:\FilePath\ProjectName_Documentation.chm::/html/f1afd62e-365c-848d-cef2-6e3e896a8645.htm">Method_Name(String, String, String, String, String, String, String, String) (ProjectName.ProjectClass)</a></para>
''' </remarks>
`

**Comment by EWSoftware** [comment]
If the intent is to reference members from prior versions that may no longer be in the current release, you can use the [Version Builder Plug-In](http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm) to merge the information from multiple versions of an assembly into a single help file.  Each API member gets a Versions section that indicates in which versions the member appears.

Standard `<see cref="XXX"/>` references still wouldn't work if the member isn't in the current release since the compiler wouldn't be able to resolve it.  However, you should be able to use the `<see href="ID.htm" />` form which uses the member ID from the same help file as the topic linking to it.

**Comment by kellyjmartens** [comment]
Maybe a picture best explains it. My friend seemed to indicate there was out of the box functionality within Sandcastle to show what the method I am documenting is touching. In the past I used Call Hierarchy in Visual Studio and copy and pasted it in the documentation. Doing this was so helpful in developing testing plans. But if there is that functionality in Sandcastle of course I will change and use it. Just let me know how to do that. Thank you for replying.

![untitled](https://user-images.githubusercontent.com/11928858/28336408-d296818c-6bcf-11e7-8662-f965136ece64.jpg)

**Comment by EWSoftware** [comment]
Unless someone developed a plug-in or build component that did it, there's no such functionality in the Sandcastle tools by default.  The MRefBuilder tool which outputs the reflection data only analyzes the members of the class and the inheritance hierarchy.  There's nothing in place that would analyze the actual code content to see what members are called by any particular method.  I think it does have access to the bytecode so it's possible it could be done though I don't have a good idea of how to go about it.

Perhaps your friend is confusing what you are trying to do with the object hierarchy that does appear on the type pages.
