### ISSUE TITLE
html navigation option to keep navigation visible

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#496]
With the out-of-the-box HTML navigation, when a child topic is selected, all the other visible top level topics are hidden except those that are parents of the selected topic.  Is there a way to keep topics which aren't parents of selected topic visible?

E.g.,

Before selecting topic outlined in red, topics in green are visible:
![before selection is made](https://i.imgur.com/Pd2hKNU.png)

After selecting topic outlined in red, topics in green are no longer visible:
![after selection is made](https://i.imgur.com/u4VFMQk.png)

Thanks in advance for any tips or suggestions,
Glenn

**Comment by EWSoftware** [comment]
No, not as currently implemented.  To see them, the other nodes need to be expanded manually.  It's modeled after how MSDN used to work and sort of still does though it appears to show some surrounding topics in a few cases now.

**Comment by glenncarr** [comment]
Thanks.

**Comment by JohannesDeml** [comment]
Sorry for reviving this issue. I actually had the same thought. For the documentation I'm creating it is not necessary at all to hide elements the are not in the parent structure of the viewed item, it actually makes the documentation less useable (only the website version of course. The HTML Help1 is great!).

How hard do you think it is to implement a toggle to enable hiding elements in the list. As of now I think MSDN also went away from that approach. The documentation I try to mimic because I really like its UX is the one form Unity3D (https://docs.unity3d.com/ScriptReference/index.html).
