### ISSUE TITLE
Apache 2 Issue for Website with icons directory

### ISSUE THREAD

**Issue by Ggs-HoRuS** [EWSoftware/SHFB#497]
Hello,

Under debian, Apache2 has an alias named "icons" pointing to "/usr/share/apache2/icons" which makes your icons directory inaccessible when using the Website format.
Would you be able to change the name of your "icons" directory in order to make the website compatible with Apache2?

Thank you.

**Comment by EWSoftware** [comment]
The *./icons* folder has been that way for over 10 years.  Changing it would require changing the presentation styles and since it's been that way for so long I'd consider it a breaking change since it may affect existing projects that contain additional files that get copied into that folder.

If it's a problem for your installation, I suggest adding a resource items file to your project and overriding the shared content item `iconPath` with the alternate path that you want to use.  You'll also need to add the existing image files from the presentation style to a folder in your project under the new name as Content items so that they get copied to the proper location.  That should resolve the issue without having to change the presentation styles for everyone.

**Comment by Ggs-HoRuS** [comment]
Ok,
