### ISSUE TITLE
Use HTTPS links instead of HTTP

### ISSUE THREAD

**Issue by franklinyu** [EWSoftware/SHFB#503]
Currently the HTML output links to Microsoft documentation as HTTP links, such as http://msdn2.microsoft.com/en-us/library/e5kfa45b. HTTPS links like https://msdn.microsoft.com/en-us/library/e5kfa45b is preferred. I think it is just [here](https://github.com/EWSoftware/SHFB/blob/8103f7f43bb59f18677e6d90a9a276ee4aab2a38/SHFB/Source/BuildAssembler/BuildComponents/MsdnResolver.cs#L242) but not sure; if so I can make pull request.

There are actually a lot of HTTP links here. Most (if not all) of them can be replaced with HTTPS ones.

**Comment by EWSoftware** [comment]
Does it really matter?

**Comment by franklinyu** [comment]
Not really. I thought someone would care.

**Comment by harsheel87** [comment]
I have been using Sandcastle since 2014 to generate doc for our customers. These docs go out once every 6 months and within that period there is a chance that these redirects may break. I have seen them break in another product's doc. Also, some of our customers prefer HTTPS over HTTP as they work under tighter security rules. As HTTPS is increasingly being the norm, I think it would be helpful if we replace HTTP with HTTPS.
