### ISSUE TITLE
Is there a way to be able to include created class diagrams into Sandcastle help file?

### ISSUE THREAD

**Issue by NB17** [EWSoftware/SHFB#506]

**Comment by EWSoftware** [comment]
If you've converted the class diagram to an JPEG or PNG image, you can include that image in the SHFB project.  From MAML topics, you can use the [mediaLink](http://ewsoftware.github.io/MAMLGuide/html/34c8823f-8395-4d64-9941-8d156083709c.htm) element to include it in a topic.

If referenced from XML comments, just use the standard HTML `img` element and make sure you set the `CopyToMedia` property on the image file's properties to true so that it's copied even if not referenced by any MAML topics.  The image will be copied to the *.\Media* folder in the compiled project.  See the [FAQ entry](http://ewsoftware.github.io/SHFB/html/b92db9c5-9d0c-4d65-ac6e-d3d25adb4093.htm#EmbedImage) for an example.

**Comment by NB17** [comment]
What if I'm working with class diagram file (.cd) in Visual Studio? I can't seem to get it working

**Comment by EWSoftware** [comment]
The class diagram isn't an image.  You'll need to do something to save it as an image first.  There are no tools that I'm aware of that will do it automatically or that can be put into a SHFB plug-in to do it during the help project build.

**Comment by NB17** [comment]
Alright thanks

**Comment by StevenBonePgh** [comment]
Probably not much of a help, but VS 2008 SDK version 1.1 has sample code for "Microsoft Tools for Domain-Specific Languages (DSL Tools)" found here in the installed SDK: VisualStudioIntegration\Samples\DSLTools\Example.DesignerCustomizations\Example.ClassDiagrams\

I played with the above a long time ago, but as I recall this is not something that would parse a .cd file but allow you to get similar results with a design surface.  I don't know if any of the APIs have survived in modern VS versions.

You can [export class diagrams as an image manually](https://msdn.microsoft.com/en-us/library/ms165366.aspx).  You can also [programmatically save a UML diagram as an image](https://msdn.microsoft.com/en-us/library/ff469815.aspx) in VS2015 Enterprise (UML support removed in VS2017).  I'd imagine a similar kind of programmatic approach may work in 2015/2017 for the class diagrams, but I haven't researched specific integration points.

If you do end up finding something other than the manual approach, please update us all in this issue as I've wanted to do this exact thing in a few previous documentation projects and likely will want to do so in the future.
