### ISSUE TITLE
Howto retrieve  Display attribute name information as property description

### ISSUE THREAD

**Issue by FMoralesLdG** [EWSoftware/SHFB#513]
Hi, 

I am trying to retrieve the "Name" information inside a attribute "Display" associated with a public property in other to be show as description for the property in the .chm file.

How could I do it?, Can I use any plugin?, or extra parse option to retrieve this field?

Any help would be appreciated.

`       [Display(Name: "RGB Bitmap allocation",
        Description:"Description: \n"+
        "Range: \n"+
        "Default: 000011",
        Group: "RGB Bitmap allocation (Specific)", Order: 1.4, Collapsed: false)]

        public string RGBAllocationBitmap { get; set; }`

Thanks 
Francisco

**Comment by EWSoftware** [comment]
You'd have to turn on the option to include attributes in the Visibility category of project properties.  That would put the attribute info into the reflection data file.  They'll show up in the Syntax section at that point too.  However, if you want to use them as the description in the topic you'd still need a plug-in to extract them and create XML comments from them or perhaps clone and modify a presentation style to extract the attribute value for the comments rather than using the XML comments.

To be honest, it's probably easier to just duplicate the info in the XML comments or turn on the attribute option and rely on the attribute info in the Syntax section to provide the comments there.  The downside to the latter of course is that there wouldn't be any comments on the type pages that list all members.

**Comment by FMoralesLdG** [comment]
Hi, 

thanks you very much for your help, and sorry for ask again, but, how can I duplicate the info in the XML?, this file is generated by Sandcastle?, ...so, I need to create a plugin that can access to this .xml file on execution time and duplicate the info to be able to Sandcastle retrieve it, Is not it?

I am checking the "Execute(ExecutionContext context)" method in a plugin c# project, could you provide a simple example or help to perform this action?

I have turn on the "Attributes" option as you told me and now I can see it on the "Syntax" section.

Thanks,

Francisco

**Comment by EWSoftware** [comment]
The Sandcastle tools work with the assembly, not the source code so you can't get anything out of the source code except to import code for examples.  You can't parse it for documentation info like comments.

If you're going to use a plug-in, it would probably run after the `GenerateReflectionInfo` build step.  Your plug-in would have to load the *reflection.xml* file from the working folder.  You'll find the attribute info in it.  Find an `api` element with the member ID of something containing the attributes you want.  Using that as an example, you find the attribute elements you need and can use XPath or LINQ to XML to extract all members with the necessary attributes in order to generate comments for them.

If you've already got an XML comments file, you can add the additional info to the related members in it.  If not, you'll need to create one that matches the format of a normal XML comments file.

Take a look at something like the [Documented Entities Only plug-in](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderPlugIns/DocumentedEntitiesOnlyPlugIn.cs) as it works with both the reflection data file and the XML comments files.

**Comment by FMoralesLdG** [comment]
Thanks you very much for you help.
Regards,
Francisco Morales
