### ISSUE TITLE
Can't build SHFB project in solution that has a project referencing NETStandard.Library 2

### ISSUE THREAD

**Issue by palpha** [EWSoftware/SHFB#515]
Actual problem faced: building an SHFB project residing next to a solution in which a .NET < 4.6.1 project references System.ValueTuple fails, saying that it can't load netstandard 2.0. In the real project where this happens, I've tried to add the netstandard 2.0 dll as a reference, no luck. Updating the .NET project to .NET 4.6.1 or later resolves the issue, because then System.ValueTuple can be used without netstandard. Locking NETStandard.Library to 1.6.1 also resolves the issue.

The SHFB project does not even have the offending project as a documentation source for it to explode.

Here's a runnable minimal repro: https://github.com/palpha/shfb-issue-repro

**Comment by EWSoftware** [comment]
SHFB scans the documentation project folder for build components and plug-ins.  Since it resides at the same level as the solution, it's going to scan all the solution project and package folders as well.  The bad image format exception is typically ignored but in this case, it's the inner exception of an argument exception which isn't being handled.  I'll add code to take this case into account as well.

The solution for the time being is to move the SHFB project into its own subfolder so that it doesn't scan everything in the root folder.  That's usually a good idea anyway since then it won't lock the project output assemblies if working from within Visual Studio.  It also speeds up the build since it doesn't have to scan a lot of unnecessary folders that will never contain components.
