### ISSUE TITLE
Weird Missing Reference Errors with .NET Standard libraries

### ISSUE THREAD

**Issue by hallambaker** [EWSoftware/SHFB#518]
I have two large solutions split between a set of general libraries and a second project that builds on them.

So I spent today documenting the general libraries and got those working with no errors. Then I moved on to the second project and found that I was getting a long series of ResolveReferenceLinksComponent errors.

These issues went away when I added the libraries as a Document Source as well as in References.

This behavior seems to be limited to references to .NET Standard libraries.

I was also getting issues at one point due to the Publish builds having slightly different build versions and the XML files not being checked in some. But I fixed those.

To suppress the errors, the files have to be loaded and the namespaces have to be output in the documentation. Turning off the documentation causes 550 errors to appear which go away when I turn them back on.

**Comment by EWSoftware** [comment]
If you are documenting library B which references library A, the unresolved link warnings are normal since it doesn't have any info on how to generate a link to those members.  These warnings can be safely ignored.  If you want to suppress them, you can use the [Additional References Links plug-in](http://ewsoftware.github.io/SHFB/html/15b6b7be-3778-4487-b524-d558d02e6460.htm).
