### ISSUE TITLE
HTML Help files' names

### ISSUE THREAD

**Issue by Macharius92** [EWSoftware/SHFB#524]
Hi,

I'm trying to move the online help of our software from a tool named Help&Web to SHFB. I converted from HTML generated files to MAML, fixing some issues and build. It's all OK from that point of view. The HTML Help generated is usable (many adjustments are needed to make it nice and readable but the content is here).

What i would like to know is : Is there a way to modify the files' names ? They are generated with the topic id but the link between our application and the help is already made but with filenames. So if it's not possible, we need to manually regenerate the link between the different screens of our app with the new filename of the corresponding topic. It's somehow tricky with topic ids as filenames ;)

Thanks a lot for your answer !

**Comment by EWSoftware** [comment]
The topics are created using GUIDs by default to keep all of their IDs unique.  However, there is no requirement that they be GUIDs.  You can use any value you like such as the filenames as long as they are unique across all topics.  For example, you can't have two topics with the ID "Examples" in two different folders since it wouldn't be able to determine which one to link to and they'd overwrite each other since all topics are output to a common folder when built.

You'll need to change the IDs in each file and reassociate the topic with its entry in the content layout file.  There's a button in the File Properties section of the content layout file editor that will let you do that for each topic.  When the help file is built, the IDs will be used to name the files.

**Comment by Macharius92** [comment]
Yeah ! Thanks a lot ! It's exactly what i was looking for !
