### ISSUE TITLE
 Error BE0065 BUILD FAILED

### ISSUE THREAD

**Issue by FabioBo** [EWSoftware/SHFB#528]
We have add a new "Sandcastle Help File Builder Project" to our solution, after adding all projects into documentation source we have done documentation project build.
During build process we receive the following error: 
Error BE0065 BUILD FAILED: ......\Help\Working\System.Runtime.CompilerServices.Unsafe.xml does not contain a 'doc/members' node
We have open System.Runtime.CompilerServices.Unsafe.xml and doc\members nodes are present!
After removing this files from the solution build was completed succesfully!
Enclosed you could find System.Runtime.CompilerServices.Unsafe.xml renamed to .txt
Thank you
Fabio  
[System.Runtime.CompilerServices.Unsafe.txt](https://github.com/EWSoftware/SHFB/files/1394574/System.Runtime.CompilerServices.Unsafe.txt)

**Comment by EWSoftware** [comment]
There's a root `span` element that contains the `doc` element.  The `doc` element should be the root node.  That's why it can't find the `doc\members` element.  Remove the `span` start and end tags and it will work as expected.

**Comment by FabioBo** [comment]
Yes, i've already tried to remove _span_ element as you have suggested and it's works!
However, System.Runtime.CompilerServices.Unsafe.dll is a .net framework component and when we will upgrade to the new version the problem will be back.
Could you plan to avoid this issue on next release of SHFB?
Thank you

**Comment by larrybud2004** [comment]
I confused by this issue.  Why should we have to touch the XML of a .net library?

**Comment by EWSoftware** [comment]
@larrybud2004: Because it's broken and contains invalid XML.  There should be a reasonable expectation that XML comments files contain valid XML.  Unfortunately, Microsoft is producing more and more bad XML comments files through their NuGet packages.  Future release of SHFB will simply throw them out and not use them.  It's not up to me or the build tools to fix them as there are just too many things that can be wrong with them.  That's on the producer of the packages.  Until they do fix them, if you want them used, you need to fix them manually.
