### ISSUE TITLE
Requires Visual Studio 2015 (MSBuild 14.0)

### ISSUE THREAD

**Issue by Hazealign** [EWSoftware/SHFB#529]
Thanks for nice project.
I tried to install it on my PC, but it doesn't works and it showed popup that it requires MSBuild 14.0.
How about to add requirements on [Installation Instructions](http://ewsoftware.github.io/SHFB/html/8c0c97d0-c968-4c15-9fe9-e8f3a443c50a.htm)?

**Comment by mike-barnett** [comment]
I also have run into this on a machine that has VS2017 installed, but *not* VS2015. I really don't want to have to install VS2015 to fix this.

**Comment by EWSoftware** [comment]
You don't have to install VS2015, just the MSBuild 2015 tools as referenced in the link in the release notes.  If you've got VS2017 installed, you don't need them since Visual Studio uses whatever version is build into it.  Likewise, the version of MSBuild that comes with VS2017 works without issue from the command line.  It's only an issue if using the SHFB standalone GUI.

**Comment by mike-barnett** [comment]
Thanks! I've installed the MSBuild 2015 tools and that worked!

**Comment by VBWebprofi** [comment]
MSBuild Tools 2015 (V 14.0) located here https://www.microsoft.com/en-US/download/details.aspx?id=48159.
