### ISSUE TITLE
search can not use chinese

### ISSUE THREAD

**Issue by YaoNiGu** [EWSoftware/SHFB#532]
The search function on the web site which generated by SHFB can not search by Chinese. As long as any Chinese word appears in the description, We still cannot search the method or description by English keywords. How can I solve this problem? Thanks.

**Comment by EWSoftware** [comment]
The keyword index generation and the keyword search term splitting are done by splitting the text on whitespace characters to figure out what the words are.  This will work fine for Latin and Cyrillic languages but probably won't work at all for languages like Chinese.

Unfortunately, to solve it would probably require an entirely different key word index creation process which is part of the build engine and alternate script for the website to split the entered keywords used for the search.  Since I'm not at all familiar with Chinese or other such languages, this isn't something I can provide a solution for.
