### ISSUE TITLE
Content orders

### ISSUE THREAD

**Issue by wsptr** [EWSoftware/SHFB#538]
In SHFB generated files, all contents, including fields, properties, namespace, etc. are all ordered by alphabetic order. But sometimes I need them to be maintaned in orders exactly the same as they are in program. How can I keep the orders unchanged?

**Comment by EWSoftware** [comment]
MRefBuilder sorts the namespaces, types, and members in alphabetical order before they get written to the reflection information file.  Removing those sorts for one special case is not really an option.  Even then I'm not sure you can guarantee an order for anything since I'd guess its dependent on the order things are compiled and then written to the assembly.

If you create your own presentation style and include source context info in the SHFB project by setting the [source code base path](http://ewsoftware.github.io/SHFB/html/e6fcfa33-e7ee-430a-abfe-6b7962e6d068.htm#SourceCodeBasePath) it's possible you could update the TOC XSL transformation and presentation style transformations that sort members to sort by the `@startLine` attribute value on the `api/sourceContext` element.  However starting line info isn't available for all types.

**Comment by wsptr** [comment]
Thank you very much for your help!
