### ISSUE TITLE
Lightweight Website Style Plug-In settings page

### ISSUE THREAD

**Issue by joriszwart** [EWSoftware/SHFB#54]
Although there are no settings for this plugin it would be nice to have it available in the list of plugins. More specific: I want to be able to disable the plugin.

The reason behind this is that I want to embed the documentation into a website using the *VS2013 presentation style*. In order to embed it I have to strip some HTML from the topics content. However I cannot process the content HTML on the server-side easily because it is not valid X(HT)ML. Without the *Lightweight Website Style Plug-In* however valid XML is generated. Of course the *ToC* is missing then. But transforming`WebTOC.xml` with XSLT and the files from the `html/`-directory (which are valid XML) I was able to embed the documentation into the website.

For now I solved this by creating a custom *presentation style* where I left the *Lightweight Website Style Plug-In* commented. This works for me, but it has to be maintained over time.

Another alternative for me would be to have another *output file format* or *presentation style* that outputs XML for every topic (or have I overseen something and is this already possible?)

**Comment by EWSoftware** [comment]
The way the plug-in was originally written was to enforce HTML output when writing the TOC elements due to the empty div used for the resizing bar which, if written as a self-closing element, breaks the display in the browser.

However, that can be fixed by adding an empty text element to the div to ensure it's still written out with a full opening and closing tag.  It can then be saved as normal XML so that the image elements are self-closing and the topics can be post-processed as XML files.  I'll make the change for the next release.

**Comment by joriszwart** [comment]
Great!
