### ISSUE TITLE
How to include JSDoc files to project

### ISSUE THREAD

**Issue by larsmarkussen** [EWSoftware/SHFB#543]
Hi
I've generated some JSDoc from my javacripts files. How can i include this generated HTML into my project? i tried simply adding all the files, but (obviously) they dont appear in the toc. Searching for some of the content do however reveal that the hhtml files are included. Accessing any of them will throw an error... 
Optimal i would like to extract the JSDoc comments to XML files, and then include this, but there dont seem to a be a tool or plugin for this?

**Comment by EWSoftware** [comment]
Add a [site map file](http://ewsoftware.github.io/SHFB/html/3dd5fe3b-1bc3-42e5-8900-56165e3f9aed.htm) to the project and add entries to it to lay out the HTML files in the order you want them to appear in the TOC.

If the HTML files reference any script or style sheet files, you'll need to add them to the project as well with a Build Action of "Content" so that they are included as well.
