### ISSUE TITLE
PresentationStyle specific ProductionTransforms

### ISSUE THREAD

**Issue by Frogman7** [EWSoftware/SHFB#547]
I have modified the 'CreateVSToc.xsl' in order to customize the generation of my table of contents.  However, the only way I know to apply this is to set it globally in my Sandcastle install directory:

"Program Files (x86)\EWSoftware\Sandcastle Help File Builder\ProductionTransforms"

Which of course means this now applies globally to all presentation styles.  So on to my question, is it possible for me to configure this so that it only runs on my custom presentation style and if so how might I go about that?

**Comment by EWSoftware** [comment]
[Create or clone one of the presentation styles](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm) and make your change to the TOC transformation there by assigning its path to the `IntermediateTocTransformation` property.  In this case, it'll be stored locally with all the other presentation style files so the path will be relative to the presentation style assembly rather than in SHFBROOT.

**Comment by Frogman7** [comment]
Sorry I was working to close this as soon as I'd confirmed it worked which it did.  Thanks for your help.
