### ISSUE TITLE
Just need to link to existing doc pages

### ISSUE THREAD

**Issue by rindlespot** [EWSoftware/SHFB#55]
I've been scanning thru the docs for sandcastle, and I'm not seeing how to do what I'm trying to do.  Before I take the time to download, install, configure, etc, it would be helpful to know that at the end it will do what I need.

In concept, what I need to do seems simple (doesn't everything?).  Right now if I press F1 on an interface I have defined in my project, Visual Studio 2010 attempts to open a url formatted something like this:

https://msdn.microsoft.com/query/dev10.query?appId=Dev10IDEF1&l=EN-US&k=k(FOO);k(TargetFrameworkMoniker-".NETFRAMEWORK,VERSION=V4.0.3");k(DevLang-CSHARP)&rd=true

And obviously this fails since there are no docs for "foo" in the .Net 4.0.3 framework on msdn.microsoft.com.

As it happens, the docs that I want to link to already exist online.  I just need to be able to change the link that VS uses to find them.  Conceptually something like:

    [HelpUrl("http://docs.bar.com/lookup/foo.html")]
    public interface foo
    {
        [HelpUrl("http://docs.bar.com/lookup/foo-Meth1.html")]
        int Meth1();
    }

And I need to be able to package this up so people using my assembly can do this too.  But I can't quite see how to get there from xmldocs.  They all seem to want me to duplicate the text of the docs in the cs files.  That's not what I'm looking for at all.

Is sandcastle the right tool for this?  Is there an easier way?

**Comment by EWSoftware** [comment]
I doubt you'll find anything that does what you want since you're trying to change the way Visual Studio looks for and opens help topics.  Most tools, Sandcastle included, combine information about the assemblies with the XML comments to produce a help file that is then merged into the Visual Studio help collection.

That said, I did find this thread that describes a possible way to extend the websites Visual Studio will use for online help:  https://social.msdn.microsoft.com/Forums/vstudio/en-US/c67624d3-2f20-47ba-ba6a-c03055d658cc/change-f1-help-online-url?forum=vsx

That may get you something like what you want but you'll probably have to modify the website to look up the passed member name.  It also assumes you can force all your users to use online rather than local help.
