### ISSUE TITLE
Custom tag to add new version column in member tables

### ISSUE THREAD

**Issue by Caleb-D** [EWSoftware/SHFB#561]
In another project, using Innovasys Document! X, we added a <version> tag that could be placed on classes, enums, enum members, methods, properties, etc. 

In addition to showing the <version> text in the content topic for the member, we also modified the member summary tables to add a column with the version for the member (default was "---" if no version tag).

Now on different project and trying to modify Sandcastle presentation styles to do the same thing.  I see how to put the version tag information into the content topic for the member, but the xml available at the point of running the xslt template to add a <td> to the member table appears to only contain the <summary> information.  

If it is possible to get the <version> tag contents at this point, could someone point me in the right direction?  If not, could this functionality be added (custom tag contents at member table <td> template execution)?

**Comment by EWSoftware** [comment]
Assuming you're referring to the member list pages, you probably just need to update your *BuildAssembler.config* file so that the new element is copied in when getting the info for the members.

You should find an instance of the `For Each Component` preceded by the comment "Copy in reflection data and comments for members".  Within that is a nested instance of the `Copy From Index Component`.  On the `copy` element for it, you should see the source which is set to "summary|overloads|example".  Change it to "summary|overloads|example|version" and it should make the version element available to the transformation.

**Comment by Caleb-D** [comment]
Thanks, this sounds like it will work.
