### ISSUE TITLE
Bad displaying of the TOC after selecting an entry

### ISSUE THREAD

**Issue by peter-sabath** [EWSoftware/SHFB#562]
I have a help file that contains a welcome page, a guides folder with some usage articles and an API reference which is generated, using a layout as follows:
![grafik](https://user-images.githubusercontent.com/31621424/35002408-d86f38a2-fae9-11e7-9387-29f54d3287f7.png)

When the help is opened from the root navigation everything looks good:
![grafik](https://user-images.githubusercontent.com/31621424/35002447-fb81af64-fae9-11e7-91e8-e0c5bd6518ee.png)

When I select "Basic object handling" the display misses some entries:
![grafik](https://user-images.githubusercontent.com/31621424/35002482-18ff097e-faea-11e7-9745-e5fdef3fdec5.png)

The "Welcome" page is missing as well as the complete "Reference" subtree, and the only way to get it back is to click on the root again.

If I select a page from the reference, API sub tree is visible, but not as child of "Reference" and without showing the "Guides" folder or welcome page.
![grafik](https://user-images.githubusercontent.com/31621424/35002753-f195d75e-faea-11e7-9c0b-aac3655bb6e7.png)

This behavior is highly confusing. Is that a bug, or is there something I can do myself with changing the project file?

Used version: 2016.9.17.0

**Comment by EWSoftware** [comment]
It's not missing entries, it's using a lightweight style.  Each topic only contains a fragment of the TOC with its immediate children if any plus its siblings and parents up to the root.  Expanding any collapsed nodes will fill them out and, if they are parents, then you'll also see their siblings etc.  It's by design and works similar to how the MSDN site does for the .NET framework.

**Comment by peter-sabath** [comment]
Is there any way to change that? 
Using another style for example or adding a breadcrumb trail to each page.
Forcing to always include the full TOC up to an predefined depth, e.g. 2 levels deep.

Looking at the example with the "Basic object handling" entry, the user never gets a hint, that there is anything other than the "guides" folder. And if that page was opened from a google search result, the user will run (and many have already) in this problem.

Possibly you have an entry point for me learn how to extend an existing style or add a new one.

**Comment by EWSoftware** [comment]
You can [create a presentation style project](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm) and copy the content of one of the existing presentation styles into it.

However, in this case, I think it will be more a case of modifying or replacing the [lightweight website style plug-in](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderPlugIns/LightweightWebsiteStylePlugIn.cs) since that's what generates the TOC fragment files and inserts the default elements into each topic.
