### ISSUE TITLE
Suggestion: Repeat the need for "Microsoft Build v14" in current release notes

### ISSUE THREAD

**Issue by warrickprocter** [EWSoftware/SHFB#563]
Not an issue, just a suggestion for an excellent product:

After a fresh/clean install of Windows 10, I installed VS 2017 (v15) and the latest SHFB (v2017.12.30.2).
I then struck the "Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0...".
I could not see anything in the release notes for SHFB v2017.12.30.2 but googled the issue and found https://github.com/EWSoftware/SHFB/issues/478.
Although blindingly obvious now, it took me some time to solve the problem of needing to install Microsoft Build v14.

I would have found it helpful if the current release notes (and maybe some previous ones) could repeat the need to install "Microsoft Build v14" as shown in SHFB "2017.5.15.0 Release Notes".

Regards, Warrick

**Comment by EWSoftware** [comment]
It's noted in the guided installer.  If you don't use that you can miss it I suppose.  It's also noted in the installation requirements topic.  To be honest, repeating it in the release notes is redundant since most people don't read them anyway.  The referenced work item is proof of that since it was related to the release it which it became a requirement.

It only affects the standalone GUI.  I suppose I could have it catch that specific exception and tell you what to do.

**Comment by warrickprocter** [comment]
Accepted. Thanks.

**Comment by alexbk66** [comment]
I agree, I have to spend some time trying to troubleshoot the issue (i.e. re-installing, googling, etc.).  Adding this to release notes won't help much, how many people read the notes?
1.  At least instead of unhandled exception it should at least display a decent message!!!
2.  Installer should check the dependencies!
