### ISSUE TITLE
Sandcastle did not for for me with Visual Studio 2017

### ISSUE THREAD

**Issue by zhulika** [EWSoftware/SHFB#564]
I just downloaded and tried to install Sandcastle on my machine (SHFBInstaller_v2017.12.30.2.zip). The installation refused to install the extension and then complained that I hadn't checked any schemas (they were all disabled). I do not have Visual Studio 2015 on this machine (though I did install the build tools as per the instructions).

I carried on to see if it would work anyway, but the help file builder GUI complained that it did not support the CSPROJ format for my .Net Core 2.0 projects and it refused to produce any documentation for them. It did successfully produce documentation for the legacy projects, though.

I didn't notice anything here about problems with .Net Core, so that may not be the problem.

**Comment by EWSoftware** [comment]
The guided installer only looks in the standard locations for Visual Studio installations.  If you've installed it somewhere else such as on a different drive or folder, just run the VSIX package manually to install it.  If you want the MAML schemas installed, you can do it [manually as well](http://ewsoftware.github.io/MAMLGuide/html/746fc19e-2670-440b-8277-a1ef7dc074d5.htm).

The standalone GUI does not support the newer project formats since its using the older MSBuild tools.  Once you get the Visual Studio extension installed, it will be able to handle them from within VS 2017.
