### ISSUE TITLE
Unsupported library System.Collections.Immutable

### ISSUE THREAD

**Issue by wojtpl2** [EWSoftware/SHFB#569]
SHFB doesn't support library System.Collections.Immutable. https://www.nuget.org/packages/System.Collections.Immutable/

After add reference to project SHFB can not create documentation. I have error message:
```
BUILD FAILED: The 'br' start tag on line 507 position 385 does not match the end tag of 'p'. Line 507, position 391.	TestCaseProject	SHFB	0	
```

**Comment by wojtpl2** [comment]
I've created pull request with example of this exception:
https://github.com/EWSoftware/SHFB/pull/570

**Comment by wojtpl2** [comment]
System.Collection.Immutable is used in 
Microsoft.EntityFrameworkCore. This means that can't create documentation if you use new Entyty Framework Core.

**Comment by EWSoftware** [comment]
This is a known issue with a number of the newer framework NuGet packages from Microsoft.  See issue #560.  They appear to have a bug in their XML comments file generators that can result in invalid files.  A workaround for the time being is to manually fix the file in the package folder or, add a corrected copy to your SHFB project which should override the bad one.

As noted in the other work item, I can work around it by ignoring bad XML comments files but then you lose the comments from the base types.  The only real fix is to report the issue to the package owner (Microsoft in this case) and have them fix the bad XML comments file.

**Comment by wojtpl2** [comment]
I understand that is issue in Microsoft's xml. It is part of html in xml
file. Maybe you should fix xml before processing them. It isn't so hard.
What do you think?

**Comment by EWSoftware** [comment]
It's not my job to fix broken XML comments files.  The build engine can't fix them on the fly either.  As noted in the other thread, there should be reasonable expectation that XML comments files are well formed.

I'll add a workaround to just ignore such bad files but, like I said, if you want them truly fixed, you're going to have to complain to the package owner which is Microsoft in this case.

**Comment by wojtpl2** [comment]
I understand you but all you need to do is change `<br>` to `<br/>`.
I just want to generate documentation to my code. I don't need reference to Microsoft code and documentation.

**Comment by mprochaska** [comment]
It's January 2019.  MS has not fixed the docs for System.Collections.Immutable.  It has been more than a year. 

As a pragmatic programmer, I cannot use your tool.  FULL RESPECT.  I fully support your position, I agree with you in full.  I acknowledge my OCD.  I like documentation, how am I going to explain my time fixing MS docs on my machine so I can generate documentation?  How am I supposed to share this with my team?

Is this the hill you want to die on?; I am not willing to jump on the gerbil wheel and correct nuget package XML files from MS.  Nor do I expect you to do the same.  Give me the option.  Give me the warning, do not give me broken documentation silently and explain why on the web so that I spend hours finding this page.

I have used a this tool for years; I got strange results after a hiatus.  I spent hours chasing this down.  My only ding; fail completely; do not give me broken documentation.

Your position is technically accurate and totally defensible; my response is I will not use SHFB again until you address meeting the user need.  ASSUME: MS will continue to ship broken XML doc files in nuget.  Blaming MS is like crying that it rains too much in Seattle.  Your ask is reasonable, it is not being met; change your expectation.

You are the owner; you decide.  I am saying goodbye to a favored tool.  

I give feedback because this was a favored tool.

**Comment by mprochaska** [comment]
Hello,

I installed from SHFBInstaller_v2018.12.10.0.zip last week.

I read the error messages in the log, saw undocumented methods that returned System.Collections.Immutable types and tracked down this article with a reason for won’t fix by searching System.Collections.Immutable SHFB

I am certain there is user error involved

I will set aside time to re-install and repo this on another machine if you are interested.  Nothing told me how to self-help based on what I was seeing and a “won’t fix” statement on a similar issue on the web led me to choose another tool.

If I had this experience it is likely someone else will have the experience.  I am not trying to make you wrong.

I think we disagree on the meaning on this turn of phrase:
“The help file will build successfully but you'll be missing comments for base types from the broken comments files”

I would describe that as the output is mangled due to XML docs from MS nuget packages, you will get a warning, but no solution is provided for with SHFB.

You are welcome to disagree, but I want my methods documented, not stripped of documentation.  I am happy there is a warning, many tools fail to even warn; but no documentation is a failure condition in my opinion.  As an engineer, I fully understand your reasoning and your choice.  But that leaves me with a broken scenario and no path forward with SHFB.

Respectfully,

~Michael

**Comment by EWSoftware** [comment]
If this is the issue you ran into, you should have seen BE0031 warnings in the build log.  If it's something else, I can look into it if you provide an example.

Regarding the missing docs from the topic list pages related to the BE0031 warning, it's not something that can be fixed without making the XML comments files valid.  There's nothing more I can do with this issue.  I have the build engine issue a warning so that you're aware of the problem but I nor SHFB can't magically insert valid documentation from a broken source.  If you or anyone else can suggest a solution that actually inserts the missing info, feel free to suggest it.

If you want to stop using SHFB because of this, that's your choice but it seems like you're blaming the tool for a problem that it simply cannot fix and is beyond my control.

**Comment by EWSoftware** [comment]
I apologize if it seemed like I was taking my frustration out on you.  It's not what I intended.  There may be ways to handle malformed XML but none that I could find short of writing my own XML parser which wasn't something I felt I could do so I fixed the issue as best I could.  This is an open source project and I do welcome contributions.  If somebody does want to tackle it and solves it, I'm more than happy to merge that solution.  I can't do anything more with it but I'm not opposed to using someone else's solution if there is one.  The same is true for any other issues or new features.

Looking into this further, I did find this issue in the [Roslyn project](https://github.com/dotnet/roslyn/issues/24177) which referenced another issue in the [corefx project](https://github.com/dotnet/corefx/issues/26263) which addresses this very issue.  It does appear that Microsoft has fixed their IntelliSense tooling so that it doesn't generate the invalid XML anymore.  That said, it won't affect previously released NuGet packages which makes sense since I don't think it's even possible to replace prior published versions.

I downloaded the 1.4.0 and 1.5.0 version of the System.Collections.Immutable NuGet package which started this issue.  Comparing the XML comments files in the two, the 1.5.0 version has been fixed.  So, if you are using or update to the latest release of the packages, the issue resolves itself.  However, all is not perfect as I do see that in the 1.5.0 copy of the comments many of the `cref` attribute values are missing the type code prefix such a "T:" or "M:" or "P:".  Without those, it will fail to resolve the reference when generating links to the online content.  You'll still get base type documentation but links to the online topics from them will not be useable for those ill-formed link targets.

If you are using the latest release of the NuGet packages, I suspect the issue with the invalid `cref` values is what you actually ran into and it was complaining that it couldn't resolve those bad links.  That can be fixed since it's easy enough to check for the missing type code prefix and try the common ones to see if it can find a match.

**Comment by mprochaska** [comment]
Eric, please open a private contact with me if you want me to take a deep dive.  I am offering.  I spent last week looking as CS101 topics to prepare for my interview today.

I am motivated.  I am interested.  Let's have a private conversation if you want me to dig in.  I have time to give.  I want to talk about your perspective, scope, and limits.  I am a minimal change dev.  I've pulled your source in prep, I have not started a deep dive.  I in no way want to rewrite it.  Minimal impact is a switch, or any other option of your choice.  This is the wrong forum to discuss what you want.  We have shared our dirty laundry, let us talk in private.

I specifically want your guidance, limits and goals.  My goal is simple, some mechanism for handling Systems.Collections.Immutable 1.5.0.  We accomplish that, and we can generalize.  You are the product owner, you are in charge.

~M

**Comment by EWSoftware** [comment]
There's no e-mail address on your profile and GitHub doesn't appear to allow private messaging anymore.  You can contact me via e-mail using the one on my profile or in the SHFB help file.  A good starting point would be an example that reproduces the issue in question.
