### ISSUE TITLE
Consider distributing alternative "light" theme via NuGet

### ISSUE THREAD

**Issue by sharwell** [EWSoftware/SHFB#58]
Certain presentation aspects of the SHFB output are subjective, and obviously we can't match everyone's individual tastes. It would be nice to have a live example of an alternative presentation style so developers can easily understand how to use the reference implementation of SHFB alongside their custom theme.

I propose packaging the "light" theme described in the comments of #49, #51, as well as the script modifications in #44 as an independent package that can be installed in a SHFB project to automatically use that output.

I am not sure this is possible in the exact form described here, but I wanted to create this issue so it doesn't get lost. :smile:

**Comment by EWSoftware** [comment]
A NuGet package is probably overkill.  Expanding on the existing topic about [stock content replacement](http://ewsoftware.github.io/SHFB/html/77d2d693-db84-4ae3-a84c-e33c71f92e9a.htm) and moving it up to the root of the TOC is more than sufficient.  It can be updated to include a walkthrough.  I don't really want to add a NuGet package for something like this since then it has to be maintained and published with each new release if it changes.
