### ISSUE TITLE
Markdown formatting in HTML output

### ISSUE THREAD

**Issue by DataTables** [EWSoftware/SHFB#59]
I'm wondering if it is possible to use Markdown to add plain text formatting in documentation comments that will then be transformed (via Markdown) to be HTML in the generated documentation. For example if I have:

```
    /// <summary>
    /// This awesome class provides the following features:
    ///
    /// * Makes the coffee
    /// * Washed the dishes
    /// * Takes out the rubbish
    /// </summary>
    public class Awesome
```

The output would be the normal HTML template that Sandcastle provides, but rather than plain text for the summary it would be Markdown HTML.

I've seen other requests for complete Markdown output (#8) for example, and I might be misunderstanding or completely missing an existing feature, for this, but it would be great if we could plain text format comments.

**Comment by dotMorten** [comment]
Plain text formatting would go against the XML Code summary Language - this isn't controlled by Sandcastle but by Microsoft, and it's inherently XML and HTML based. I think it would be a bad idea to start adding new flavors of code summaries to a standard already used in C#.
Personally I believe it's better to have the transform tools generate either html or markdown from a well-defined markup, rather than changing the entire input.

**Comment by EWSoftware** [comment]
There won't be support for markdown in the MAML or XML comments themselves.  The problem is that there's no guarantee that the comments will be imported and passed through the transformations as-is.  Inline stuff like bolding or emphasis would probably be fine in some cases but anything like lists that rely on the structure of the text would up wrong and wouldn't appear as a list.

The markdown presentation style under development should work fairly well but there are a number of limitations as noted in work item #8.  There's no way to render pure markdown with an automated process using MAML and XML comments which are much less restrictive with regard to the resulting document structure.  As such, there's typically more HTML than markdown in the rendered topics.

**Comment by DataTables** [comment]
Thanks for letting me know!
