### ISSUE TITLE
SHFB Build Error when using custom presentation style 

### ISSUE THREAD

**Issue by FredEkstrand** [EWSoftware/SHFB#603]
I had recently created a PresentationStyles using the VS2017 PresentationStyles project. Then package it in an Inno installer.
While testing the install and usage of the new presentation style SHFB generated the following error near the end of the build.

SHFB: Error BE0065: BUILD FAILED: Could not find a part of the path 'C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\LegacyWeb'.

Base on my current understanding of the PresentationStyles extensions setup/layout LegacyWeb is part of the main application not extension.

**Comment by EWSoftware** [comment]
The files in the *.\LegacyWeb* folder are only used by the VS2010 presentation style or those based on it.  If yours is based on it, simply include it as part of your presentation style project and adjust the path accordingly on the `ContentFiles` entry that includes it.  If it's not, you can remove it.

Those files were shared with a couple of other deprecated presentation styles but they were removed.  In reality, those files probably should be moved into the VS2010 presentation style folder now since they are no longer shared.
