### ISSUE TITLE
HTML content not linked correctly in TOC

### ISSUE THREAD

**Issue by thomas-delahaye** [EWSoftware/SHFB#61]
I run SHFB (v2015.1.12.0) on an API documentation with conceptional content (i.e. MAML files) and HTML content to generate a website help.
The files are structured in the project as follows:
* `\`
 * `htmlcontent.html`
* `Content\`
 * `conceptual1.aml`
 * `conceptual2.aml`
...

Then, in the table of contents (TOC), I get a structure like this:
* (Title of `conceptual1.aml` as defined in `.content` file)
* (Title of `conceptual2.aml` as defined in `.content` file)
* (`<title>` of `htmlcontent.html`)

But in the TOC, all pages a linked using relative URIs that do not define a path. As the TOC is in the `html` folder of the generated web, all links point to the same folder. `htmlcontent.html` is copied to the resulting web, but not to the `html` folder, so that the link does not work.

I already played with the location of the `htmlcontent.html` file within the project a bit: whenever I put it in a folder (like `Content\htmlcontent.html`), this folder is part of the TOC:
* (Conceptual pages like above)
* `Content`
 * (`<title>`of `htmlcontent.html`)

Unfortunately this does not change the link (`href`), but only introduces a "topic" in the TOC.

Do I miss a setting in the project file or on the HTML content files? How can I influence the links in the TOC - or the location of the HTML content in the generated web help?

-Thomas

**Comment by EWSoftware** [comment]
Put the HTML file in an *html\* folder within the SHFB project.  It will then get copied to the *html\* folder during the build.  That may resolve the issue.  You may also need to add a site map file that references the topic.  You can set the sort order property on the site map and content layout files in the project to get the content of each added in the order you want.

Bear in mind that the additional content model that copied files and added them to the TOC has been deprecated for a long time and may not work with the latest presentation styles, especially the VS2013 style since it expects to be able to embed the TOC fragments in each topic.  MAML is the preferred method since the build handles all of the requirements to make them work properly.

**Comment by thomas-delahaye** [comment]
Thank you, I already tried to put the HTML in the `html` folder, but I didn't know about the site map - that did the trick.
This is all an attempt to include an external documentation website (for an TypeScript API) in the TOC. The HTML file just redirects to the external documentation that is generated by another tool.
Do you have any suggestions what I might try in the "MAML world" to achieve that?

**Comment by EWSoftware** [comment]
A MAML topic with an externalLink that goes to the other site would probably do it.  If you want it to automatically redirect using script, you can use a markup element.  Something like this should do it:

``` XML
<markup>

<p>If you are not redirected automatically, follow this link to the
<a href="http://www.someothersite.com">API documentation</a>.</p>

<script type="text/javascript">
window.location.replace("http://www.someothersite.com")
</script>

</markup>
```
