### ISSUE TITLE
Missing Cloo.dll

### ISSUE THREAD

**Issue by khatran79** [EWSoftware/SHFB#62]
hi mate. trying to build the first doc on x64 win7 machine but failed with missing cloo.dll. 
any idea pls.
thanks

Generating reflection information...
[C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe]
Build started 2/04/2015 11:18:55 PM.
Project "C:\Users\Kha\OneDrive\My Documents\Help\Working\GenerateRefInfo.proj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj\Debug\".
GenerateRefInfo:
  MRefBuilder (v2015.1.12.0)
  Copyright ¸ 2006-2015, Microsoft Corporation, All Rights Reserved.
  Portions Copyright ¸ 2006-2014, Eric Woodruff, All Rights Reserved.
  Loaded 1 assemblies for reflection and 1 dependency assemblies.
MRefBuilder : error : Unresolved assembly reference: Cloo (Cloo, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null) required by OpenCLTemplate [C:\Users\Kha\OneDrive\My Documents\Help\Working\GenerateRefInfo.proj]
    Last step completed in 00:00:02.1506
-------------------------------

SHFB: Error BE0043: Unexpected error detected in last build step.  See output above for details.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.RunProcess(String fileToRun, String args)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by EWSoftware** [comment]
The OpenCLTemplate assembly you're trying to document has a reference to the given version of the Cloo assembly.  If you use the Visual Studio solution or project as the documentation source it should resolve the reference automatically from the project information.  If you've added the assembly directly as a documentation source, you can add the Cloo assembly to the References project node so that it knows to include it for the build.

**Comment by khatran79** [comment]
working as guided. thanks.
