### ISSUE TITLE
SHFB build failed on Linux

### ISSUE THREAD

**Issue by PocherninaElena** [EWSoftware/SHFB#627]
I tried to build SHFB project on Linux and the build failed while the same project was successfully built on Windows.

The error message: "SandcastleHelpFileBuilder.targets (15,2): error MSB4019: The imported project "Microsoft.Common.Targets" was not found. As I see this file exists but the name is "Microsoft.Common.targets". 

How can I build my .shfbproj project on Linux?

**Comment by EWSoftware** [comment]
I've never built it for use on Linux and have never set up or used Linux so I can't say how you can get it working.  Microsoft.Common.targets is typically a part of MSBuild so either something is missing or it can't find what it needs due to a missing path or environment variable.  It looks for it using `$(MSBuildBinPath)`.  You should be using MSBuild 14.0 at the minimum if there's a Linux equivalent.

**Comment by PocherninaElena** [comment]
I used MSBuild 15.0, the problem is that when I build it on Linux it finds all names case-sensitively and that is why couldn't find this Microsoft.Common.targets file. That means that SandcastleHelpFileBuilder.targets contains wrong file name (case-insensitive).

**Comment by EWSoftware** [comment]
I've published an updated package containing the name fix (2018.7.8.1).
