### ISSUE TITLE
SHFB on Linux

### ISSUE THREAD

**Issue by PocherninaElena** [EWSoftware/SHFB#628]
After a new release it seems much better, but fails again.

The error is  "SHFB : error BE0065: BUILD FAILED: Directory "/home/user/project/_build\" not found." 
I looked at your source code and found a lot of strings like this:  str + "\*\\\*" (with backslash).
The problem may be with them. 
For these purposes could be better to use DirectorySeparatorChar (https://msdn.microsoft.com/en-us/library/system.io.path.directoryseparatorchar(v=vs.110).aspx) and using this constant may solve my problem.

My folder "/home/user/project/_build/" is a folder which contains .shfbproj.

**Comment by EWSoftware** [comment]
As I mentioned in the other issue, I don't have nor have I tried to use this on Linux.  Apparently nobody else has yet either at least not that anyone has reported.  As such, there will likely be several issues.  I can fix them up as they are found but it's not something I can dedicate time to in order to find them all myself.

**Comment by EWSoftware** [comment]
Sorry, but after considering this, I'm not going to support Linux.  I just don't have the time or inclination to do it.  I could make changes to SHFB related to the path separator but there's no guarantee there wouldn't be other issues and I since I won't be testing it on Linux there's no guarantee that changes I make in the future wouldn't break something without me knowing it.  As such, I can't provide support for it and won't be making any changes to support it.
