### ISSUE TITLE
Ability to use VS2013 presentation style with full TOC 

### ISSUE THREAD

**Issue by melissaburpo** [EWSoftware/SHFB#63]
Our dev shop likes everything about the VS2013 presentation style, but we are interested in making a change to how the TOC behaves. We don't have that much content, and so it is confusing when you click on one of the nodes to view the child content. The rest of the sibling nodes disappear, and you can only see the selected node and its children. 

Ideally for us, when you select any nodes beneath the top parent, we'd like to still display the sibling nodes of the selected item, so that people can easily jump around the full TOC. 

It looks like this functionality is controlled by the hidden plugin LightweightWebsiteStylePlugIn.cs and that there aren't any configuration options for it. 

Is there a way to use the VS2013 style and also persist the full TOC as you click through it? Or would we need to customize our own version of LightweightWebsiteStylePlugIn (or do something else)?

**Comment by EWSoftware** [comment]
The lightweight TOC only inserts the TOC fragment into each topic that's necessary similar to what the MSDN website does.  The full TOC is still accessible from each topic but you do have to expand the parent nodes to see their content.

In order to get the full TOC, you'd have to go back to the frame-based implementation used by the VS2010 and earlier styles.  Since the search and TOC elements are inserted by the plug-in, you could probably clone the presentation style and, rather than using the lightweight TOC plug-in, use the same legacy web content that the VS2010 style uses.

**Comment by melissaburpo** [comment]
That makes sense. I definitely don't want to go back to a framed site, so we'll stick with it as is for now. Thanks for the reply.
