### ISSUE TITLE
Human readable urls

### ISSUE THREAD

**Issue by mikasoukhov** [EWSoftware/SHFB#637]
Does SHFB do this feature? To avoid (and sure support as a backward compatibility) GUIDs?

**Comment by EWSoftware** [comment]
You can use the [Member Name naming option](http://ewsoftware.github.io/SHFB/html/1b2dff59-92cc-4578-b261-f3849f30c26c.htm#NamingMethod) rather than GUID naming.  With regard to MAML topics, they default to a GUID for the ID but you can change it to whatever you like as long as it is unique across the entire set of topics in the project.

**Comment by mikasoukhov** [comment]
The key moment is backward compatibility. To use both URLs resolving simultaneously with following redirection.

**Comment by EWSoftware** [comment]
The sites as built won't do that.  That's not to say it can't be done but it's not something I plan on adding or supporting.
