### ISSUE TITLE
Compiler warnings "warning : BuildAssembler : warning : ShowMissingComponent:" when method returns a tuple

### ISSUE THREAD

**Issue by roryap** [EWSoftware/SHFB#649]
I'm getting spurious compiler warnings when I build the documentation project, and the output help file says it's missing elements that are not actually missing.  Please use the attached VS solution and compile the documentation project to see what I mean.  The output I'm getting is also provided in the attached zip file.

[Compiler warnings ShowMissingComponent when method returns a tuple.zip](https://github.com/EWSoftware/SHFB/files/2425558/Compiler.warnings.ShowMissingComponent.when.method.returns.a.tuple.zip)

**Comment by EWSoftware** [comment]
Your assembly is built against .NET 4.7 but the SHFB project is set to use .NET 4.5 to get the reference info.  This is causing the mismatch in parameter types.  Changing the SHFB project to use .NET 4.7 for the Framework Version property will fix the issue.

Note that you can use the solution or project as the documentation source rather than the assembly and XML comments file.  If the build engine finds a mismatch between the documentation source project version and the SHFB project version, it auto-corrects it to prevent such issues.
