### ISSUE TITLE
Mapping Excel topic ids

### ISSUE THREAD

**Issue by keithalewis** [EWSoftware/SHFB#651]
I use the old-fashioned Excel SDK to register xll add-ins.
For context sensitive help in Excel (Help on this function in the Function wizard) one must specify the HelpTopic. It has the form filepath!HelpContextID where filepath this the complete path to the .chm file and HelpContextID is a 4-byte unsigned integer.
How does one determine the appropriate HelpContextID? 
I used to create a Map.h file that specified the HelpContextID to topic id GUID mapping, but I'm hoping for an easier solution.

**Comment by EWSoftware** [comment]
This isn't something I'm familiar with and isn't supported natively by SHFB since it doesn't use numeric help context IDs like that.  It's possible you could automate the process by creating a plug-in for SHFB that loads the manifest file and generates the help compiler header file that maps the GUIDs to a sequential numbers and adds it to the proper place in the help compiler project file settings during the build.

One problem with doing it automatically is that as the API changes over time, the IDs would potentially change as well as types and members were added or removed.  If you want them to remain constant, you'd have to manage the mapping file manually and just have the plug-in insert it into the project file during the build.

**Comment by keithalewis** [comment]
Thanks for the quick response. I was hoping to avoid doing this:
https://github.com/keithalewis/xll/blob/master/xll/maml/document.cpp#L225.
Looks like that is the only way.

**Comment by EWSoftware** [comment]
If all you're generating is MAML topics, the topic ID can actually be anything you want.  GUIDs are just convenient since they're unique when adding new topics.  If you manage them carefully, you can assign non-GUID values such as numbers or more human-readable text to be the ID.  I don't know if that helps at all but thought it might be worth mentioning.

**Comment by keithalewis** [comment]
Thanks for your help. I will eventually create a build process add-in, but for now I will modify your Help1x.hpp template to include alias and map sections.
https://github.com/keithalewis/xll12/blob/master/TODO.txt
