### ISSUE TITLE
Xamarin unresolved assembly reference

### ISSUE THREAD

**Issue by MaykDEV** [EWSoftware/SHFB#652]
Hello,

I've tried to generate an help file using your tool but unfortunately it crashed.
The error that it gave me was (`BE0043`).
Error:
> `MRefBuilder : error : Unresolved assembly reference: Xamarin.Forms.Xaml (Xamarin.Forms.Xaml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null) required by JohnDoeCS [C:\Users\JohnDoe\docs\Help\Working\GenerateRefInfo.proj]`

## How did i get this issue:
Added Xamarin.Forms.csproj to documentation source
Tried include subfolders but no success 

## Installation / Tool setup
Visual Studio 2017 Enterprise V15.8.5
Xamarin 4.11.0.776
SHFBVisualStudioPackage_VS2015AndLater.vsix (latest build: checked at 8 oct 2018)
Guided installer v2018.7.8.0

## Build Setup
![image](https://user-images.githubusercontent.com/17426430/46653366-24f75a00-cba6-11e8-803b-b57ef32c4ed5.png)

## Visibilty Setup
![image](https://user-images.githubusercontent.com/17426430/46653257-d21da280-cba5-11e8-84f0-65b6c5dc78d3.png)

If more information needs to be provided let me know and i'll try to respond as fast as possible.

Thanks in advance!

PS: SHFB rocks!!

**Comment by EWSoftware** [comment]
I'm not familiar with Xamarin projects but there are a couple of things you can try.  Since it is Xamarin, have you tried the Cross-Platform option for the Framework Version SHFB project property?  Also, are you using the assembly as the documentation source or the solution/project?  If using the solution/project, it should auto-detect the framework version and include any necessary references.

That said, there are some issues with some of the newer frameworks and detecting all of the necessary reference assemblies.  If you can't get it to work and can attach an example, I'll take a look at it.

**Comment by MaykDEV** [comment]
Thanks for the fast response much appreciated, The main reason it doesn't seem to work as far as I have noticed (Xamarin.Forms.Xaml.dll) can't be reflected at least that is what I interpret based on the error. 
But i haven't tried that yet thanks for the tip!!
I'll let you know more if i stumble into more.

**Comment by EWSoftware** [comment]
Since it's an unresolved reference, it either can't find it at all or it found one but it's the wrong version.  The build log should list which references are being included.  If it is listed, you can probably use the path in the log file to find it and find out what version it is.  In that case, you may be able to use the Assembly Binding Redirection plug-in to redirect it to the version it's looking for.

**Comment by EWSoftware** [comment]
There were some issues with the package resolver not including all the reference assemblies from a package reference.  That's what was causing this issue.  It is fixed for the next release.
