### ISSUE TITLE
Too small default font sizes of generated documents

### ISSUE THREAD

**Issue by wmjordan** [EWSoftware/SHFB#660]
Nowadays many programmers have gotten high definition monitors.
The default font sizes of generated documents maybe too small on them.
Could you please change or provide an option to the base font size value so the text of generated documents could be easier to read?

**Comment by EWSoftware** [comment]
That's a function of the style sheets in the presentation styles.  I'm not sure if there's a good way to control that through an option since many elements have a font size (headings for example).  You can [include a customized version of the style sheet](http://ewsoftware.github.io/SHFB/html/77d2d693-db84-4ae3-a84c-e33c71f92e9a.htm) to adjust the sizes as you see fit.

**Comment by wmjordan** [comment]
I knew that we can customize the style sheets.
However, providing a better default set of style sheets benefits all users. The current set of styles are more than a decade before.
As you can see on the modern MSDN, they have enlarged the font sizes, like the following pages.
https://docs.microsoft.com/en-us/dotnet/api/system.io.textwriter?view=netframework-4.7.2

**Comment by EWSoftware** [comment]
If you have suggestions for updated style sheets, feel free to submit them in a pull request.  The same goes if someone wants to submit an updated or new presentation style.
