### ISSUE TITLE
html does not contain all namespaces

### ISSUE THREAD

**Issue by jmecosta** [EWSoftware/SHFB#663]
hi,

i cant get the html to look the same as the chm. chm contains 2 namespaces and html contains only one.  If i split them in 2 projects they are created correctly, if i join them only the ReqApi shows up.

ive tried several combinations but only if both are in different shproj they get created

"d:\prod\fabsuitedocgenerator\TeklaFabSuiteAPI_Reference.shfbproj" (default target) (1) ->
(CoreBuildHelp target) ->

**Comment by EWSoftware** [comment]
Do you mean the website output?  There should be no difference between the two output with regard to content if building from the same project.  Both outputs can be selected to build at the same time and their content should be the same.

**Comment by EWSoftware** [comment]
There shouldn't be any difference and I've never seen it happen.  Can you provide an example that shows the issue?

**Comment by jmecosta** [comment]
I do have to ask if i can publish it.

**Comment by EWSoftware** [comment]
You can e-mail it to me if you prefer to keep it private.

**Comment by TomasJosefi** [comment]
Hi, I want to ask, if this issue was accepted as a bug or not. I have the same problem. chm documentation contains all namespaces, but html only one of them. There are html files with documentation for all namespaces generated in html subfolder, but only one is visible in help tree in index.html and neither clicking on root node is displaying other namespaces. I think this issue was discussed 4 years ago here: https://stackoverflow.com/questions/25198190/sandcastle-html-output-multiple-namespaces

**Comment by EWSoftware** [comment]
@TomasJosefi  I have received no further information nor a test case with which to reproduce the problem.  The issue you linked to was resolved a long time ago.  If you can provide an example that demonstrates the problem in the current release, I'll look into it.

**Comment by jmecosta** [comment]
I'm still waiting confirmation from my side to see if I can provide the
project

**Comment by TomasJosefi** [comment]
I can provide the result of Sandcastle build. If you acknowledge that there is something wrong, I can prepare some example of sources and project if needed.
Please try to look at attached zip. There is Documentation.chm with 6 namespaces. But when you open index.html, there is only one namespace.  Thank you
[Help.zip](https://github.com/EWSoftware/SHFB/files/2740201/Help.zip)

**Comment by EWSoftware** [comment]
Are either or both of you perhaps viewing the output using the View Ouput (Local File System) option?  If so, that would explain the problem since all browsers but Edge will block the scripts from running when loaded directly from the file system.  If you use the View Output (Local Web Dev) option to view the output it'll run it through the local development web server and will work as if you had uploaded it to a full web server.  If uploaded to a full server, you should also see the full set of TOC entries.

**Comment by jmecosta** [comment]
yes, I can confirm this is the case. Thanks for the help. Previous time, i was using a http server so i did not notice this.

**Comment by TomasJosefi** [comment]
Yes, you are right. Using Local Web Dev option it's working correctly. Thank you for your help.
