### ISSUE TITLE
E-mail address in Markdown output

### ISSUE THREAD

**Issue by akesseler** [EWSoftware/SHFB#668]
When I compile the API docs as MD 
- without adding an e-mail address, then I get an empty e-mail link in the footer.
- with adding an e-mail address, then I get an unclickable `mailto` link instead.

Affected configuration fields: "Feedback e-mail address" and "Feedback e-mail link text"

Note: CHM generation works fine and as expected.

**Comment by EWSoftware** [comment]
I've fixed the formatting of the e-mail address so that it appears correctly when specified.

Not specifying an e-mail address will still result in an empty link.  This is a limitation of the markdown format.  The footer has to be defined in a single file rather than being part of each topic so it can't use resource items like the other formats do.  If you want to modify the format of the footer, add a copy of [_Footer.md](https://raw.githubusercontent.com/EWSoftware/SHFB/master/SHFB/Source/PresentationStyles/Markdown/MarkdownContent/_Footer.md) to your SHFB project, make sure it's Build Action is set to Content, and remove the e-mail link line.
