### ISSUE TITLE
Unresolved assembly reference: System

### ISSUE THREAD

**Issue by brianke** [EWSoftware/SHFB#67]
I am trying to generate HTML for a project and am getting the following error:

GenerateRefInfo:
  MRefBuilder (v2015.1.12.0)
  Copyright c 2006-2015, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2014, Eric Woodruff, All Rights Reserved.
  Loaded assembly binding redirect: System, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Version(s) 2.0.5.0 redirect to Version 4.0.0.0
  Loaded 1 assemblies for reflection and 6 dependency assemblies.
MRefBuilder : error : Unresolved assembly reference: System (System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes) required by SimpleMvvmToolkit-Common [C:\Projects\SandCastle\Help\Working\GenerateRefInfo.proj]
    Last step completed in 00:00:01.7897

I have found various references to using the API to Redirect Assembly binding to the 4.0.0.0 version but when I add the following it doesn't change anything (I still get the error above):

![image](https://cloud.githubusercontent.com/assets/925682/7095065/09329ae2-df95-11e4-9d59-49b24dd137d2.png)

If I ignore this file rather than redirect it, the help file will build but I am not sure if I am losing something by ignoring the file.  Is there a way to properly redirect the file/version so that it builds without ignoring the file?

**Comment by EWSoftware** [comment]
Version 2.0.5.0 is typically a Silverlight or portable framework assembly.  Set the SHFB project's Framework Version property to the appropriate Silverlight or .NET Portable framework.  If you use the Visual Studio solution or project as the documentation source rather than the assembly itself, SHFB will figure out what settings to use and correct the framework version automatically if necessary.

**Comment by brianke** [comment]
I am using the Visiual Studio project as the documentation source but it doesn't appear to be using the correct framework.  Is there some way to add the 2.0.5.0 framework to the SHFB project so it can use the correct version?

Also, if I choose to ignore this System.dll if it cannot be resolved, what are the ramifications (as opposed to redirecting it)?  Will it not document some of my project?

**Comment by EWSoftware** [comment]
The *SimpleMvvmToolkit* assemblies appear to be built against the .NET Portable framework which is retargetable and can be reused in projects like yours that target .NET 4.5.1.  However, their reference information still refers to the portable assembly strong names.

You can chose to ignore the missing references (*System*, *System.Runtime.Serialization*, and *System.Core*).  All it will do is leave out potential base class member information for any documented classes that derive from types in the affected assemblies.

You'll also see a lot of warnings from the Resolve Reference Links component about unresolved member IDs.  That's because the toolkit assemblies aren't included as documentation assemblies.  Typically you don't want them included so you can safely ignore the warnings.  If you find them bothersome, you can use the Additional Reference Links plug-in to suppress them.

**Comment by brianke** [comment]
Thanks for the quick answers.  I do have a couple questions:

- How would I suppress the "Resolve Reference Links Component" warnings?  I am not sure what to add to the Additional Reference Links plug-in when it is expecting a SHFB project file.  Would this be a help file for the SimpleMVVMToolkit?

- If I didn't want to add the Additional Reference Links plug-in, is there a way to suppress the "Resolve Reference Links Component" warnings?

- I have this error "ShowMissingComponent: [F:CustomTabTest.CustomerView.LayoutRoot] Missing <summary> documentation".  CustomerView is a WPF XAML file (and associated xaml.cs file).  In the cs file I have the following and am not sure how to resolve this warning:

namespace CustomTabTest
{
    /// <summary>
    /// Interaction logic for CustomerView.xaml
    /// </summary>
    public partial class CustomerView : UserControl
    {
        /// <summary>
        /// CustomerView default constructor
        /// </summary>
        public CustomerView()
        {
            InitializeComponent();
        }
    }
}

**Comment by EWSoftware** [comment]
There is no other way to suppress the reference link warnings.  To use the [plug-in](http://ewsoftware.github.io/SHFB/html/15b6b7be-3778-4487-b524-d558d02e6460.htm), create a separate SHFB project and add the assemblies with the types from the warnings as the documentation sources.  If the project is included in a solution, you can set the build configuration so that it is never built.  It is just used by the plug-in.

Add the Additional Reference Links plug-in to your main SHFB project, and configure it by adding the reference project created above and setting the link type to None.

Regarding the LayoutRoot missing documentation warning.  It's probably an auto-generated property.  If you don't care to see it, you can use the API Filter to remove it from what gets documented.  If you want it documented, you'll need to manage the comments using a separate XML comments file that you keep up to date separately.
