### ISSUE TITLE
Enums and Delegates are recognized as a class when building from Visual Studios, but are recognized properly when built from SHFB GUI

### ISSUE THREAD

**Issue by iShorty123** [EWSoftware/SHFB#673]
As the title says, that is the issue I currently have. I'm not sure what details I need to give you, but I am using v2018.12.10.0.

When I build from the GUI it correctly identifies enums and delegates, but when I build from Visual Studios 2017 Community by rebuilding my entire solution (I have it set up so Sandcastle is dependent on my project that I am documenting and so it's built after it, so order should not be a problem here), it does not identify enums and delegates correctly. It instead labels them as classes. 

I saw from an earlier issues that this can occur if .NET versions don't match between projects and Sandcastle. I have double checked this and all versions are using .NET 4.7.1.

Let me know if you need more info or not! Until then I will just continue to build with the GUI. Thanks!

**Comment by EWSoftware** [comment]
The build engine used in Visual Studio is the same one used by the standalone GUI.  That said, if you didn't update the Visual Studio package, it might be using outdated assemblies since it does contain local copies of some of the assemblies.  You might try removing the Visual Studio extension and installing it again using the VSIX installer that came with the standalone version you installed.

It might also be worth checking that the SHFBROOT environment variable is pointing to the right location and also that there isn't a SHFBROOT project variable that's pointing somewhere different.
