### ISSUE TITLE
Support for redirecting MSBuild to reference assemblies.

### ISSUE THREAD

**Issue by Delpire** [EWSoftware/SHFB#677]
Another issue I am having with SHFB is allowing it to use a location other than Program Files (x86) for the Referenced Assemblies.

I don't know if this will be easy to change, but MSBuild allows you to use a property called FrameworkPathOverride to point MSBuild to the .NET Reference assemblies. This works great on our build machines as we can keep the software stack small, and simply pull down the reference assemblies locally and point MSBuild to the location of these assemblies.

The issue is that this does not work with SHFB. The SHFB .NET Framework reflection data files all have this "hard coded" location path:
`<Location Path="%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5">`

This is fine if .NET is installed on the machine, but if we want our builds machines to have as little state as possible, then this path will not allow us to pull things down locally for our builds.

Maybe there is already a solution to this that I don't know about, but if not, it would be nice to be able to replace these paths with our own.

**Comment by EWSoftware** [comment]
The build tools need to know where the assemblies and related XML comments files are.  This information is stored in the reflection data set information files.  The simplest solution is probably to clone the relevant data set folder (for example the *%SHFBROOT%\\Data\\.NETFramework* folder) and put it in a common location or a sub-folder within the project.

Copy the relevant *.reflection* file for the framework version you want to a new name, and then edit it to change the `Title` attribute so that it's unique and the `Path` attributes so that they point to your copies of the assemblies.

Once that's done, update the Component Path property in the SHFB project to point to the folder containing your custom reflection data set.  This is not necessary if you put it in a subfolder under the project folder as it scans those automatically.  You should then be able to choose it in the Framework Version dropdown.
