### ISSUE TITLE
Use of <para> tag

### ISSUE THREAD

**Issue by bubbakittee** [EWSoftware/SHFB#693]
The documentation for the para tag says that the first block of text (i.e. the first paragraph in a sequence) does not need to be included between para and /para tags.

However, if I omit these tags, I don't get any spacing between my first and second paragraphs in either CHM or website output. 

And, I have noticed that many examples in the SHFB pages *do* use para tags on the first paragraph in a "Remarks" section.

I have a large quantity of documentation, so I'd like to avoid adding extra para tags to it. Advice, please?

**Comment by EWSoftware** [comment]
If you only have one paragraph or a single sentence, they can be omitted.  If you have multiple paragraphs, include them on each paragraph to get proper spacing.

**Comment by bubbakittee** [comment]
OK. Thanks. But I think the text [here ](http://ewsoftware.github.io/XMLCommentsGuide/html/c7973ac7-5a4f-4e4d-9786-5ce659ac8e24.htm)is a bit misleading. It says "The para element on the first block of text is optional". To me, that says that the first paragraph (even if there are several) can omit the para tags. 

Anyway, I appreciate the quick reply and all your other fine work. Thanks again.

**Comment by sharwell** [comment]
@bubbakittee You may find [DotNetAnalyzers.DocumentationAnalyzers](https://www.nuget.org/packages/DotNetAnalyzers.DocumentationAnalyzers) helpful for this. It has [style rules](https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/StyleRules.md) DOC100, DOC101, and DOC102 to help with the consistent use of paragraphs in order to avoid presentation differences like this.

**Comment by EWSoftware** [comment]
I've clarified the `para` example to note that it's only optional if it's the only text within the parent element such as the `summary` tag in the example.
