### ISSUE TITLE
HowTo get value of attribute for description of class by XPath?

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#694]
Is there a way to reference a value of an attribute in the XML comment of class?

Current class code:
```cs
/// <summary>
/// Database connector class
/// </summary>
/// <remarks>
/// Requires database schema version 1.6.
/// </remarks>
[DataVersion("1.6")]
public class DatabaseConnector
{
  // ...
}
```

Some kind of sample code im looking for to reference the "1.6" from attribute:
```cs
/// <summary>
/// Database connector class
/// </summary>
/// <remarks>
/// Requires database schema version <shfb-reference-tag xpath="../attributes/attribute[type[api='T:ObjectModel.DataVersionAttribute']]/argument/value"/>.
/// </remarks>
[DataVersion("1.6")]
public class DatabaseConnector
{
  // ...
}
```

Is there something like the ``shfb-reference-tag`` ? And if so, how to reference the value of the ``DataVersionAttribute``?

Or may be there is an other way to reference it in XML comment?

**Comment by EWSoftware** [comment]
The best approach is probably to write a build component which could process the custom tags and insert the attribute value in place of the custom tag.  It could function something like the code block component which scans for `code` elements and replaces them with the colorized code.  The syntax of the custom element could probably be simplified since the format and location of the value should be constant within the topic metadata.  You'd probably only have to specify the type name of the attribute to find.  For example `<attributeValue type="T:ObjectModel.DataVersionAttribute" />`

By using a build component, you could add it to the projects that need it and you wouldn't have to change any of the presentation styles.
