### ISSUE TITLE
Want to add a front page in document, which will tell about the author, creator and version of that document.

### ISSUE THREAD

**Issue by shourabhshukla** [EWSoftware/SHFB#718]
Want to add a front page in document, which will tell about the author, creator and version of that document. This front page need to be generated every time with document and should be placed in the front page of the document. Could you please help in this how i can achieve this?

Thanks in ADvance :)

**Comment by EWSoftware** [comment]
Add a content layout file which lets you add [conceptual content](http://ewsoftware.github.io/SHFB/html/3d4edd2d-7883-4508-b9d2-bd7b4d848b0d.htm), topics that are authored by you rather than being produced from the API.  If you create a brand new SHFB project, it creates a default welcome topic.  That can be used as an example.
