### ISSUE TITLE
Documentation for building missing SHFB

### ISSUE THREAD

**Issue by kant2002** [EWSoftware/SHFB#731]
Wiki page which lists all documentation, missing globally available `%SHFBROOT%` variable, which most of the tie indicate that SHFB Tools globally installed.

**Comment by kant2002** [comment]
Also I have to modify MasterBuild.bat to run build on system where VS2017 does not installed. I will provide PR for that. Another note, is that project build failing now for me at:
```
MRefBuilder : error : An error occurred while loading assemblies for reflection. The error message is: Could not find a part of the path 'C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0'. [C:\Users\kant\AppData\Local\Temp\tmpA1B0.tmp\BuildReflectionData.proj]
```
I do not have FSharp workload installed on my machine as well. Maybe it also should be noted in the Wiki page.

**Comment by EWSoftware** [comment]
Which wiki page are you referring to?  Regarding the F# assembly reference, that's needed in order to build the reflection data set.  If you don't have or don't want to install it, you can just copy the reflection data set files from an installed copy of the tools or extract them out of the reflection data set NuGet packages.

**Comment by kant2002** [comment]
I'm referring to https://github.com/EWSoftware/SHFB/wiki/System-Requirements-and-Building-the-Code

I think it would be good to capture all these small quirks in that document, so in case somebody would be in my place, it would be easier to build.

**Comment by thelastofreed** [comment]
So, for those that are having issues building the project, I had problems at first too.  However, in order to resolve the problem, I used the nuget command line tool to download the "Microsoft.Build.Utils.Core" version 14.3.0 nuget package onto my computer:

```
 nuget install Microsoft.Build.Utilities.Core -Version 14.3.0
```
Then, I opened the visual studio developer command prompt as admin and used the gacutil command to install the "Microsoft.Build.Utilities.Core.14.3.0" and "Microsoft.Build.Framework.14.3.0" to the gac on my for my machine:

```
gacutil /i "C:\Temp\nubuild\Microsoft.Build.Utilities.Core.14.3.0\lib\net45\Microsoft.Build.Utilities.Core.dll"
gacutil /i "C:\Temp\nubuild\Microsoft.Build.Framework.14.3.0\lib\net45\Microsoft.Build.Framework.dll"
```

THen, just close and relaunch the visual studio developer console, set the working directory as the root of the cloned project, and run the script:

```
.\MasterBuild
```

**Comment by EWSoftware** [comment]
@kant2002 SHFBROOT and the option to copy the reflection data from an installed version are already mentioned.  Can you provide more specifics on what info you found to be missing?

**Comment by kant2002** [comment]
F# workload required to build would be good to have I believe.
