### ISSUE TITLE
Google Analytics Global Site Tag causes build error

### ISSUE THREAD

**Issue by Pelican7** [EWSoftware/SHFB#736]
When adding Google Analytics, using the Global Site Tag method shown below causes a build error. The below code is added to the Website Ad Content, as described here https://github.com/EWSoftware/SHFB/issues/727.

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXX-X"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXX-X');
</script>
```

A solution is to use the analytics.js method rather than the Global Site Tag.

**Comment by EWSoftware** [comment]
The fragment is inserted into an XML file for the build.  The `async` attribute causes it to appear that the XML is not well-formed and cannot be loaded.  If you remove the `async` attribute it works as expected though it won't load that script asynchronously.  You could try setting it to a value so that it is well-formed XML although I don't know if that changes its behavior in the browser.
