### ISSUE TITLE
Image links broken in Help Viewer

### ISSUE THREAD

**Issue by IcarusHH** [EWSoftware/SHFB#76]
I’m developing a custom build component aimed to add LaTeX contents to documentation files. When the component encounters a `<latex>` node in an XML document, it creates a corresponding image, say eq_1.png, replaces the node with the following

`<img src="../icons/eq_1.png" alt="LaTeX Equation" />`

and copies the PNG file to the "icons" subfolder of the selected help outputs.
Such approach works fine when the help output is OpenXml, HtmlHelp1, or Website; however, when the output is MSHelpViewer, the image file is missing. By inspecting the html files generated by SHFB, it can be observed that the XML emitted is as follows.
HtmlHelp1:

`<img src="../icons/eq_1.png" alt="LaTeX Equation" />`

Website:

`<img alt="LaTeX Equation" src="../icons/eq_1.png"></img>`

The latter is also the code emitted in the MSHC file. After the insertion of the container in the Help Viewer (Version 2.1), the `<img>` node becomes:

`<img src="ms-xhelp:///?method=asset&amp;id=..\icons\eq_1.png&amp;package=SAMPLEDOCUMENTATION.mshc&amp;topiclocale=EN-US" alt="LaTeX Equation" title="LaTeX Equation" />`

Is this the expected behavior? Any suggestions in order to obtain the right output?

**Comment by EWSoftware** [comment]
Yes, this is the expected behavior.  If you check the presentation styles, there is a separate content item file specific to MS Help Viewer that contains a set of elements with different paths for icons, style sheets, and scripts.  They leave off the leading "../".  The Shared Content Component replaces the resource item references with the text of the reference items.

The help viewer transforms the topics and changes the paths to resources like icons so that it can find them in the installed collection.  File paths in help viewer before transformation are relative to the root, not the topic being viewed.

If you change your build component to emit an includeAttribte element and reference the icon path resource item the Shared Content Component will generate the correct path regardless of the help file format.  The XSL transformations for the presentation styles contain several examples.  Something like the following should work:

``` XML
<img alt="Latex equation">
  <includeAttribute item="iconPath" name="src">
    <parameter>eq_1.png</parameter>
  </includeAttribute>
</img>
```

**Comment by IcarusHH** [comment]
Many thanks for the reply: by adding a new transformation matching latex nodes now I am in control of their Html representation. This closes the issue, for me. However, I would like to signal that I was unable to find an item named “iconPath” in the Content subfolder of the OpenXml presentation style, hoping this will help.

**Comment by EWSoftware** [comment]
Open XML is a little different since it post processes the image elements.  Its transformations concatenate the literal path "../media" with the filename since all images end up there in the generated document.  I'll add the item for the next release so that its there for components that expect it.
