### ISSUE TITLE
WebSite Table of Contents starts expanded and stays that way in every browser besides Edge

### ISSUE THREAD

**Issue by ristogod** [EWSoftware/SHFB#760]
Whenever we generate the website, when we load the index.html file from the Help folder, the site starts with the ToC already expanded to the first namespace. So you don't see all the other namespaces. Then when you try to click the very top node, it won't reset and therefore we cannot navigate through the documentation API.

This happens when we use Chrome, Firefox and Internet Explorer.

However, if we run the site using Edge, it works fine.

**Comment by EWSoftware** [comment]
Most browsers block script from running when opened from the file system.  Edge seems to be the exception.  Use the local web server option in SHFB instead to view the content.  I need to remove the file system option since it has too many issues now with the security measures in place in most browsers.
