### ISSUE TITLE
Sticky TOC in HTML Output

### ISSUE THREAD

**Issue by ritchiecarroll** [EWSoftware/SHFB#782]
Hi Eric,

Is there a flag I can enable in the Sandcastle project file that I can use to make the table of contents be fully expanded and stay in sync with current page - like the "Track Active Item in Solution Explorer" in Visual Studio or more like the way the MS .NET web site docs work? I've not found the option if so.

Currently I find it's easy to lose context and/or not be able to see related items at the current spot in the namespace without re-navigating from top/down when most of the namespace hierarchy is disappearing.

If this is not an option, I imagine it could be difficult to to retain a full state of expanded pages between calls, however, even just either fully expanded state or expansion to current page/level with visible children would be useful. I am guessing you've considered this already and it may be more complex than I realize and/or a performance issue?

Thanks,
Ritchie

**Comment by EWSoftware** [comment]
No, there is no option for that.  Each page contains a fragment of the TOC, it sibling topics and the parent.  Expanding the parent shows the other nodes at that level as you work your way up.  It's based on how the MSDN site used to work.

Expanding what is in the fragment by default could probably be accomplished by reworking how the lightweight website style plug-in generates them but it isn't something I have pursued.  Creating a presentation style to match the current Microsoft Docs site is a lot of work and since web development isn't by forte, I just haven't found the time to invest in doing so.

**Comment by ritchiecarroll** [comment]
Thanks Eric,

Understood. If I find some spare time that I can invest I will contact you again and see if we could coordinate on an update here (with me doing as much of the work as possible under your guidance).

**Comment by ritchiecarroll** [comment]
So I did a quick examination of the current HTML used by Microsoft .NET APIs and even the new DocFX tool. From what I've seen, I think at least from the HTML part of this, it wouldn't be too bad (_famous last words, lol_). With this insight I started trying to see if I could understand the rendering process in SHFB, focusing on VS2013 for HTML. What follows is my interpretation (as Alice went into the rabbit hole), with the intention that you can help course correct any of my personal misinterpretations:

As background, I have successfully tweaked output presentation styles a little by messing with custom CSS by overriding the `branding.css` in my SandCastle projects. This was a fairly trivial exercise, for example, here is a deployment on GitHub pages updated to try to match the standard "Cayman" Jekyll-based theme: https://gemstone.github.io/common/help/

To move to a model that more closely matches what Microsoft is doing (in 2020 at least) for its dotnet APIs, e.g., [System.Int16](https://docs.microsoft.com/dotnet/api/system.int16), it has the following major rendered parts:
1) Header
2) Body, 3-sections with size responsive layout:
   1) Table-of-contents
   2) Main section (XML help detail)
   3) Quick bookmarks
3) Footer

This layout has a neat CSS-driven `light` / `dark` / `high-contrast` instant theming option and picking your "default" code sample target, e.g., `C#`, `VB`, `F#`, etc., is out of a drop-down list, not on tabs - here I noticed if the sample for the target language wasn't available it just fell back on `C#`.  Certainly you wouldn't have to target _all_ features, but getting something operating with a responsive layout that looked and operated **very** similar is manageable.

From a **content** perspective, the SHFB existing produced documentation results are very close (_but I guess that should have been obvious since the content source is the same_). The key differences are format, style and section arrangement plus a complete table-of-contents tree that is always _only_ initially expanded to current item. Another key difference is in the table-of -contents layout, this operates on a standardized model like the following:

1) Target Member (i.e., class/struct/enum, etc.) <- _Not a link just a TOC tree container_
   1) Target Member  Overview <- _Link_
   2) Constructors <- _Link (if any constructors)_
   3) Fields <- _Not a link just a TOC tree container (visible if any fields)_
      1) Field1 <- _Link to field details_
      2) Field2 <- _Link to field details_
      3) etc.
   4) Properties <- _Not a link just a TOC tree container (visible if any properties)_
      1) Property1 <- _Link to property details_
      2) Property2 <- _Link to property details_
      3) etc.
   5) Methods <- _Not a link just a TOC tree container (visible if any members)_
      1) Member1<-  _Link to member details_
      2) Member2 <- _Link to member details_
      3) etc.
   6) Operators <- _Not a link just a TOC tree container (visible if any operators)_
      1) Operator1 <- _Link to operator details_
      2) Operator2 <- _Link to operator details_
      3) etc.
   7) Explicit Interface Implementations <- _Not a link just a TOC tree container (visible if any explicit items)_
      1) EII1 <- _Link to explicit interface implementation details_
      2) EII2 <- _Link to explicit interface implementation details_
      3) etc.

> _This may not be an exhaustive list of major target item member sections, but it's all I initially noticed._

So again, from an HTML only perspective, this seems very doable, but my missing link was how SHFB "renders" all this. Certainly, given my prior experience messing with CSS, the styling part would be a more simple approach - but because the changes are more substantive that just style, I needed to better understand the rendering process. 

I started with the `StandardPresentationStyles` solution. Here I found the core DLL that seems to drive the UI selection of "output theme" types. However the actual rendering does not seem to be in this DLL. From what I "think" so far, the rendering works by way of XSL transforms, specifically using the `ApplyVSDocModel.xsl` and `CreateVSToc.xsl` which seems to be the linchpin for all the output themes that brings all the rendering work together, **_yes_**? 

I found these XSL transforms in the `XslTransform` solution. So as for guidance, to accomplish a new TOC with a structure similar to above, I believe you would need a new `CreateVSToc.xsl`, e.g., `CreateMS2020Toc.xsl`, **_yes_**?

Anyway, I am looking to find some time to start this process. I would like to make the TOC operate in a similar manner, plus add the on-page theming options - although I would also like a fourth option for "Cayman", so the rendered pages match better with GitHub pages.

Please feel free take this conversation offline, would like to discuss options for updates. I suppose fork with pull-request model, etc. is a workable option for you?

Thanks!
Ritchie

**Comment by EWSoftware** [comment]
If the more immediate goal is to just show more stuff in the TOC fragment, a simpler start would be to perhaps modify what the [lightweight website style plug-in](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderPlugIns/LightweightWebsiteStylePlugIn.cs) generates for the TOC fragments.  My initial thought is to just have it perhaps walk up the TOC tree adding the siblings of the parent nodes as it goes to the fragment thus giving you more definition up front rather than having it expanded and rendered as each node is manually expanded.  It's been a while since I looked at it so perhaps I'm oversimplifying the changes needed.

Getting a presentation style that approximates the newer Microsoft Docs sites would require creating a brand new presentation style.  The TOC transform would change and also the document model transformation (ApplyVSDocModel.xsl) would have to be replaced since overloads topics no longer get a parent topic and sub-topics for each overload.  Instead, they're just handled like general member pages with all the overloads listed in a single topic.  Those changes also affect the presentation style transforms as they base their output on what type of page they are rendering (namespace list page, type member list page, member page, etc.).  The lightweight website plug-in would probably also be replaced.  Whether it's a variation of that or something entirely different and better, I don't know.  Also note the breadcrumb trail at the top of the page though for SHFB that would probably be a link to the root topic and any parent nodes of the current topic up to the root.

There are some high level topics on the tools under the [Sandcastle Tools topic](http://ewsoftware.github.io/SHFB/html/1f2caa70-729b-48e1-9a9c-b612efd2f3b7.htm).  That will give you a general overview of the build process.  I haven't gotten around to filling out the topics on most of the tools themselves yet and unfortunately, the links to the old Sandcastle blog topics are dead now.

Feel free to contact me by e-mail to discuss how all this works in more depth.  My e-mail address is in the footer of the pages in the help topics.  As for submitting changes, fork and pull requests will work.
