### ISSUE TITLE
Support for docker

### ISSUE THREAD

**Issue by jazpearson** [EWSoftware/SHFB#794]
I couldn't find any documentation around this, so was wondering if there was any support for creating chm files inside docker containers?

Sandcastle requires the HTML Help Workshop, which requires Internet Explorer..... and IE isn't (as far as i know) something you can install in a docker container.

**Comment by jazpearson** [comment]
Looks like we'd need to create a website rather than a chm file....

**Comment by NETSphereSoft** [comment]
As I know the IE is still installed in Docker containers from Microsoft as I inspected last days.

Could not get HTMLHelp get installed, but would be possible to extract that archive to the expected path. But don't know how SHFB detects the installation of HHC or uses it a default path?

Another question would be - is there an quiet mode installation possible? Was trying it with msiexec /i SandcastleHelpFileBuilder.msi /quiet /norestart but installation didn't finish.

**Comment by EWSoftware** [comment]
The guided installer just searches for the folder "HTML Help Workshop" under the Program Files folder.  If it finds it, it assumes it's installed.  The SHFB build tools do the same thing.  Quiet mode should work since it's just a function of the MSI file rather than anything specific to the SHFB tools.
