### ISSUE TITLE
Upgraded project does not build: components/plugins not found.

### ISSUE THREAD

**Issue by obiwanjacobi** [EWSoftware/SHFB#801]
I have[ this old project](https://github.com/obiwanjacobi/vst.net/tree/master/Source/Docs/Jacobi.Vst.Docs) I want to generate .md's for but I get an error building the project (VS2019) saying it cannot find plugins and components. I had no errors during install.

Suggestions what I may try?

**Comment by EWSoftware** [comment]
A lot has changed since SHFB 1.8.  Most significantly, the components and plug-ins are now MEF components so their IDs have changed.  Also, many have had their configurations modified and the older configurations will no longer work.  In such cases, remove them from the project, add them back in so that they are current and have the latest configuration settings, and reconfiguring them to get them working again.  In the case of the data caching build components, you will have to delete and recreate the caches as well.

You can browse through the [release notes with breaking changes](http://ewsoftware.github.io/SHFB/search.html?SearchText=%22breaking%20changes%22), for the release after the old version being used to the latest to find things that require such updates.
