### ISSUE TITLE
Unexpected error detected in last build step

### ISSUE THREAD

**Issue by Nick-Nich** [EWSoftware/SHFB#805]
Hello. I've downloaded sfml.net 2.5 and encountered a problem with compile `../doc/sfml.shfdproj` into the chm file. Error decription is 
 `Unexpected error detected in last build step`. I read build log and found problem with `doc/Working/reflection.xml`, but I so far from XML as much as possible. Of cource LastBuild.log file attached. I am asking for a help with compilig it. I use VS 2019 
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/4875374/LastBuild.log)

**Comment by EWSoftware** [comment]
The log file doesn't help much though I can tell you it just builds a help file with some conceptual content so there shouldn't be a reflection.xml file in it anyway.  Since there's no API content, you can probably find the info online at their project site.  I suggest just removing the SHFB project from the build for the time being.  You'll need to contact the SFML project owners if you're having trouble getting their projects to build.  They may need to update their SHFB project to the latest release but I can't do that for you.

**Comment by Nick-Nich** [comment]
So the problem isn't in my compilers. It's just that the problem is lack of documentation about sfml.net, only in .shfbproj and .XML files. Anyway thanks for your answer.
