### ISSUE TITLE
nuget restore fails

### ISSUE THREAD

**Issue by avivanoff** [EWSoftware/SHFB#812]
This issue related to #748. If I rung the following command:

`nuget restore mysolution.sln`

it fails with

`error MSB4019: The imported project "D:\SandcastleHelpFileBuilder.targets" was not found. Confirm that the expression in the Import declaration "\SandcastleHelpFileBuilder.targets" is correct, and that the file exists on disk.`

Is **nuget restore** scenario supposed to work, or do I still have to resort to **msbuild -restore** workaround?

**Comment by EWSoftware** [comment]
Honestly, I don't know if nuget restore should work.  If msbuild -restore works, I'd use it.

**Comment by avivanoff** [comment]
I actually found a way to make it work for both NuGet restore and MSBuild restore,. Instead of

`<Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" Condition="'$(MSBuildRestoreSessionId)' != ''"/>`
`<Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" Condition="'$(MSBuildRestoreSessionId)' == ''"/>`

do this

`<Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" Condition="!Exists('$(SHFBROOT)\SandcastleHelpFileBuilder.targets')" />`
`<Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" Condition="Exists('$(SHFBROOT)\SandcastleHelpFileBuilder.targets')" />`

**Comment by tom-englert** [comment]
@avivanoff I thought of this solution, too, but discarded it because it appeard too risky to me: 

- If you did not do a restore before the build, the build of the SHFB project will not fail but silently skip when only checking for `$(SHFBROOT)`, and your output will never be updated.

So only use this if you can live with this limitation.

**Comment by tom-englert** [comment]
@avivanoff BTW, `msbuild -restore` is not the workaround, but the new MS recommended way; it always ensures that the correct nuget version is used, without mangling with the build definition every time.

**Comment by joecuevasjr** [comment]
> I actually found a way to make it work for both NuGet restore and MSBuild restore,. Instead of
> 
> `<Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" Condition="'$(MSBuildRestoreSessionId)' != ''"/>` `<Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" Condition="'$(MSBuildRestoreSessionId)' == ''"/>`
> 
> do this
> 
> `<Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" Condition="!Exists('$(SHFBROOT)\SandcastleHelpFileBuilder.targets')" />` `<Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" Condition="Exists('$(SHFBROOT)\SandcastleHelpFileBuilder.targets')" />`

Clarification where the change above has to be made: within the **.shfbproj** file.

This worked for me on Azure DevOps Server. In my situation, I'm forced to use Nuget restore since MSBuild does not work correctly for legacy ASP.NET Web Site projects. Adding package references to "EWSoftware.SHFB" and "EWSoftware.SHFB.Framework" did not correct my issue either. However, the change quoted above works well without any fuss. Thanks @avivanoff !
