### ISSUE TITLE
How to use a wildcard with API filters?

### ISSUE THREAD

**Issue by gpetrou** [EWSoftware/SHFB#824]
We are using some C++/CLI libraries and when we try to produce the documentation we get a long list of external namespaces such as:
?A0x000c5d65
?A0x00115ec7
?A0x008b4eb8
?A0x02e52892
?A0x03357cf4
?A0x05044233
?A0x07b5d984
Each of these namespaces contains only an internal struct __clr_placement_new_t.
Similarly, we have some other namespaces such as:
vc.cppcli.attributes.?A0x008b4eb8
vc.cppcli.attributes.?A0x0a4e47a1
vc.cppcli.attributes.?A0x2d3cd8d3
vc.cppcli.attributes.?A0x3777830c
vc.cppcli.attributes.?A0x3f3eba8f
vc.cppcli.attributes.?A0x52367f0d
Each of these namespaces contains only an internal class CppInlineNamespaceAttribute.
The hexadecimal names seem to differ between machines.
Is there a way to use a wildcard to exclude this long list of namespaces?
Alternatively, is there a way to exclude all namespaces and then just include the ones we want?

**Comment by EWSoftware** [comment]
There are a couple of options.  Since they follow a pattern, you can probably use the [XPath reflection file filter plug-in](http://ewsoftware.github.io/SHFB/html/cd68ef02-3493-4af6-96de-1957b0aaf858.htm) to filter out members using a `starts-with` or `contains` expression.

Another option is to use the [Documented Entities Only plug-in](http://ewsoftware.github.io/SHFB/html/1c05f8f0-71f3-420a-b546-a438c435b759.htm) which builds an API filter dynamically at build time to only include members with XML comments.

**Comment by gpetrou** [comment]
Thank you for the fast reply.
I tried `<expression>/reflection/apis/api[starts-with(@id,"vc.cppcli.attributes")]</expression>` but does not seem to work.
Using `<expression>/reflection/apis/api[contains(@id,"vc.cppcli.attributes")]</expression>` seems to work.
Does starts-with have a different syntax?

**Comment by gpetrou** [comment]
Looks like I forgot that this is a namespace, so `<expression>/reflection/apis/api[starts-with(@id,"N:vc.cppcli.attributes")]</expression>` seems to work. I think we can close this issue.
