### ISSUE TITLE
Fatal error during doc generation: ESENT Cache: Primary index is corrupt

### ISSUE THREAD

**Issue by RobertvanderHulst** [EWSoftware/SHFB#826]
I am getting the following error during doc generation.

```
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component 'Comments Index Data (ESENT Cache)'. The error message is: Primary index is corrupt. The database must be defragmented [C:\XSharp\DevRt\Binaries\obj\Help\BuildTopics.proj]
BuildAssembler : error :  [C:\XSharp\DevRt\Binaries\obj\Help\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component 'Switch Component'. The error message is: See log for details [C:\XSharp\DevRt\Binaries\obj\Help\BuildTopics.proj]
Done Building Project "C:\XSharp\DevRt\Binaries\obj\Help\BuildTopics.proj" (default targets) -- FAILED.

```

Do you have any idea what could be causing this and how I can solve this ?

Robert

**Comment by RobertvanderHulst** [comment]
I have disabled the ESENT caches and the problem is gone. In fact I have the impression that this actually makes the build faster in stead of slower.

**Comment by EWSoftware** [comment]
It could be the cache is corrupted or, depending on how old the project is, out of date with regard to configuration settings.  Generally, deleting the cached file location and letting it get recreated resolves the issue.  If it's due to an outdated configuration, deleting the cached file location and then removing, adding, and configuring the components in the SHFB project gets things back on track.

As noted in the [cached component documentation](http://ewsoftware.github.io/SHFB/html/3a1c4bf1-8ecf-4ab3-8010-277bed8d3819.htm), the database versions are for reducing memory usage rather than speeding the build.  Due to file access, they are slower than the standard in-memory cached components but will typically use a lot less memory.  Unless you're having out of memory issues during a build, the standard caching components work the best.

**Comment by RobertvanderHulst** [comment]
Thanks Eric.
Guess I should have read the docs better. "Cache" sort of raised expectations of better performance.
And memory is not really an issue for me.
