### ISSUE TITLE
Screenlayout for Codeblock component configuration cutting off parts

### ISSUE THREAD

**Issue by Hefaistos68** [EWSoftware/SHFB#830]
The buttons at the bottom are cut off and only partially visible, one has to guess whats under it.
Display at 1366x768 with 100% scaling

![SHFB codeblock](https://user-images.githubusercontent.com/8855055/103344850-b1dca580-4a87-11eb-9811-4db246930cdd.jpg)

**Comment by EWSoftware** [comment]
I'm slowly converting everything over to WPF (#344).  The property pages have been done and a few of the component configuration forms but I still need to find time to do the rest, this one included.

**Comment by Hefaistos68** [comment]
Sorry to say, I have version 2020.3.6.0 installed and the screenshot is absolutely from this version.

**Comment by EWSoftware** [comment]
I tried it on my desktop and in a VM at that resolution and scaling and didn't see any clipping.  It's WPF and I've never seen WPF not scale things correctly.  What OS are you using?  As I noted, the screen shot is showing raised buttons rather than flat style so perhaps some other system setting is affecting the layout.

**Comment by Hefaistos68** [comment]
Windows 10 Home, latest updates, Asus VivoBook 15.  For reference, the screenshot shows that the VS app settings show nice flat buttons, the SHFB settings dont. And that in the very same IDE and project.

![image](https://user-images.githubusercontent.com/8855055/113016553-821c6700-9176-11eb-9eff-cd6ca29adfde.png)

And to avoid any version doubts:
![image](https://user-images.githubusercontent.com/8855055/113016866-cad42000-9176-11eb-9535-eb6181df992c.png)

**Comment by EWSoftware** [comment]
I did a little more checking.  Try adding the IntelliSense component and the Syntax component and open their configuration forms.  Do they get clipped?  I don't see any clipping but if I'm right, for you the IntelliSense one will but the Syntax Component one won't.  I suspect there's something related to whether or not the overall set of controls are of a fixed height versus forms with controls that can vary in height.

**Comment by Hefaistos68** [comment]
You are right, but interestingly, some dialogs have flat buttons, some not.
![image](https://user-images.githubusercontent.com/8855055/113062574-dbeb5400-91ab-11eb-9a97-36b2d7b6f625.png)
![image](https://user-images.githubusercontent.com/8855055/113062655-fcb3a980-91ab-11eb-924e-21ece6afbbeb.png)
![image](https://user-images.githubusercontent.com/8855055/113062696-0f2de300-91ac-11eb-811f-1fde7afe749e.png)

Look at the difference in window layout, depending on the selection in the left list. This difference happens for all SQL and ESENT entries.
![image](https://user-images.githubusercontent.com/8855055/113062921-659b2180-91ac-11eb-90f0-bd71a689e0f8.png)
![image](https://user-images.githubusercontent.com/8855055/113062950-751a6a80-91ac-11eb-8a75-288aea541905.png)

**Comment by Hefaistos68** [comment]
ok, sorry, its bad to see here. Have to put the two screen shots side by side, one is higher than the other, both lists stretch.

**Comment by EWSoftware** [comment]
The dialogs without the icon in the upper left are Windows Forms still.  I think the issue with the WPF forms is that they are using a fixed height.  I found a setting today that tells the form to size itself to the content so that will probably fix the issue for those.  The ones with resizable content like the syntax component one must take some space away from the resizable controls so everything fits.  The property page layout is flexible too.  There's less text in the component description so the bottom text box shrinks a bit thus giving more space to the list boxes.

I'm not sure why the WPF property pages and dialogs aren't using the flat style on your system.  On mine and in a VM I use for testing, everything uses the same flat style.  I only know enough about WPF to put some basic stuff together so this sort of thing is beyond me unless I can find something that might fix it like the size to content property.

**Comment by EWSoftware** [comment]
I've applied the change that should correct this issue in the latest release.
