### ISSUE TITLE
No results for website search

### ISSUE THREAD

**Issue by MarAlder** [EWSoftware/SHFB#854]
Thanks to #853 I managed to build the XSD documentation for [CPACS](https://github.com/DLR-SL/CPACS) using SHFB 2021.4.9.0. The build process runs through and produces the website as expected. However, the search bar does not return any results. I attached the compiled documentation. Does anyone have any idea why this could be? 

[project file and compiled docs](https://dlrmax.dlr.de/get/ae1f278e-75bf-5b9a-ba40-9ec173083ced/) 

Thanks for your help!

**Update**: After uploading the documentation the search function is working fine in the [online version](https://www.cpacs.de/documentation/CPACS_development/index.html). Interesting 🤔

**Comment by EWSoftware** [comment]
When the index page or other pages from the output are opened from the local file system, the scripts are blocked for security reasons by the browser.  Use the "View Website (Local WebDevServer)" option in the standalone GUI or from within Visual Studio to view the output.  It will run it using WebDevServer or IIS Express so that scripts are enabled.
