### ISSUE TITLE
MAML XSD documentation: how to set the ID for linking?

### ISSUE THREAD

**Issue by MarAlder** [EWSoftware/SHFB#863]
Hi,

I have a question on how to link topics within an XSD documentation using MAML. According to the [link documentation](https://documentation.help/Sandcastle-MAML/53a2b7c6-a269-4916-9313-bdc301ee9398.htm) I need to set this very long string:
```XML
<link xlink:href="cfd9dabf-22f3-4742-8b54-d84404610db1">companion file</link>
```
 I found out the proper ID by copying the compiled hmtl file name `cfd9dabf-22f3-4742-8b54-d84404610db1.htm`. This works fine. Is it also possible to set an individual `id`? I'm not sure how the above ID is generated and whether it remains the same after modifying my xsd (e.g, changing the type name or so). 

In my specific example I'm trying to link to the documentation of the following XSD type:
```XML
<xsd:complexType name="pointAbsRelType">
        <xsd:annotation>
            <xsd:appinfo>
                <sd:schemaDoc id="linkID1">
                    <ddue:summary id="linkID2">
                        <ddue:para>Point with global/local reference</ddue:para>
                    </ddue:summary>
                    <ddue:remarks id="linkID3">
                        <ddue:para>PointAbsRel type, containing ...</ddue:para>
                    </ddue:remarks>
                </sd:schemaDoc>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexContent>
```` 

None of this is working. Is there a solution for this or do I need to use to the long string as in the MAML documentation?

Thanks for your help!

**Comment by EWSoftware** [comment]
I assume this is for the XSD plug-in.  Please note that I did not develop that so I can't provide much support for it.  I can tell you that each MAML topic has an ID, usually in GUID form although it can be any unique text string.  Looking at the code for the plug-in, it appears to be generating an MD5 hash of the link URI.  I didn't dig into it further to see what that actually is.  Since it names the files using the GUID, you can use that.  You'd also be able to get it by building the help at least once and then examining the HTML for the target topic.  The ID will be in the metadata in the `head` element.

Since it isn't a requirement that the ID be a GUID, you could modify the plug-in to just use the link URI value so that it is plain text.  Depending on what it actually is, you could then specify that as the ID rather than converting it to an MD5 hash.
