### ISSUE TITLE
Possible to have two separate sets of API docs?

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#865]
I have a small group of types in a single separate assembly that I'd like to have in a separate topic from those types exposed through the main set of assemblies.  Is it possible to do that?

I.e.

  - Main API docs from multiple assemblies
    - ...
  - Conceptual Topic A
  - Conceptual Topic B
    - API from a single assembly
      - ...

Thanks,
Glenn

**Comment by EWSoftware** [comment]
It should be possible with a plug-in but there's nothing identifying the assembly from which the API member came from in the TOC file.  You'd have to look that up in the *reflection.xml* file.  If it's one class and you always know it's name, you wouldn't have to do that.  The plug-in could be made configurable to let you specify that when the plug-in is added to the project and make it more generic.

The plug-in could run after the `CombiningIntermediateTocFiles` build step.  You could load the *toc.xml* file in the working folder, locate the TOC entry for the class and move it so that it's parented under the desired conceptual topic.  If it's in it's own namespace, with no other types, move the namespace topic instead.  The namespace/type members will all be children of it so moving the one entry will move them all.

**Comment by glenncarr** [comment]
Thank you.  I'll check that out.
