### ISSUE TITLE
Nuget and references to the EWSoftware libs

### ISSUE THREAD

**Issue by eschneider999** [EWSoftware/SHFB#871]
I added the EW Software libs to my ORM library to document my API, my nuget .spec file now includes them as dependencies.

Are these dependencies required now for my package/lib?

    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="EWSoftware.SHFB" version="2021.4.9" exclude="Build,Analyzers" />
        <dependency id="EWSoftware.SHFB.NETFramework" version="4.8.0" exclude="Build,Analyzers" />
        <dependency id="System.Data.Common" version="4.3.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>

**Comment by EWSoftware** [comment]
They shouldn't be there.  The SHFB packages are only used to generate documentation when you build your project so they don't need to be in the NuGet package that will be consumed by end-users since they won't be building the help content.  A help file in a NuGet package isn't really accessible so if you've built a CHM help file, you'll just need to put it somewhere they can download it.  If you build the help as website output, publish the content to a website and provide a URL to it.
