### ISSUE TITLE
Project failed to load with reference to SHFB.NetFramework

### ISSUE THREAD

**Issue by winnieXY** [EWSoftware/SHFB#872]
I'm unable to load my project after I've added the both the SHFB main package and the SHFB.NetFramework Package to the project. The resulting error (during loading the project) is:
```
D:\Git\Project\MyProject.csproj : error  : The attribute "Include" in element <SHFBComponentPath> is unrecognized.  D:\Git\Project\packages\EWSoftware.SHFB.NETFramework.4.8.0.1\build\EWSoftware.SHFB.NETFramework.props
```
BTW: I've used the current nuget packages from nuget.org (2021.4.9 for SHFB and 4.8.0.1 for SHFB.Framework). 

The line in question is the following one in EWSoftware.SHFB.NetFramework.props:
```
<SHFBComponentPath Include="$(MSBuildThisFileDirectory)..\tools\" />
```
Can you please advise what is going wrong here?

with best regards
Patrick

**Comment by EWSoftware** [comment]
The NuGet packages should go in the SHFB project rather than your documentation source project (the .shfbproj rather than your .csproj).  See the [XCOPY/NuGet Build Server Deployment](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm) topic for information on how to add the package references to the SHFB project so that they are used.

In the current release, you need to make the changes to the project file manually.  In the next release, support has been added for managing the SHFB project NuGet packages from within Visual Studio.
