### ISSUE TITLE
SHFB: Error BE0070: Differing framework types were detected in the documentation sources (while using solution reference)

### ISSUE THREAD

**Issue by Atrejoe** [EWSoftware/SHFB#873]
Using Sandcastle 2021.4.9.0
While using a solution reference , I receive this error:
> SHFB: Error BE0070: Differing framework types were detected in the documentation sources (i.e. .NET 5 and .NET Standard 2.x).  Due to differences in how the core types are redirected, the different frameworks cannot be mixed within the same documentation project.  See the error number topic in the help file for details.

I do use different frameworks (.NETStandard 2.1 & .NETCoreApp 3.1), but I think with previous Sandcastle versions this was not an issue.

![image](https://user-images.githubusercontent.com/585091/138891007-c3703c06-4b56-4245-ab00-60b413b22427.png)

On [https://ewsoftware.github.io/ > Errors and Warnings > Build engine > BE0035](https://ewsoftware.github.io/SHFB/html/230e5a68-858d-4272-a3a2-eea156cf379b.htm) it appears to state that this should be no issue when using a solution reference and I should report it here:
> ...
If this error occurs while using a solution or project as a documentation source, please open an issue at the Sandcastle Help File Builder project site asking for help along with a small example that can be used to reproduce the issue.
...

Is there any preferred information I could provide to demonstrate this issue?

**Comment by EWSoftware** [comment]
It may have worked in prior releases but that was by accident rather than by design and there was no guarantee that it was actually working properly.  In many cases, it built the help file but the generated documentation may not have been correct with regard to the type information.

If you aren't already, use the ".NET Core/.NET Standard/.NET 5.0+" framework version setting rather than the old "Cross-platform" option.  Also, as noted in the help for the [BE0070 error](https://ewsoftware.github.io/SHFB/html/a73e776d-0f62-41ee-aa5f-637916c09553.htm), you can use the `TargetFramework` option on the documentation sources to specify a common target framework used by all the projects if they use multi-targeting so that they are compatible.  If that's not possible, they do need to be separated and you can use the Version Builder plug-in to combine them into one help file.
