### ISSUE TITLE
The attribute "Include" in element <SHFBComponent> is un recognized

### ISSUE THREAD

**Issue by alcoalex** [EWSoftware/SHFB#880]
I'm to setup my shfbproj file to create documentation for a project targeting netstandard2.0.

I've set the framework version as:
<FrameworkVersion>.NET Core/.NET Standard/.NET 5.0+</FrameworkVersion>

And I'm trying to use the following nagget packages:
- EWSOftware.SHFB v2021.1.17
- EWSoftware.SHFB.NET v5.0.0.1

However, one I restore the uget packagfes I get the following error:
The attribute "Include" in element <SHFBComponent> is un recognized

This also happens when I create my shfbproj file via the Sandcastle Help File Builder application.  

Is there something else I need to do to get this to work?

**Comment by EWSoftware** [comment]
The packages are only needed if you're going to build the project on a build server or another PC where SHFB isn't installed.  If you're always building on a PC where the tools are installed, you don't need them.

If you do need them, use the version of EWSoftware.SHFB that corresponds to the version of SHFB you have installed and use the latest version of the reflection data package.  The latest reflection data packages should work with the older versions of SHFB.  If not, try one version back.

If you've got the latest SHFB release installed (2021.11.7.0), you should add the packages using the Component Packages node in the project rather than manually editing the project file to add the package references.  That was only necessary in prior releases.  Sometimes, the packages changes are not always reflected once you close the package manager dialog.  You may need to close and reopen the project so that it sees all of the changes.

**Comment by alcoalex** [comment]
Many thanks for your quick response.

My intention is to use a build sever – I was trying the builder application on a VM just as a means to check if I was missing something.

I’ve changed this now to use v5.0.0 and it appears to have resolved this issue.

In my shfbproj file I now have this:
  <ItemGroup>
    <PackageReference Include="EWSoftware.SHFB" Version="2021.11.7" />
    <PackageReference Include="EWSoftware.SHFB.NET" Version="5.0.0" />
  </ItemGroup>
  
   
   <Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" Condition="!Exists('$(SHFBROOT)\SandcastleHelpFileBuilder.targets')" />
   <Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" Condition="Exists('$(SHFBROOT)\SandcastleHelpFileBuilder.targets')" /> 

However, I'm now getting an error in the GenerateReflectionInfo build step.  This is the error in the log fiile:

      GenerateBindingRedirects:
         No suggested binding redirects from ResolveAssemblyReferences.
       GenerateRefInfo:
         Microsoft.Build (v17.0.0+c9eb9dd64e9a2e8a433900a1a626d65a2bce4428)
         c Microsoft Corporation. All rights reserved.
         No source code context base path specified.  Source context information is unavailable.

**Comment by EWSoftware** [comment]
There should also be an import for Microsoft.Common.props at the top of the project file.  Your conditions are also not what is usually used.  See the [project template](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/VSIX_VS2017/Templates/Projects/SandcastleBuilderProject/SandcastleBuilder.shfbproj) for an example of the typical imports and their conditions.

I don't see an error, only informational messages.  Did you leave it out?

**Comment by alcoalex** [comment]
Thanks, I've restarted my project file using the template and this appears to have solved my issue - I must have had an error in the previous configuration

**Comment by felix-ri** [comment]
I have the same problem. I made a new .shfb Project via the template in VS and added these nugets:
```
  <ItemGroup>
    <PackageReference Include="EWSoftware.SHFB">
      <Version>2021.11.7</Version>
    </PackageReference>
    <PackageReference Include="EWSoftware.SHFB.NET">
      <Version>5.0.0.1</Version>
    </PackageReference>
  </ItemGroup>
```
When I try to `dotnet build` it on another machine without any SHFB software installed, I get the same error.

It seems to me, that the issue is in the *EWSoftware.SHFB.NETCore.props*: 
```
<PropertyGroup>
   ...
   <SHFBComponentPath Include="$(MSBuildThisFileDirectory)..\tools\" />
</PropertyGroup>
```

This tries to include a path to the **Property** `SHFBComponentPath`. Afaik adding paths is only supported for **Items** in MSBuild.
When I move it to its own ItemGroup, it seems to work

```
<PropertyGroup>
   ...
</PropertyGroup>
<ItemGroup>
   <SHFBComponentPath Include="$(MSBuildThisFileDirectory)..\tools\" />
</ItemGroup>
```

**Comment by EWSoftware** [comment]
The packages have been fixed and the updates published.
