### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by anastasiyaArk** [EWSoftware/SHFB#887]
I have made upgrade to version 2022.1.22.0. It was the first update since the last one for 3 years or so. I can build the project locally, but not on the build server (I use Azure DevOps) The error message is a generic one, and as log as I can see there are no other error related entries prior to that. I attach the log
[shfb_log.txt](https://github.com/EWSoftware/SHFB/files/7942388/shfb_log.txt)

**Comment by EWSoftware** [comment]
Since it works locally but not on the build server, check that the version on the server is the same or if using the NuGet packages for SHFB that the project properties are set correctly to use them.  If you use the Component Packages node in the project to add the packages, it should add the necessary properties.  There have been a number of breaking changes in the past 3 years.  The most likely issue is a problem with the configuration settings of a component or plug-in in the SHFB project.  See the actual SHFB build log rather than the one you attached as it may have more details.  Typically, opening the component or plug-in configuration and saving it will correct any issues.  In some cases it may be necessary to remove the component or plug-in and add it back to get the new configuration settings.  See the release notes for the versions between the last one you used and the current release to see what breaking changes may be causing you a problem.
