### ISSUE TITLE
Access Error: Cannot Create File or Directory

### ISSUE THREAD

**Issue by john-b-at-keysight** [EWSoftware/SHFB#889]
Using latest version 2022.1.22.0, also had the problem with 2021.11.7.0. Placed project file in its own directory, and using only .NET Core 3.1 dlls with accompanying XML files, referenced in separate directories. The build fails every time, claiming an "access error", which makes no sense because SHFB created that folder to begin with. None of the parent directories have restrictive permissions on them. The error in detail is below (absolute file path details removed). 

BuildAssembler : error : SaveComponent: [Methods.T:PpiManager.PpiDevice] An access error occurred while attempting to save to the file '[ProjectFilePath]\Help\Working\Output\HtmlHelp1\html\43c84619-9831-5662-c36d-32d29fb53add.htm'. The error message is 'The directory or file cannot be created. [[ProjectFilePath]\Help\Working\BuildTopics.proj]

**Comment by EWSoftware** [comment]
Perhaps it's running into a path length issue if the overall path length is over 260 characters and long path support isn't enabled.

**Comment by john-b-at-keysight** [comment]
The [Project File Path] is very short, only 32 characters. I can't help how absurdly long the files are that SFHB creates.

**Comment by john-b-at-keysight** [comment]
But looks like the file path, including the relative path that SFHB is creating, is only about 100 characters, so that's not it. Besides, it says it's an "access error", which sounds like either a permissions problem or that the file/folder is locked somehow.

**Comment by EWSoftware** [comment]
Can you try it on another PC to see if it's reproducible elsewhere?  Also, virus scanners have also been known to cause file access issues in the working folder.  If that's the case, excluding the working folder from being scanned resolves the issue.

**Comment by john-b-at-keysight** [comment]
Looks like I don't have permission on my (work) PC to add an exemption, so I'll try this on another PC I have access to.

**Comment by john-b-at-keysight** [comment]
Okay @EWSoftware  I reproduced it on a separate PC

**Comment by john-b-at-keysight** [comment]
Weirdly enough, it looks like it's the same file, too, that it has a problem with. I also recreated the SFHB project from scratch.

**Comment by john-b-at-keysight** [comment]
Okay I tried removing some documentation source files, and all the (manually added) references and I get the same error, but with a different file (227068e9-b741-365d-ce13-a099e9090e1b.htm).

**Comment by EWSoftware** [comment]
Does it do it for other projects?  Can you send me an example so that I can try to duplicate the issue?

**Comment by john-b-at-keysight** [comment]
Nope it doesn't do it for other projects. I have one other project I use SHFB for and it's never done this. Unfortunately the project itself and documentation sources are proprietary, and I can't share them directly. Anything else I can provide that isn't specific to the files?

**Comment by EWSoftware** [comment]
Without something I can use to try and duplicate the issue, I can't find it or fix it.  I wouldn't need the source code, just the assemblies to use as documentation sources and the SHFB project so that I can try to duplicate it.  If that's not an option, you can always download the code and try to find the issue.

**Comment by john-b-at-keysight** [comment]
Well the issue is that not only are the dlls in an unreleased and not customer-viewable state with the XML files, so with legal issues there, but the software is subject to ITAR (International Traffic in Arms Regulations), and anyone who is provided access must be verified. 

I'll try cloning/building/running the source, see if I can get more details on the problem that way. If it's something with the code and I can fix it, I'll branch and put in a pull request. Would you need to add me so I can get permission to do that?

**Comment by EWSoftware** [comment]
No permissions are needed.  Pull requests are open to anyone.

**Comment by EWSoftware** [comment]
I thought of one other thing you can try.  The save component actually writes out the topics in a background task.  The "Maximum Save Component writer task cache capacity" property in the Build category of the project properties controls the cache size.  You can try setting it to 1 to effectively make it synchronous.  It may have no effect but may be worth a try to eliminate it as a possible cause.

If you decide to pursue debugging the source, let me know and I can walk you through setting up the test case.

**Comment by EWSoftware** [comment]
Once you downloaded and extracted the code:

1. Edit the system environment variables and change the SHFBROOT environment variable so that it points to the build location for the tools.  Be sure to include the trailing backslash.  For example: C:\SHFB-master\SHFB\Deploy\
2. Copy the reflection data files from the release version of SHFB (C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data) to the build tools location (example: C:\SHFB-master\SHFB\Deploy\Data).  Overwrite any existing files from the code download.
3. Open SHFB-Master\SHFB\Source\SandcastleTools.sln and rebuild the Debug configuration of the solution.
4. Set SandcastleBuilderGui.csproj as the startup project and run it.
5. Open your project in the standalone GUI and build it.  Once it fails, you can exit the standalone GUI.  This will generate the files for debugging in the working folder of the project using the debug version of the SHFB tools.
6. Set BuildAssember.csproj as the startup project.
7. Edit its properties and go to the Debug category.
8. Set the executable to run to MSBuild.exe for the version of Visual Studio you are using.  For example, VS2022 Community Edition: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
9. Set the command line arguments to BuildTopics.proj which is the project file that runs to build the topics.
10. Set the working folder to the working folder for your project.  Assuming you are using the default settings, this will be [ProjectFolder]\Doc\Help\Working where [ProjectFolder] is the folder containing your SHFB project.
11. Open BuilderAssembler.cs and set a breakpoint in the Execute() method.
12. Run the project and, if you've set the properties correctly, you should see MSBuild start up and then stop on the breakpoint.
13. Go to BuildComponents.csproj and open the SaveComponent.cs file.  You can set breakpoints in the methods there to do what you need.  Note that it may not be loaded yet so the breakpoints won't show as active until you continue execution and the main task loads the components assembly.
