### ISSUE TITLE
Extension method icon

### ISSUE THREAD

**Issue by maxtoroq** [EWSoftware/SHFB#901]
Although the HTML output includes an icon to represent extension methods (pubextension.gif) it seems it's never used, showing instead both method and static icons. Here's an example: https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Linq_Extensions.htm

**Comment by EWSoftware** [comment]
Currently, the icon does show up but only when it's an extension method of the type on the `this` parameter.  So, to see the extension method icon you have to have that type or one derived from it documented and it will get an Extension Methods section.  Here's an example from the SHFB test case project.  That's where the icon is currently used.

![image](https://user-images.githubusercontent.com/10552523/158038376-d34e5f24-88c3-4f42-a41a-01cd7494b8c6.png)

I see that IntelliSense in Visual Studio does show the extension method icon when you type the containing type name to call it explicitly like a normal static method.  Nobody's ever noticed that it doesn't show the extension method icon in the member list documentation page for the containing type before.

I'm currently overhauling the presentation style implementation so I've applied a fix there so that it is consistent with IntelliSense.
