### ISSUE TITLE
There is a way to change the sections order?

### ISSUE THREAD

**Issue by amcrally** [EWSoftware/SHFB#902]
I'm using Visual Studio 2022 add-on.
The order of the sections are always:
Summary
Sintax
Properties, Methods and events
Remarks
Example

There's a way to change this order? I would like put Remarks immediatly after Summary. Can I do it?

**Comment by EWSoftware** [comment]
It's only possible right now by creating a clone of the existing presentation style and modifying the related XSL transformation.  However, I am in the process of overhauling how the presentation styles are implemented (#868).  Part of that is making it easier to do things like this with a simple plug-in that modifies how the existing presentation styles work rather than having to clone the whole presentation style.

It may be a while before it's completely ready for public use.  I'm not quite done with the changes that will allow this particular option but, if you're interested, I can let you know when it is available and provide an experimental release if you want to try it out.

**Comment by amcrally** [comment]
why not? Of course! If I can be useful I will do it

**Comment by EWSoftware** [comment]
I didn't get around to releasing an experimental release as things were changing quite often.  The new release will be out soon, probably this weekend.  I ended up moving the Remarks section anyway.  It now appears after the Syntax Section to be consistent with Microsoft Docs.  If you still want to move it so that it appears right after the Summary section you can.  I'll be publishing an example plug-in that demonstrates how to do that.
