### ISSUE TITLE
Auto completion broken in VS 2015

### ISSUE THREAD

**Issue by wmjordan** [EWSoftware/SHFB#91]
After enabling SHFB, the auto completion of XML documentation in C# got broken, when I typed "&lt;para", select "paramref" in the auto completion list and press the tab key, the auto-completion failed to expand it to "&lt;paramref name="">&lt;/paramref>".

**Comment by EWSoftware** [comment]
You can disable it in Tools | Options | Sandcastle Help File Builder for the time being.  Uncheck "Enable extended XML comments completion options".  You may need to restart after disabling it or at least close and re-open any affected editors.

**Comment by wmjordan** [comment]
Thank you for the instruction.
After disabling the setting, the XML comment documentation was turned back to normal.
Please have this issue fixed as we do need the extended XML comments :)

**Comment by sharwell** [comment]
I figured this out, and will send a pull request. :smile:

**Comment by wmjordan** [comment]
Thanks great!

**Comment by wmjordan** [comment]
The fix had not fully fixed this issue.
If there are more than one `paramref` element in the XML documentation, the second `paramref` will not have code completion. @EWSoftware

**Comment by EWSoftware** [comment]
With VS2015 Update 1 and the latest release of SHFB, it autocompletes as expected when I select `paramref`.  It works the same with the extended option off too so I'm not seeing any issue with it.

**Comment by wmjordan** [comment]
Please take a look at this example:

 	/// <summary>
	/// Converts the <paramref name="value" /> to a new value during serialization.
	/// </summary>
	/// <param name="value">The value to be serialized.</param>
	/// <returns>The new value.</returns>
	object SerializationConvert (object value);

Please try it several more times inside the same `summary` element but different place. After several tries, the completion will occasionally break.

**Comment by EWSoftware** [comment]
Sorry, but it still works.  I got up to 15 entries and stopped trying.  Perhaps you're just selecting the `para` element which is just above `paramref`.

**Comment by wmjordan** [comment]
Thank you for trying. I reproduced the bug and here are the details of my operations:
1, Type `<para` and press the Down Arrow key to select `<paramref name=""/>` from the completion list, then press Enter key to select the item.
2, Type something inside the `name=""`, and press the Right Arrow key to move the caret somewhere else behind the finished markup.
3, Type `<para` again, and the completion list will highlight and select the previously selected `<paramref name=""/>` item.
4, Press Enter key to select the item. `<para` will no longer be completed as the selected `<paramref name=""/>` from the completion list.

**Comment by sharwell** [comment]
I'm now able to reproduce a few discrepancies using the steps indicated.

**Comment by sharwell** [comment]
The problem lies in [this block of code](https://github.com/drew-gross/SHFB/blob/856d5e4d122d30f82502b75300c5af98a2f623e4/SHFB/Source/SandcastleBuilderPackage/IntelliSense/AugmentedCompletionSet.cs#L216-L227). Using the steps posted by @wmjordan, the completion selected by Roslyn is not unique (there are two potential matches even if one is better than the other). This prevents the use of selection information provided by Roslyn and ultimately ends up calling `base.SelectBestMatch`. I believe there are some additional cases where using `_source.SelectionStatus` or `_secondSource.SelectionStatus` may be beneficial.

* Use `_source.SelectionStatus` if it is selected (`IsSelected` is true) but the selection from `_secondSource.SelectionStatus` is not selected
* Use `_secondSource.SelectionStatus` if it is selected (`IsSelected` is true) but the selection from `_source.SelectionStatus` is not selected

This would address the case encountered by @wmjordan because `<para` and `<paramref` are in `_source` while no items starting with `para` are located in `_secondSource`.

**Comment by EWSoftware** [comment]
Apparently hitting the Enter key makes the difference.  I always use tab to autocomplete so was not seeing the issue.

**Comment by sharwell** [comment]
I have narrowed down the problem and it's a bit different than I thought. The underlying cause is Roslyn updates the selection in its completion set differently from the editor, so the call to `_source.SelectBestMatch()` [does nothing](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/Presentation/CompletionSet2.cs#L131-L135).

The only remaining issue is I'm not entirely sure why [this code](https://github.com/EWSoftware/SHFB/blob/856d5e4d122d30f82502b75300c5af98a2f623e4/SHFB/Source/SandcastleBuilderPackage/IntelliSense/AugmentedCompletionSet.cs#L198-L204) exists.

**Comment by sharwell** [comment]
If you're curious why this bug produced the specific behavior you observed, it's actually quite interesting. My previous update on this issue (#93) only covered the major case where the user changes the selection by pressing one of the navigation keys (up, down, etc.). Navigation keys result in the IDE changing the `SelectionStatus` property of the augmented completion set (the set which is shown to the user with both Roslyn and SHFB items). The case I failed to handle is when something changes one of the underlying sets (Roslyn items or SHFB items) directly.

The specific thing that can change here is Roslyn recalculating the best match outside of `SelectBestMatch()` and setting the result on its completion set. Normally even this wouldn't be a problem, because the change would still be picked up by the IDE on the next call to `SelectBestMatch()`. However, following a keystroke the IDE calls `SelectBestMatch()` *before* Roslyn updates its selection. This means at the specific point when the IDE requests a selection for `<para`, Roslyn is still reporting results from the last update, `<par`. Since `<par` didn't exactly match an item, it used a most recent item instead.

This specific situation can only occur when the Roslyn completion list contains two or more items, where one is a prefix of the others. It also only occurs when you exactly type the shorter item after you complete one of the longer items. This would appear for `para`/`paramref`, `see`/`seealso`, and possibly `c`/`code` (not sure if the single character case results in this). It might also occur for `para`/`param` if you complete the `param` and then remove it from the text before trying to complete `para`.
