### ISSUE TITLE
Exapnding topics doesn't work

### ISSUE THREAD

**Issue by mckool23** [EWSoftware/SHFB#918]
Hello there,

So far I was generating my help as CHM, and it worked perfect. Now, building the help as HTML, I found that clicking the arrow to expand a topic doesn't seem to be working. Only clicking on that topic let me see the sub topics. 

Is this a known issue, or is there any option that I forgot (and can use) to chagne this behavior? 

Attached a video that shows what I mean. First you see the docuemntaiton of newtoonsoft.Json (think they use SHFB too), and then the help I am building now:
[ExpandingPRoblem.webm](https://user-images.githubusercontent.com/102285602/178001307-19d61093-61fe-4022-9361-6ac0d717d5c7.webm)

Thanks in advance for your help.

**Comment by EWSoftware** [comment]
Made sure you're opening the website output using the View Help File or View Website (Local Web Dev Server) option and not from the file system directly.  If opened from the file system, the browser blocks the script from running and you won't be able to use the TOC.  Using either of the view options starts a web server instance so that it can be viewed normally with script support.

**Comment by mckool23** [comment]
Sorry, my fault, I was indeed calling the index.html directly. Thanks for your help!
