### ISSUE TITLE
Intellisense component shouldn't longer filter out remarks 

### ISSUE THREAD

**Issue by chm-tm** [EWSoftware/SHFB#927]
... since Visual Studio now shows remarks as a separate paragraph below the summary.

**Comment by EWSoftware** [comment]
It took me a while to track this down.  The remarks are only shown in the Quick Info popup when you hover the mouse over the member, not the IntelliSense completion popup that appears when typing.  It can also be turned off in the Text Editor options.  Anyway, I'll add them so that they appear when the option is enabled.

**Comment by chm-tm** [comment]
Sorry for not being more specific on where the remarks appear.
I really like the possibility of showing remarks since there is still no F1 experience for 3d-party libraries.
