### ISSUE TITLE
MSBuild Environment varibales not expanding

### ISSUE THREAD

**Issue by sudarsanyes** [EWSoftware/SHFB#94]
When I try to add environment varibales to the DocumentationSources, it  does not expand during the build. 
For example, 
<pre>
    &lt;DocumentationSources&gt;
      &lt;DocumentationSource sourceFile="$(SOURCE)BrandIdentity.dll" /&gt;
    &lt;/DocumentationSources&gt;
</pre>
where SOURCE is defined while launching the msbuild using /p:SOURCE=..\..\..\bin\debug

is not working.

**Comment by EWSoftware** [comment]
The option appears to be working.  I do notice that you did not include a backslash in the `sourceFile` attribute nor did you include one on the end of the property override command line option.  In such cases, it'll join the two together without the separating backslash giving the wrong filename.  I'd suggest including it in the `sourceFile` attribute of the documentation source since the command processor tends to interpret trailing backslashes as escapes in some cases.

``` XML
<DocumentationSource sourceFile="$(SOURCE)\BrandIdentity.dll" />
```

**Comment by sudarsanyes** [comment]
@EWSoftware thanks for your reply. You are correct! Guess the backslash screwed up my script. 
Now, 
<pre>
    &lt;DocumentationSources&gt;
      &lt;DocumentationSource sourceFile="$(SOURCE)\BrandIdentity.dll" /&gt;
    &lt;/DocumentationSources&gt;
</pre>

seems to be working fine, if I run the msbuild command like this, 

<pre>
msbuild MyLib.shfbproj  /p:OUTPUT="C:\users\sudarsanyes\desktop\help"
</pre>
