### ISSUE TITLE
Question: nested sections

### ISSUE THREAD

**Issue by MarcelVersteeg** [EWSoftware/SHFB#945]
In my project I came from SHFB version 2020.3.6 and now I updated to version 2022.10.15.

In some of my `.aml` files I have nested sections like this:
```
<section address="MySection">
  <title>My Section</title>
  <sections>
    <section address="MySubsection">
      <title>My Subsection</title>
      <content>
        ....
      </content>
    </section>
  </sections>
</section>
```

However, with the latest SHFB, these sections that contain subsections are no longer rendered in the output (WebSite), but they do show up in the outline (via the `<autoOutline>` tag). Also when I open the `.aml` file in VS2022 (with the SHFB plugin installed), I see that the `<sections>` element inside a `<section>` is not supported.

How can I now add these sub sections to my `.aml` files? I have tried to search through the version history to see something related to this, but was could not to find anything.

**Comment by EWSoftware** [comment]
The `sections` element is valid inside a `section`.  The validation error is about the missing `content` element which is required but itself can be empty.  The latest release replaces all of the old XSL transformations with a code-based model.  My interpretation of the XSL was that if the `content` element is empty, it skips the section.  It looks like the XSL transformation in that case then went on to handle the sub-elements such as `sections` anyway.  The new code-based transformation isn't doing that and skips everything.

You can work around it for the time being by adding a `content` element with an empty `para` element.

```
<section address="MySection">
  <title>My Section</title>
  <content>
    <!-- Work around the empty content issue -->
    <para/>
  </content>
  <sections>
    <section address="MySubsection">
      <title>My Subsection</title>
      <content>
        ....
      </content>
    </section>
  </sections>
</section>
```

That satisfies the non-empty content requirement and it will render the subsections.  I'll fix it so that it renders them even when the content element is missing or empty.

**Comment by MarcelVersteeg** [comment]
The workaround indeed helps to get the sections shown again.

**Comment by MarcelVersteeg** [comment]
@EWSoftware 
I have seen there is a new release of the installer package that contains this fix, but there is no new NuGet package. Is installing the new version via the installer enough, even when I use the NuGet package in my project?

**Comment by EWSoftware** [comment]
I see the NuGet package out there:  https://www.nuget.org/packages/EWSoftware.SHFB/2022.12.30

The NuGet package is only required if you're building somewhere that the tools are not installed like a build server.  If you need the fix in such cases, you'll need the related release.

**Comment by MarcelVersteeg** [comment]
I'm sorry I didn't check Nuget.org directly, I was relying on the "Manage NuGet packages for solution" option in Visual Studio. And somehow, even though there are package references in the sandcastle projects, when opening the manager in Visual Studio the entire sandcastle package is not listed at all (also not in the "Installed" list), which also means that it was not showing an available update.

It must be because of some VS2022 update that it is no longer seen in the list anymore or something else. I need to check on another computer to see if the manager in Visual Studio displays SandCastle as an installed package or not....

For now, I will just update the NuGet package reference by hand in the project(s), as the command line NuGet restore command actually does restore the package as expected.
