### ISSUE TITLE
.NETFramework 4.8 and .NETStandard 2.0 gives BE0070

### ISSUE THREAD

**Issue by Riuujin** [EWSoftware/SHFB#958]
According to the documentation: 
> Typically, projects for the full .NET Framework and .NET Standard 2.x can be mixed in the same help file builder project.

Yet when add a project of .NETFramework 4.8 and a project of .NETStandard 2.0 I get the "BE0070" error.

Is it simply not possible or could I be doing something wrong?

> \-------------------------------
\[Sandcastle Help File Builder and Tools, version 2022.12.30.0]
Creating output and working folders...
The Sandcastle tools are located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder'
Locating components in the following folder(s):
    \*\*
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Components
Using framework reflection data for '.NET Framework 4.8' located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework'
Using presentation style 'Default2022' located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Components\Default2022'
Loading and initializing plug-ins...
Website Table of Contents Generator Version 2022.12.30.0
Copyright © 2006-2022, Eric Woodruff, All Rights Reserved
\-------------------------------
Clearing any prior web/markdown output...
\-------------------------------
Validating and copying documentation source information
Source: \*\*.csproj
    Found project '**.csproj'
Source: \*\*.csproj
    Found project \'*\*.csproj'
Parsing project files
    Found assembly '\*\*.dll' (.NETStandard 2.0)
    Found assembly '\*\*.dll' (.NETFramework 4.8)
    Last step completed in 00:00:00,8276
\-------------------------------
SHFB: Error BE0070: Differing framework types were detected in the documentation sources (i.e. .NET 5 and .NET Standard 2.x).  Due to differences in how the core types are redirected, the different frameworks cannot be mixed within the same documentation project.  See the error number topic in the help file for details.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

Build log, paths have been repleaced with **

**Comment by EWSoftware** [comment]
It used to be allowed but I started running into too many cases where it would just randomly fail due to differences in the frameworks, typically where attributes were involved such as EditorBrowsable for some reason.  As such, it's no longer possible.  I have plans to support mixed platform types to allow adding platform info to the topics.  That will require some extensive reworking so no firm date on when that will be available.

If the documentation source solutions and projects use multi-targeting and share a common target framework, you can set the target framework to use explicitly by specifying it in the TargetFramework property on each documentation source.  If not, a workaround for the time being is to use the [Version Builder plug-in](http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm).  One project would go into the main documentation project, the other would go in the documentation project added to the configuration settings of the plug-in.  The plug-in builds the other project separately and the information is merged into the primary project's output but it's treated like a different version instead of a platform so there's a Versions section rather than an Applies To/Platforms section.

**Comment by Riuujin** [comment]
I assume when you say target framework you mean like this:
![image](https://user-images.githubusercontent.com/5675840/210861144-b42121d7-110d-4bfe-be86-5471e2290dda.png)

If I do that for each project i still get the same error.

**Comment by EWSoftware** [comment]
Yes, that's the property.  However, both documentation source projects have to support building output for the common framework you specify.  For example:

```
<TargetFramework>net48</TargetFramework>

or

<TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
```

As long as the target framework is common to both, it will use the indicated version to build the documentation.  If it can't find the one you specify in all projects, it will still refuse to build them together.
