### ISSUE TITLE
Markdown / Open XML

### ISSUE THREAD

**Issue by gnimor** [EWSoftware/SHFB#969]
So first of all, this is not really an issue but a question.

Reading the release notes of version 2022.8.14.0 there is mentioned that CHM format is deprecated. Now we are thinking to switch to Open XML or Markdown output. However we are not sure with which viewer the help files can be opened afterwards. 

With CHM format it was no problem. Our installer just included the CHM file and on the target machine a double click opens the help file (or event context sensitive help was possible with F1) without installing extra tools. Context sensitive help for our WPF application is more or less mandatory.
 
With Open XML, it seems an office installation is required on the target machine - and for Markdown - to be honest I am not sure what to use...

So we are a little bit lost with the "CHM" format "deprecated" information. Any hint would be very appreciated.

**Comment by EWSoftware** [comment]
Deprecated doesn't mean removed.  It just means it will no longer be supported as an output format in presentation styles like the new Default 2022 style and any future ones.  It's now a legacy format so it's still there but only in the VS2013 style which will be retained as long as it's viable.  I couldn't find anything definitive, but the IE controls used by the CHM and Help 2 viewers should be good through 2029 assuming it matches end of life for IE mode in the browser so look at that as a possible end date.  Also note that you can't even download the HTML Help Workshop from the Microsoft site anymore as the link has been broken for a long time.  I'm hosting a copy here for those that need it.

Open XML generates .docx files which can be opened in Word, Open Office, or anything else that supports them.  They're also convertible to other formats such as PDF but will likely needs some manual fix ups first to remove blank pages and that sort of thing.  It's not a good fit for context sensitive application help though since it is just a document.  Markdown is a web-based format.  You'd need to host it somewhere that converts it to HTML like a GitHub wiki.

Website output is an option if you've got somewhere to host it since it's simple enough to generate links to online topics.  I replaced the SHFB CHM help files with links to the online topics in the standalone GUI and Visual Studio package for context-sensitive help.  That assumes you can have online content and don't need an offline-only option.  I'm not aware of anything that could replace a CHM file for offline-only context-sensitive help content.
