### ISSUE TITLE
HTML search functionality

### ISSUE THREAD

**Issue by sccrgoalie1** [EWSoftware/SHFB#97]
I'm launching the html help file within an embedded WPF web browser control and it works great except for the search page.  After you search, the links that show up are configured to open in a new window which gets outside my application to the default web browser.  Is there a built in way to change the links on the search page to target _self?

Thanks!

**Comment by EWSoftware** [comment]
Change the SDK Link Target property in the Help category to Self.  It controls where the external topics open.

**Comment by sccrgoalie1** [comment]
Thanks for the quick response!  Changing that doesn't seem to do the trick.  The links on the search results page are all internal links to other help pages.

**Comment by EWSoftware** [comment]
Sorry, misunderstood.  The search pages all hard code the target to "_blank".  That was done intentionally so that the search results page remains open and you can go back to it without having to navigate away from or close any opened result pages in the browser.  You can edit Search.aspx, Search.inc.php, and scripts\branding-Website.js and replace the target with "_self" to change the behavior.

**Comment by sccrgoalie1** [comment]
That does the trick.  Thanks!
