### ISSUE TITLE
Feature Suggestion - "JSON" Language Option

### ISSUE THREAD

**Issue by legistek** [EWSoftware/SHFB#970]
Not sure how common this is, but all my APIs are meant to be consumed by C# code as well as by Javascript code. For instance if I have an `Account` object, its C# definition might look like this:

```
public class Account 
{
     /// <summary>
     /// The user login.
     /// </summary>
     [JsonProperty("the_login")]
     public string TheLogin {get; set;}
}
```

In the documentation that member will show up as:
```
Account.TheLogin Property
The user login.

...

[JsonPropertyAttribute("the_login")]
public string TheLogin { get; set; }
```

and at the class level:

```
TheLogin        The user login.
etc.
```

However, it would be amazingly awesome if one of the possible language filters was just JSON, in which case the documentation used the attribute value for `JsonProperty` or `JsonPropertyName`  to generate the name, as in just:

```
Account.the_login Property
The user login.

...

the_login
```

and at the class level:

```
the_login        The user login.
etc.
```

I realize this might be considered more the domain of something like Swagger, but I don't like the idea of having to have two sources of truth for my APIs. 

Could something like this be done through plugins/extensions? (Or has it already??)

Many thanks for keeping this amazing product alive.

**Comment by EWSoftware** [comment]
Changing the topics as a whole to replace all references with their Javascript/JSON name counterparts via the language filter is probably rather difficult since it's really only geared toward syntax and not the name which is constant.  This is probably a better fit for a syntax generator that would add a new syntax section for JSON.  There's already a [Javascript syntax generator](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/BuildAssembler/SyntaxComponents/JavaScriptDeclarationSyntaxGenerator.cs).  You could probably adapt that to generate equivalent syntax but use the name from the attribute as the member name and render syntax and/or usage examples similar to the VB and VB usage syntax generators.
