### ISSUE TITLE
Silent and offline installation(s) impossible

### ISSUE THREAD

**Issue by W-e-r-n-e-R** [EWSoftware/SHFB#976]
Dear Sir,

I'd like to inform You of some issues I had on Windows 10 with Visual Studio 2019/2022 with [Help File Builder and Tools v2022.12.30.0](https://github.com/EWSoftware/SHFB/releases/tag/v2022.12.30.0) which might be the same with [Help File Builder and Tools v2023.3.4.0](https://github.com/EWSoftware/SHFB/releases/tag/v2023.3.4.0):
A. The HTML Help Workshop copy shows (/?) there should be a /Q switch for silent installation. Nonetheless the contained setup.exe therein does not care and shows (dialog/message) boxes.
B. msiexec /i SandcastleHelpFileBuilder.msi /quiet /passive /qn ([see Microsoft Learn](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec))
is quiet and starts but the installation hangs somewhere and the process has to be killed somehow.
Perhaps a response file or some foolproof default settings could help with suppressing the dialog windows and message boxes.
C.  Going to &lt;MyVisualStudio2019InstallationFolder&gt;\Common7\IDE folder and executing
VSIXInstaller.exe /quiet &lt;MyInstallResourcesUnzippedFolder&gt;\SHFBVisualStudioPackage_VS2017And2019.vsix
or
going to &lt;MyVisualStudio2022InstallationFolder&gt;\Common7\IDE folder and executing
VSIXInstaller.exe /quiet &lt;MyInstallResourcesUnzippedFolder&gt;\SHFBVisualStudioPackage_VS2022AndLater.vsix
won't be quiet at all and, moreover, if some additional files (Microsoft.VisualStudio.Debug...) cannot be downloaded from the internet, the process fails. I thought [Remote Tools for Visual Studio](https://visualstudio.microsoft.com/downloads/#remote-tools-for-visual-studio-2022) installation was only necessary on remote machines, but somehow the SHFB Plugins seem to want the Remote Tools for Visual Studio, unless we have an unsupported operating system (e.g. the newest release of Windows 11 with [Help File Builder and Tools v2022.12.30.0](https://github.com/EWSoftware/SHFB/releases/tag/v2022.12.30.0))
I would prefer an exhaustive list of prerequisites rather than the installer fetching some internet stuff.

Sincerely

Werner

P.S. The VSIXInstaller help comes as a message box upon double-clicking the VSIXInstaller.exe in &lt;YourVisualStudioInstallationFolder&gt;\Common7\IDE\

**Comment by EWSoftware** [comment]
I have no control over the HTML Help Workshop installer since it's Microsoft's product.  Since it's likely unsupported now, I doubt there's much chance they'd do anything to fix it if there is an issue.  That said, you only need it if you will be using the legacy VS2013 presentation style to create Help 1 (CHM) files.  If you will only create Help Viewer (MSHC), website, markdown, or Open XML files it can be skipped.

I don't recall any issues being reported with silent installs before and haven't had any issues with the msiexec installing silently myself.  Both msiexec and VSIXInstaller have logging options.  Enabling logging may provide insight into any issues they have during the installation process on your systems.  I know people have created Chocolatey packages for silent installation so it is possible.

I can't say why the VSIXInstaller isn't honoring the quiet option and haven't used it myself.  You'll have to report that to Microsoft if you think it's an issue they need to fix.  With VSIX files, you define what dependencies your package has and, if needed, it goes and gets them.  As far as I know, there are no provisions for embedding them directly in the package installer itself so that isn't something I can do, nor would I want to as it would likely bloat the installer's size significantly and unnecessarily.

I only declare two dependencies: Microsoft.Component.MSBuild and Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites.  It's likely both have their own dependencies that will install if not present which is likely why the remote tools are being pulled in even though I don't request them as a direct dependency in the package.
