### ISSUE TITLE
WebToc.xml not generated  EWSoftware.SHFB.2022.10.15.1

### ISSUE THREAD

**Issue by jmecosta** [EWSoftware/SHFB#981]
Hi,

we have some questions about a missing WebToc.Xml. We have updated the doc to use EWSoftware.SHFB.2022.10.15.1 and .net 6 and this file is no longer found in the html documentation

Do we have to include some additional flag to generat this file?

thanks in advance

Jorge Costa

**Comment by EWSoftware** [comment]
Are you using the new Default2022 presentation style?  If so, it isn't used by that presentation style and is not generated.  It's only used and generated by the VS2013 presentation style.

**Comment by jmecosta** [comment]
Will it be removed at some point? Since it's from a ancient visual studio?
Thanks

**Comment by EWSoftware** [comment]
The VS2013 style will be around for a few years yet.  It's the only one that will output the Help 1 and Help Viewer formats.  So, as long as they continue to work, it will be there.  Best guess is they'll continue to work at least through 2029 as that's when the old Internet Explorer control is likely to reach end of support and be removed.

**Comment by Venca-M** [comment]
Hi, @EWSoftware unfortunately the VS2013 style does not solve this problem. The presentation style was always set to this value in our shfbproj file. The file WebTOC.xml is still missing. Is there anything else that could be interfering with generation of WebTOC.xml?

Thanks,
Venca

**Comment by EWSoftware** [comment]
It is generated but it's in the working folder now rather than the output folder since it's only used by the Lightweight TOC plug-in to generate it's TOC files.  It isn't used by the live site at all so it isn't included in the output.  Is it something you need in your live site?  If not, and it's just for another plug-in or something, you can point it to the copy in the working folder instead.
