### ISSUE TITLE
Why .chm(html help 1) help file format is not supported

### ISSUE THREAD

**Issue by wzqiwhy** [EWSoftware/SHFB#986]
The .chm format is not supprted even though I have installed "HTML Help Workhop" corectly. Why?

1. this screenshot shows I installed "HTML Help Workhop" successfully
![c8fbbc206f620d3a636a87c61635c8d](https://user-images.githubusercontent.com/130955553/232381638-02748d98-b246-45cf-9874-ac80b4f34ae9.png)

2. But there is no chm format in this view
![a4b078674433ca9773981fb01111c5f](https://user-images.githubusercontent.com/130955553/232381655-1c7d9c75-01b2-47fc-b51f-8be82ce6e8bb.png)

3.I search a screenshot online which has chm format
![3cf72e659dd2f3816fa5ce3f89e4130](https://user-images.githubusercontent.com/130955553/232381675-599305aa-7524-44b2-b472-0e4b4207e44d.png)

**Comment by EWSoftware** [comment]
The new Default 2022 presentation style does not support Help 1 or Help Viewer output because the browser control used by the related viewers is incapable of displaying the more modern HTML and script that it outputs.  I did not want to limit the new presentation style due to the viewer limitations.

As such, if you need Help 1 or Help Viewer output, you'll need to use the older VS 2013 presentation style.  Select it using the Presentation Style property on the same page.  See the [v2022.8.14.0 release notes](http://ewsoftware.github.io/SHFB/html/502f1147-eaa4-4150-813d-a57eb6b521e8.htm) for details.
